### ISSUE TITLE
block.setCmdPost() doesn't work

### ISSUE THREAD

**Issue by morevnaproject** [CGRU/cgru#107]
Hello!

I am constructing a job and trying to set Post Command to execute after its completion: block.setCmdPost(command)

But when job is submitted to server, no post command is executed.

I have tried with the stable release (2.0.2) and self-compiled development (7e475efdc).
Any help is appreciated. ^__^

**Comment by cg-cnu** [comment]
Trying to execute a command after block completion (basically render locally and copy it back to the main server machine). Can you explain what you mean by 'use another block and dependencies'. Noticed one more function 'setDoPost' Isn't it supposed to do the same?

**Comment by cg-cnu** [comment]
Trying to execute a command after block completion (basically render locally and copy it back to the main server machine). Can you explain what you mean by 'use another block and dependencies'. Noticed one more function 'setDoPost' Isn't it supposed to do the same?

**Comment by timurhai** [comment]
timurhai commented on Sep 11, 2014
Hi.
post_command, and job and block are executed on job deletion and are designed to clear temporary files ( temp scenes for render )
