### ISSUE TITLE
[MODIFY FEATURE] modify "non_sequential" task solving mode to render a predefined step size instead of the current behaviour

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#108]
Hey Timur,

this is just a follow-up on our email conversation.

I think it would be nice to modify the current behavior of the "non_sequential" task solving to be more robust for actual production use.
Imagine i have two renderlayers in maya with different frame ranges:
environment: 1001-1200
car: 1080-1120

The current solver would solve like this:
environment: 1001,1200,1100,1050,1150,1025,1075,1125,1175 and so on...
car: 1060,1120,1090,1075,1105 and so on...
but this is impractical for our comp guys, since they almost never have matching frames to properly test the 3d layers.

For our purpose we would like to have every 10th frame (maybe this could be an env var called af_non_sequential_stepsize) for checking before rendering the full animation.

Do you think this is doable? Can you point me to the place where you actually implemented the logic to decide which frame is the next in line while using the "non_sequential" feature? maybe i can find a way to modify the feature with my limited c++ knowledge...

thanks in advance
Oli

**Comment by timurhai** [comment]
Hi.
Soon!
http://cgru.info/changes_log#latest

**Comment by ultra-sonic** [comment]
thx for the frame_sequential parameter timur!

**Comment by ultra-sonic** [comment]
Hi Timur,

just a tiny request to make the "frame_sequential" feature even more useful.
Can you add the very first and very last frame of a block to the sequential preview frames(preferably as the first frames that will be dispatched)? 

This would be helpful for our comp guys since they will have their readnodes start/end parameters setup properly from the first time that they load the sequence.

let me know what you think!

regards
Oli

**Comment by timurhai** [comment]
Hi.
So you want, for frame range 95 - 135 and sequential 10, render 95,100,110,120,130,135 frames first?

**Comment by timurhai** [comment]
Hi  )
Or may be 95,135,100,110,120,130 - to setup frame range first?

**Comment by ultra-sonic** [comment]
Exactly like this! 95,135,100,110,120,130

**Comment by ultra-sonic** [comment]
Hi timur,
did you already implement this or is it on hold?

**Comment by timurhai** [comment]
95, 135 - not yet

ps
right now i am rewriting nodes attributes help, to combine attribute, description, JSON and Python on one place:
http://cgru.info/afanasy/job

but i almost finished, and then it will be easy to fix sequential

**Comment by ultra-sonic** [comment]
documention looks good! i haven't seen the WT function of job yet! very
nice as well!

**Comment by timurhai** [comment]
Fixed! You can check now.

**Comment by ultra-sonic** [comment]
WORKING! thx again! you are THE MAN!
