### ISSUE TITLE
[feature request] do not overwrite existing images

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#109]
hey timur,

how hard would it be to implement a feature to not not overwrite existing images? Of course given the fact that the "files" property of the tasks are set properly.

thx in advance
Oliver

**Comment by ultra-sonic** [comment]
any news on this?

**Comment by timurhai** [comment]
Hi.
This can happen only in 2.1.0 as such afrender or afserver will not be compatible with 2.0.x

It can be at the end of this year, i think.

**Comment by ultra-sonic** [comment]
cool! end of the year sounds fair...i don't need the feature
urgently...it's just easier to wrangle failed jobs, but that is not needed
very often!

**Comment by timurhai** [comment]
Hi.
http://cgru.info/changes_log#release210
Done in code, now i am testing, you are welcome too.

After some tests i'll install 2.1.0 at work.
Later i'll implement it in several submitters to use at work and test more.
And only later there will be a release.

**Comment by ultra-sonic** [comment]
Sounds great....i am in the middle of production so i can't test right now,
but maybe by the end of January!

**Comment by ultra-sonic** [comment]
can I enable/disable this on a currently active job through the UI?

**Comment by timurhai** [comment]
Hm. It seems that you can't.
Let`s reopen this issue.

**Comment by timurhai** [comment]
Was done http://cgru.info/changes_log#release210
