### ISSUE TITLE
Linux Pathsmap is stripping the root path, but not replacing it

### ISSUE THREAD

**Issue by sharkvfx** [CGRU/cgru#112]
I have pathsmap set up in config_default.json
"OS_unix":{
        "cmd_shell":"/bin/sh -c",
        "pathsmap":[
            ["/array/X/","X:/"]
        ]
    },
but on linux renders I get the following error for a render to X:/Test/EyeTest/test.nk

---

HOSTNAME=render01
NUKE = '/usr/local/Nuke7.0v5/Nuke7.0'
Nuke 7.0v5, 64 bit, built Mar  1 2013.
Copyright (c) 2013 The Foundry Visionmongers Ltd.  All Rights Reserved.
Starting CGRU Nuke add-ons from:
/array/X/Library/cgru/cgru-linux/plugins/nuke
Writing /Test/renders/test.001.jpg took 0.00 seconds
Total render time: 0.00 seconds
[23:17.49] ERROR: Write1: Can't write, no such directory
## Write1: Can't write, no such directory

if I create a path that does not exist I get the expected errors and the path shown on the "Writing...." line is as expected. eg.
If I change pathsmap to 
 "pathsmap":[   ["/foo/bar/X/","X:/"]  ]
I get 

> Writing /foo/bar/Test/renders/test.001.jpg took 0.00 seconds
> I created a symlink path that does not exist anywhere else except on the rendernode and changed pathsmap to match but I get the same issue
> eg "pathsmap":[   ["/validSymlink/X/","X:/"]  ]
> get 
> Writing /Test/renders/test.001.jpg took 0.00 seconds

It appears that if the new path exists it is stripped from the path, rather than replaced.

I am at a loss

**Comment by tobkum** [comment]
Sorry, to dig this up, but same here, I have a Windows server and Linux clients. Works only if I add "newpath = newpath.replace('\\', '/')" on line 218 to cgrupathmap.py on the Windows machine.

**Comment by timurhai** [comment]
You should use unix paths as server and windows as client.
This is bad pathsmap: [["/array/X/","X:/"]]
This is good: [["X:/","/array/X/"]]

**Comment by tobkum** [comment]
Did so, in my case [["D:/","/mnt/erik/"]]

The problem is that the client is searching for the incorrect formatted path, e.g. /mnt/erik/Projects/client\project.blend (notice the last \ ), which does not exist. So the \ has to be replaced with a / 
With the aforementioned addition to cgrupathmap.py, it works.
