### ISSUE TITLE
Working directory doesn't exist

### ISSUE THREAD

**Issue by zabander** [CGRU/cgru#120]
Hi!, I'm just installing the system:
My server machine is one I also use as workstation.
The CGRU folder is in ; C:/CGRU

For my render node is the same:
C:/ CGRU
Both in windows.
My nuke files have network paths for all the files and material example:
//JUAN-PC/Files/Nuke/nuke.nk

When I send a render, the render node sends this messaje:

Started PID=4512: [nuke:1000] juan: Curves_V06NetTestv02.nk-COCATEST[Write8][fra
me 1-5]
Finished PID=4512: Exit Code=1 Status=1
WARNING: Working directory does not exist:
C:\Users\Juan

What can I do?, or where is my mistake?

Thank you!

**Comment by timurhai** [comment]
Hi.
Is there "C:\Users\Juan" folder a machine with that output?

**Comment by zabander** [comment]
Yes, that's the machine that is being used as workstation, but the files and resources are not in C:\Users\Juan. I don't know what is looking for in that folder.

 The nuke render output (write note) is //JUAN-PC/Files/renderoutput/job02

**Comment by zabander** [comment]
The problem is the working directory in nuke, it always puts C:/users/Juan, how can I change that, and what should I put?

**Comment by timurhai** [comment]
It is just a warning. You can skip it.

On a  job creation afanasy stores current process working folder. Then this folder goes with each task to afrender. Before a task start, afrender checks this folder on existence. If it is exists afrender starts task process in this folder, if not - just displays that warning.
If your afrender is launched under other user, it can has no access to C:/users/Juan.

If you want to change Nuke working folder (or any other) you can go to that folder in a console and launch nuke command from there.

btw
We are talking about process working directory http://en.wikipedia.org/wiki/Working_directory.
Do not mess it with Nuke (or other CG soft) "project directory".
Such soft as Nuke using relative paths relative to its "project directory" (if it is set).

**Comment by zabander** [comment]
Thanks now it's working perfectly, I just ignored the error, reinstalled the software of the slave machine ( probably the error came from here) and it worked perfeclty.
