### ISSUE TITLE
houdini not finding afanasy

### ISSUE THREAD

**Issue by gunk0001** [CGRU/cgru#121]
hello, i have an issue regarding houdini' integration of afanasy.
its not reading the python modules as well as the otl when i ran the example.

im using houdinifx 14.0.201.13, and i setup the executable in keeper to houdinifx.exe 
i have it in C:/cg-windows
ive also tried the manual global environment setting but still its not working for me in houdini.
in my nuke install it seems to be flawless.

here are the actual steps i took:
1.extract to C:/
2.run start.cmd
3.set server to 127.0.0.1(or the default)
4.run afcmd.cmd
5.run render.cmd
6.set houdini to houdinifx.exe
7.run houdini example
8.afanasy ROP complains incomplete asset def
9.running submit give the ff error:
"no module named afanasy".

im using one machine for the moment, im planning on getting some node after i get the hang of it.

thanks
-mohammed

**Comment by timurhai** [comment]
Hi.
Are you launching Houdini from keeper?
Can you check, whether Houdini 13 works?

**Comment by gunk0001** [comment]
yes Im lauching from keeper.
sorry i don't have houdini 13 for this machine.

**Comment by timurhai** [comment]
Can you launch in Houdini Python shell:
import os;print(os.getenv('HOUDINI_OTLSCAN_PATH'));print(os.getenv('PYTHONPATH'));
And copy results here.

**Comment by gunk0001** [comment]
here timurahai, thanks for you time

&;C:/Users/Peppy/Documents/qlib/otls/base;C:/Users/Peppy/Documents/qlib/otls/future;C:/Users/Peppy/Documents/qlib/otls/experimental

**Comment by timurhai** [comment]
So there is no path starting with your CGRU_LOCATION ("C:/cg-windows/...").
Also i see some custom otls folders.
You do something with HOUDINI_OTLSCAN_PATH environment variable?
How that folder "../qlib/.." appeared there? What is it?

**Comment by gunk0001** [comment]
i put it there its from a different repository:

here is my houdini.env

HCACHE = "D:/CACHE/Houdini Cache"
HOME = "C:/Users/Peppy/Documents"

#PYTHON
PYQT = "C:/Python27/Lib/site-packages"
LOCALPY = "$HOME/houdini14.0/python27"
PYTHONPATH = &;$LOCALPY;$PYQT

#QLIB STUFF
QLIB= "$HOME/qlib"
QOTL="$QLIB/otls"

HOUDINI_OTLSCAN_PATH = &;$QOTL/base;$QOTL/future;$QOTL/experimental
HOUDINI_GALLERY_PATH = &;$QLIB/gallery
HOUDINI_TOOLBAR_PATH = &;$QLIB/toolbar
HOUDINI_SCRIPT_PATH = &;$QLIB/scripts
HOUDINI_UI_ICON_PATH = &;$HOME/houdini14.0/mystuff_/icons


#PROJECT VARIABLES
#python -c $HOME/houdini14.0/mystuff_/customEnv.py

**Comment by timurhai** [comment]
So you override this environment variable. This is the reason it can't find afanasy ROP.
You should do something like this:
```bash
HOUDINI_OTLSCAN_PATH = &;$QOTL/base;$QOTL/future;$QOTL/experimental;$HOUDINI_OTLSCAN_PATH
```
To append previous value back.

**Comment by timurhai** [comment]
ps
CGRU Houdini setup uses this variable too:
https://github.com/CGRU/cgru/blob/master/software_setup/setup_houdini.sh#L44
And that is why afanasy ROP appears.

**Comment by gunk0001** [comment]
its working!! thanks alot

**Comment by timurhai** [comment]
ok)
