### ISSUE TITLE
render.cmd afrender.exe crash - Py-Initialize:unable to load the file system codec ImportError: No module named 'encodings'

### ISSUE THREAD

**Issue by Juang3d** [CGRU/cgru#124]
Hi there.

When I try to start the render with render.cmd I get this:

"Py-Initialize:unable to load the file system codec ImportError: No module named 'encodings'"

And then afrender.exe crash, some ideas?

I'm on windows 7 x64.

Cheers and thanks!

**Comment by timurhai** [comment]
Hi.
It seems that some other Python was initialized that afanasy was compiled with.
And it is strange, because if you start adrender with that script it should set all needed envirnment variables to use python that goes with a CGRU release.

**Comment by timurhai** [comment]
The problem with PYTHONHOME environment variable. Do you use it somehow in your pipeline ?

**Comment by Juang3d** [comment]
I have another Python installation in the system, I'll check this variable tomorrow and report results here.

Thanks!

Juan.

**Comment by Juang3d** [comment]
Hi there.

I removed all the environment variables from my user environment variables and now it's working :)

But I have another problem with Afanasy in max, I'll post in another thread

**Comment by ultra-sonic** [comment]
having the same issue here right now! which python did you link at compiletime on windows?

**Comment by ultra-sonic** [comment]
was python 32 or 64 bit?
