### ISSUE TITLE
Afanasy-CGRU 3dsmax error

### ISSUE THREAD

**Issue by Juang3d** [CGRU/cgru#125]
I'm getting this error when I try to send a job:

-- python "C:\cgru\afanasy\python\afjob.py" "X:\TEst_Cgru\test_vgru.max" 0 75 -by 1 -fpt 1 -seq 1 -name "test_vgru.max" -pause -tempscene -deletescene -node "Camara_Pepe" -image "W:\test_cgru_.jpg"
-- Error:
-- "python" no se reconoce como un comando interno o externo,
-- programa o archivo por lotes ejecutable.

I'll translate it:

- "phyton" is not recognised as an intern or extern command
--program or executable batch file

Some ideas?

Cheers!

**Comment by Juang3d** [comment]
Ok, solved this setting up manually the paths in windows but now I get this:

-- python "C:\cgru\afanasy\python\afjob.py" "X:\TEst_Cgru\test_vgru.max" 0 75 -by 1 -fpt 1 -seq 1 -name "test_vgru.max" -pause -tempscene -deletescene -node "Camara_Pepe" -image "W:\test_cgru_.jpg"
-- Error:
-- Traceback (most recent call last):
--   File "C:\cgru\afanasy\python\afjob.py", line 9, in <module>
--     import af
--   File "C:\cgru\afanasy\python\af.py", line 10, in <module>
--     import cgruconfig
-- ImportError: No module named 'cgruconfig'

Any ideas?

**Comment by predat** [comment]
Do you launch 3ds max from keeper ? 
It look like environnment variables are not set ! Look at PYTHONPATH !

Envoyé de mon iPhone

**Comment by timurhai** [comment]
Hi.
Look at
http://cgru.info/installation#config_environment

**Comment by Juang3d** [comment]
Thanks, all solved reviewing the environment config :)
