### ISSUE TITLE
max priority that a user can set is equal to default priority

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#127]
Hi Timur,

maybe there is a small bug in tag 2.0.4
In the past a user could set his own priorities up to 250. At the moment the max prio is equal to the "af_priority" in config.json and you need to be in godmode to change it above this value.

Is this the intended behaviour?

cheers
Oli

**Comment by timurhai** [comment]
Hi. Yes.
It was designed that only admin can raise priority.
It is not suitable?

**Comment by ultra-sonic** [comment]
there are two different priorities: 
1. the prio of a user in the users tab - this is fine if only GOD can raise it above 99
2. the prio of a job in the Jobs tab - this seems to be broken - in 1.7.0 a user could raise his own jobs prio to 250 - right now he can only raise it to a max. of what is defined in "af_priority" without being god - this makes no sense, since a user should be able to take care of his own jobs

was that change from 1.7.0 to 2.0.4 intentionally?

**Comment by timurhai** [comment]
O, you are right, it is a bug. I'll fix it!

**Comment by timurhai** [comment]
And it seems that within WebGUI user can do anything will any priority - and it is a bug too.

**Comment by timurhai** [comment]
done, 2.0.5 already released
