### ISSUE TITLE
[ass] loading   (too long)

### ISSUE THREAD

**Issue by Pixel3** [CGRU/cgru#128]
Hi,

I'm a new user and the configuration of the Afanasy renderfarm is nearing completion. The only thing that keeps me from using it is the following:

Cgru 2.0.4 on centos 6.6

Once the job is submitted, whether with afstarter or meArnoldRender  I realize it's abnormally long. Directly in Maya or even cmd kick it's very fast. Here's the log: 
...
00:00:00 9MB | [kick] command: kick -v 2 -nstdin -dw -dp -i /mnt/srv_farm/share/Test_render/scenes/simple_scene_arnold_4.0001.ass
00:00:00 9MB | loading plugins from . ...
00:00:00 9MB | no plugins loaded
00:00:00 10MB | [ass] loading /mnt/srv_farm/share/Test_render/scenes/simple_scene_arnold_4.0001.ass ...
00:03:06 10MB | loading plugins from /opt/solidangle/mtoa-1.1.2.2/2015/shaders ...
00:03:06 11MB | loaded 86 plugins from 1 lib(s) in 0:00.00
00:03:06 11MB | [ass] read 198884 bytes, 12 nodes in 3:06.83
00:03:06 11MB | 
00:03:06 11MB | 
00:03:06 11MB | there are 2 lights and 3 objects:
...
https://docs.google.com/document/d/1_6vpK8o63FZPM_T5VBfJSbxdttC8cU_wKRa0NO6DXgs/edit?usp=sharing

If i let it finish and then restart, the rendering is finished much quicker. Do you know what's wrong? Is there another log that would allow me to diagnose the problem further?

Thank you

**Comment by timurhai** [comment]
Hi.
Afanasy just runs commands that is all. To check command you can double click on a job, its tasks window will be raised, that double click on a task, you will receive a full task info. There will be a command that afanasy launches. You can copy paste it in a terminal and run to measure time.

**Comment by Pixel3** [comment]
My bad, I tested the kick command at the wrong place. You're right I get the same error in the terminal when I run it on the node. On the server, on the other hand, the kick work perfectly.

**Comment by Pixel3** [comment]
I had to tweak something in samba... well everything seems to work fine now.

I can't wait to explore Afanasy more in depth and thank you providing this great application. 

Spasibo!
