### ISSUE TITLE
frame_sequential preview approval - would introduce new "preview pending approval" state

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#130]
Hi Timur,

i am just looking into amazon cloud rendering using afanasy and everything is looking fine so far:
https://github.com/ultra-sonic/opencloudrender

What I would need to prevent rendering sequences that might be useless (because of artist fail) is an additional Job-State - let's call it "preview pending approval" or short PPA - it could be the same as the "PAUSED" state, with the only exception that a job in this state can still render the frames that are defined using the "frame_sequential" parameter.

Let me know what you think, but I would greatly appreciate this feature addition, since rendering faulty jobs in the cloud is much more expensive than on your local farm.

regards
Oliver

**Comment by timurhai** [comment]
Hi.
Yes, it will be a useful feature. And does not needs much coding.
It will be, but for now i can't say definitely when.

**Comment by timurhai** [comment]
Hi. Can you describe more detailed.
1. Job or block should have some attribute "ppa"?
2. When all non-sequential tasks rendered, job falls into "PPA" state, and stops to solve tasks (like paused), right? (this state can has some special color in a GUI to attract attention).
3. User set block(s) or job "ppa" attibute to false, job drops "PPA" state and continue solving, right?

 - i think it not a big deal to implement it and can be in the next version.

**Comment by timurhai** [comment]
Almost done like i described in previous message :)
Most because it was easy.
You can check it compiling from source code (or i can try to compile it for you platform).
But for now you can see and manipulate it only from WebGUI (and python and json api, of course).
AfWatch will support new things in later versions, because it has "rock" binary protocol.

**Comment by ultra-sonic** [comment]
thx timur...sorry that I didn't reply to your previous message...
Can i set this block(s) or job "ppa" to False at submission time already so
that we still have the old behaviour? Or will this be the new standard
behaviour?

**Comment by timurhai** [comment]
Hi.
This is job parameter ( i think that such block parameter not needed, as i think that we do not need such different behavior within the same job).
You can set it on job creation:
https://github.com/CGRU/cgru/blob/master/afanasy/python/af.py#L735
Later in web GUI you turn it ON or OFF any time (later in afwatch too).
And at least once you should turn it off after a job falls onto PPA state and you checked that everything is ok, and you want job to continue.

**Comment by ultra-sonic** [comment]
>
> https://github.com/CGRU/cgru/blob/master/afanasy/python/af.py#L735
>
This looks like it is True by default - does this mean that every job I
submit without explicitly setting it will wait for Approval? I would
suggest setting it to False to maintain the current behaviour by default
and only turn it on if a user really wants it!

cheers
Oli

**Comment by timurhai** [comment]
If you are not going to run this function, there will be no "ppa" parameter at all, null or false - no matter.

**Comment by ultra-sonic** [comment]
perfect!

**Comment by ultra-sonic** [comment]
can I pull now, or are you still working on it?

**Comment by timurhai** [comment]
Yes you can.

**Comment by timurhai** [comment]
Already done afwatch support (I forgot that all PPA theme is done by bit masks that already are transferring in an existing protocol, so no protocol changes needed).

So waiting you test to close this issue.

**Comment by ultra-sonic** [comment]
AFWATCH support is awesome!!!! Will test tommorrow morning!

**Comment by ultra-sonic** [comment]
Feature basically works! Thanks a lot man!
What I noticed: When changing the host_exclude_mask the job loses the PPA
state. Can you please take a look at this?

thx in advance
Oli

**Comment by ultra-sonic** [comment]
ah...I might just have found a bug:
i have a houdini job consisiting of two blocks:
*ifd-generate* and *mantrarender*
the job falls to PPA as soon as the *ifd generation is done* and it does
not start the mantrarender-block...

I'm afraid that means PPA state per block...which I guess you didn't want
to do in the first place. Or may there be another solution?

cheers
Oliver

**Comment by timurhai** [comment]
Ops, i forgot some "if" in the code, so any change will drop paa to the default value.
Fixed.

**Comment by timurhai** [comment]
mantrarender is the first block with tasks depend mask?
can you describe job block more detailed

**Comment by ultra-sonic** [comment]
wait ... i need to double check

**Comment by ultra-sonic** [comment]
forget the problem about *ifd-generate* and *mantrarender*
it seems to be working, but for some reason some of our jobs didn't start
the mantrarender....i'll have to investigate

**Comment by ultra-sonic** [comment]
just one more question about JOB APPROVAL in general:
Is there a way to add a final approval state which set a job from *DON*e to
*APP*roved? I would like to be able to run scripts on jobs that have final
approval from the production or even from the artist.

Any idea how this could be possible? we could also start a new issue...

**Comment by timurhai** [comment]
Hi. You can store any custom things in a "custom_data".
