### ISSUE TITLE
Error: Parser Bad result. Stopping Task

### ISSUE THREAD

**Issue by tobimai** [CGRU/cgru#131]
Everytime I send a file I saved, the server outputs this. When the project is new created and I don't save it it works. Please help me.

![parserbadresult](https://cloud.githubusercontent.com/assets/11044834/7901832/0e64610a-079d-11e5-839e-f5ea3b9be9a1.PNG)

The red line is where I send the Job

I hope somenone will be able to help me.

**Comment by predat** [comment]
How do you send the job ? Are you using the blender addon ? In watch or in the browser can you provide job info and log ?

**Comment by tobimai** [comment]
I used the Blender addon, but i installed it manually because with keeper Blender wouldn't start. In the watcher it shows a blinking star at the job. I can provide more detailed informarion as soon as i get home.

**Comment by predat** [comment]
What platform are you using ? What version of cgru (2.0.4 or git master) ?

**Comment by tobimai** [comment]
I'm using windows 7 64bit SP1 and cgru version 2.0.4

**Comment by timurhai** [comment]
Hi. You should always show task "Log" and task "Output" on any error.
