### ISSUE TITLE
Issues about Afanasy on cgru windows 2.0.4 and sending job

### ISSUE THREAD

**Issue by sephyr35** [CGRU/cgru#132]
Hi all !

I got some issues about the addon for blender.  I was watching some tutorials but i havent got the same results : i launch blender from the CGRU keeper, fine, i see the tab "afanasy" in render parameters but i can't choose the render engine "RENDER_Afanasy" in blender, as shown in tutorials.
is it normal ?

Over it, after submit a job with a afanasy example blender scene file, the job doesnt want to render in the WebGUI.
(My client renders are all shown in the list in the Renders tab)
it tells me some errors like below:

![capture_webgui](https://cloud.githubusercontent.com/assets/12729251/7959823/7cfa07ee-09fc-11e5-9ecc-32353c7d55a7.PNG)

Thanks !

**Comment by timurhai** [comment]
You should send task Log and Output on any error.
Tutorials are old, now there is no need to set render engine in Afanasy, and Afanasy itself is not a render engine too.

**Comment by sephyr35** [comment]
Thanks for the fast answer ! 

Ok, here's all the tasks log form the post_commands
I don't know what's happend, watching this:

---------------------------------------------------------------------------------------------------------------------------

Wed 03 Jun 14:57.30 : #0: SESSION #1: Starting on "node-pc": 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.32 : #0: Finished error.: 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.32 : Error task output:
=======================================================
Error: file(s) to delete not found:
C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend
Exit status = 1

=======================================================

Wed 03 Jun 14:57.32 : #0: Automatically retrying error task1 of 9.: 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.32 : #0: SESSION #2: Starting on "node-pc1": 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.34 : #0: Finished error.: 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.34 : Error task output:
=======================================================
Error: file(s) to delete not found:
C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend
Exit status = 1

=======================================================

Wed 03 Jun 14:57.34 : #0: Automatically retrying error task2 of 9.: 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.34 : #0: SESSION #3: Starting on "node-pc": 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.36 : #0: Finished error.: 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.36 : Error task output:
=======================================================
Error: file(s) to delete not found:
C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend
Exit status = 1

=======================================================

Wed 03 Jun 14:57.36 : #0: node-pc - AVOIDING HOST !: 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.36 : #0: Automatically retrying error task3 of 9.: 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.36 : #0: SESSION #4: Starting on "node-pc": 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.38 : #0: Finished error.: 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.38 : Error task output:
=======================================================
Error: file(s) to delete not found:
C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend
Exit status = 1

=======================================================

Wed 03 Jun 14:57.38 : #0: node-pc - AVOIDING HOST !: 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.38 : #0: Automatically retrying error task4 of 9.: 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.38 : #0: SESSION #5: Starting on "node-pc1": 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.40 : #0: Finished error.: 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.40 : Error task output:
=======================================================
Error: file(s) to delete not found:
C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend
Exit status = 1

=======================================================

Wed 03 Jun 14:57.40 : #0: node-pc1 - AVOIDING HOST !: 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.40 : #0: Automatically retrying error task5 of 9.: 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.40 : #0: SESSION #6: Starting on "node-pc1": 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.42 : #0: Finished error.: 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.42 : Error task output:
=======================================================
Error: file(s) to delete not found:
C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend
Exit status = 1

=======================================================

Wed 03 Jun 14:57.42 : #0: node-pc1 - AVOIDING HOST !: 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

Wed 03 Jun 14:57.42 : #0: Automatically retrying error task6 of 9.: 4d: "test-export_afanasy":
deletefiles "C:\Users\4D\Desktop\cgru-windows\examples\blender\scene.20150603145707.blend"

**Comment by timurhai** [comment]
We should see log and output from that error blender task, from that error blender job.

**Comment by sephyr35** [comment]
Hum, i'm not sure what you're talking about, but i've found a task log from the Blender job in the frame(that didnt render). is that what you need ? if not, where can i find log and output from the blender task ?


Wed 03 Jun 15:37.10 : SESSION #1: Starting on "node-pc"

Wed 03 Jun 15:37.12 : Finished error.

Wed 03 Jun 15:37.12 : Automatically retrying error task1 of 3.

Wed 03 Jun 15:37.12 : SESSION #2: Starting on "node-pc"

Wed 03 Jun 15:37.14 : Finished error.

Wed 03 Jun 15:37.14 : Automatically retrying error task2 of 3.

Wed 03 Jun 15:37.14 : SESSION #3: Starting on "node-pc"

Wed 03 Jun 15:37.16 : Finished error.

Wed 03 Jun 15:37.16 : node-pc - AVOIDING HOST !

Wed 03 Jun 15:37.16 : Automatically retrying error task3 of 3.

**Comment by timurhai** [comment]
this is the log
You can get output by RMB on a task in WebGUI.

**Comment by sephyr35** [comment]
Output:
COMPUTERNAME=NODE-PC
Le chemin d'accès spécifié est introuvable. 

Meaning that the file path is missing.

**Comment by timurhai** [comment]
It is all the output?

**Comment by sephyr35** [comment]
Yes. Even if i launch a render with all data on the same location (no network using). The task don't launch at all, but we don't have "Red" error. the error : 

{
  "error": "Task is not started.\nCheck task log.\nIf there is 'update timeout' check firewall.\nClient should listen a port and server should be able to connect to it."
}

**Comment by timurhai** [comment]
1. "update timeout" - most probably because afserver can't connect afrender. (afrender may can, but this connection is bidirectional). Anyway it is a very strange for a situation when and server and client are on the same machine. See afserver a afrender processes logs in this case.

2. "Le chemin d'accès spécifié est introuvable." is a common cmd.exe error. You can google it.
It usually happens when there is some mess with environment variables. Most common reason is spaces or national characters. Try to clean windows environment (may be on some test machine).
