### ISSUE TITLE
where do i set "Nimby Free Idle Time"

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#133]
where do i set "Nimby Free Idle Time" in config.json ?

**Comment by timurhai** [comment]
it is in farm.json, as can be needed to be different for various machines (workstations and renderers)
http://cgru.info/afanasy/server#farm_setup

**Comment by ultra-sonic** [comment]
ah...farm.json makes sense ;) thx!

**Comment by ultra-sonic** [comment]
the docs say: *If this value is not set or less than 1, machines will never
set to free automatically.*
but it doesn't work. if I set the value to 0 or remove the key itself it
still defaults to some value. I had to set it to an extremely high value
now.

**Comment by timurhai** [comment]
Fixed.
( will be in the next release, or build from sources )

**Comment by ultra-sonic** [comment]
>
> Fixed.
>
Thx man!

> ( will be in the next release, or build from sources )
>
I always build from source - except the few occasions where i used afanasy
on windows ;)

**Comment by timurhai** [comment]
Now to disable feature you need to set value to zero. if you delete property, or set negative value, farm host settings will be not updated.
It will be updated in documentation too.

**Comment by ultra-sonic** [comment]
Perfect! Thx for this fix!
