### ISSUE TITLE
Dead cycles after arnold ( kick ) rendering

### ISSUE THREAD

**Issue by MaroZz** [CGRU/cgru#134]
osx 10.9 using 2.0.3 osx pkg

after kick competed task (render exr, save it to disk, kick shutdown) , there is something, called by afrender as @deadcycles@ and afserver at this time, show already rendered frame as 50 %

maybe screenshots say more... (grade.local, frame 7)
![screen shot 2015-06-17 at 8 11 14 pm](https://cloud.githubusercontent.com/assets/157523/8232857/6a388c4e-15db-11e5-9344-ec1c93178c14.png)
![screen shot 2015-06-17 at 8 12 07 pm](https://cloud.githubusercontent.com/assets/157523/8232858/6a3b1202-15db-11e5-8c84-4c30f9eab5d2.png)

**Comment by timurhai** [comment]
Hi.
Hm, may this is some bug. But to fix it, we should catch it.
All hosts (and afserver) uses the same OS (osx 10.9)?
Only arnold causes this bug?
May be this bug can(or always) happen only on some machine(s)?

**Comment by MaroZz** [comment]
thank u for ur fast answer, but..
sorry, false alarm

i finally build 2.0.4 commit from source for osx, and this problem disappeared...
