### ISSUE TITLE
thumbnails and Frames Per Task

### ISSUE THREAD

**Issue by ramellij** [CGRU/cgru#135]
Hi timur, 

On Afansy 2.0.5 for Windows I found some bugs about thumbnail generation and the Frames Per Task option (or task size): 

1. When I try to render .vrscene files from the meVrayRender Maya plugin : 
Frames Per Task doesn't work : I have to keep 1 to render all frames because if FPT is > to 1 it renders just the first one of the task, like if the "By" option (step between frames) was used instead. 
	
2. When I use the same method (.vrscene) from afstarter :
I try to create thumbnails by setting the Output Images (to get the "File" option on tasks) but it doesn't work. My afstarter setup :
"python" "C:\cgru-windows\afanasy\python\afjob.py" "C:\Users\ASUS\Desktop\TEST\vrscenes\test_@####@.vrscene" 1 100 -by 1 -fpt 1 -seq 1 -output "C:\Users\ASUS\Desktop\TEST\images\test_@####@.exr" -os any -pwd "C:\Users\ASUS\Desktop\TEST\vrscenes" -name "test_@####@.vrscene"
		
It renders files named like this : test_0001.0001.exr, test_0002.0002.exr, test_0003.0003.exr ...etc
Thumbnails aren't created (it works when it's launched from maya) and so I can't preview my renders from the tasks tab (I got the same problem with Cinema4D file, from python plugin and afstarter). And same problem with the Frame Per Task option. 

3. When I use the Afanasy Maya Batch(plugin CGRU) to render a .mb file : 
The FPT works, but no thumbnails are generated. And I have this strange output for all my tasks : "Files: C:/Users/ASUS/Desktop/TEST/images/test.iff.0001".

4. trying the same from aftarter (setting the "Output Images" to create thumbnails and so have access to the preview command). From afstarter I have :
"python" "C:\cgru-windows\afanasy\python\afjob.py" "C:\Users\ASUS\Desktop\TEST\scenes\test.mb" 1 100 -by 1 -fpt 10 -seq 1 -output "C:\Users\ASUS\Desktop\TEST\images\test_@####@.exr" -os any -pwd "C:\Users\ASUS\Desktop\TEST\scenes" -name "test.mb"

There are no "Files" option in my tasks and so no thumbnails. 

Thanks for your help
JR

**Comment by timurhai** [comment]
Hi.
I am not very familiar with all cg software and do not have Maya and VRay by hand.
May be submission script does not work right.
You can double-click task to receive its command and run this command just in a console. If this command does not works right, you can fix it to produce needed results. And i can help you (guide or may be do it myself) to fix submission script to generate right command.

Thumbnails: The best way to parse rendered images and generate thumbnails from parsed files, because it can be not easy for submission script to solve the result file name. Some times, render engines can add some suffix to images (for example: _occ, _diff, _left, _right). But on render stage task process can output process image correctly.

If you familiar with Python you can fix afjob yourself
https://github.com/CGRU/cgru/blob/master/afanasy/python/afjob.py#L741
Because, as i told before, i do not always has VRay by hand. I also will can guide you.

**Comment by timurhai** [comment]
So if you know how to make render engine to output result images - the will be no problems with thumbnails, and there will no need for submission script (artist) to solve (specify) it.

**Comment by ramellij** [comment]
The only way I found to make thumbnails is using meVRayRender.py script from the CGRU plugin for Maya. But the problem is it doen't setup the right Working Directory path to my tasks. It changes it to "C:\Users\WORKSTATION" and so my clients render out on themselve instead of the right shared folder. 

My task output :

frame 1
vray[vray]:1000 frames(1,1,1):
Command:vray -display=0 -showProgress=1 -verboseLevel=3 -progressIncrement=1 -progressUseCR=0 -imgFile=R:/2015_WIND_TREE_II/01_MAYA/images/test_water.exr  -sceneFile= R:/2015_WIND_TREE_II/01_MAYA/vrscenes/test_water_0001.vrscene
Working Directory:C:\Users\WORKSTATION
Files:R:/2015_WIND_TREE_II/01_MAYA/images/test_water.0001.exr

My problem is I don't know how to reproduce all those commands in afstarter so I could correct the right Working directory to make everything work as it should.

**Comment by ramellij** [comment]
...and when I use afsarter it outputs that : 

frame 1
vray[vray]:1000 frames(1,1,1):
Command:vray -sceneFile="R:\2015_WIND_TREE_II\01_MAYA\vrscenes\test_water_0001.vrscene" -imgFile="R:\2015_WIND_TREE_II\01_MAYA\images\test_water_0001.exr" -display=0 -autoClose=1 -verboseLevel=4 -showProgress=2
Working Directory:R:\2015_WIND_TREE_II\01_MAYA
Files:R:\2015_WIND_TREE_II\01_MAYA\images\test_water_0001.exr

it renders but no thumbnails.

**Comment by timurhai** [comment]
Hi.
1. Try to fix maya submission script to set the correct working directory here
https://github.com/CGRU/cgru/blob/master/plugins/maya/afanasy/afanasyRenderJob.py#L160
set maya project path to each block with
http://cgru.info/afanasy/job#block_working_directory

2. AfStarter:
imgFile="R:\2015_WIND_TREE_II\01_MAYA\images\test_water_0001.exr"
and
Files:R:\2015_WIND_TREE_II\01_MAYA\images\test_water_0001.exr
are the same, try to look at task process and afrender process output, may be some error is there
Note that AfStarter has a Preview parameter in the Advanced tab. It does not try to affect render images and used for preview/thumbnails only.
( Output images parameter is used both and for output images override and for preview )

ps
I can't fix/check, as i have no maya/vray for now.
