### ISSUE TITLE
Blender Addon : Preview Pending Approval

### ISSUE THREAD

**Issue by g-LuL** [CGRU/cgru#136]
Hi !
The new cgru 2.0.5 comes with a new blender addon design.
It integrates new features of cgru, especially the "sequential" addon.
I'd find it more useful if the ppa attribute (Preview Pending Approval) is included in the addon.
I've wrote a little tweak for the Blender Addon... I will pull a request for it (I don't know how request pulling works now but i'll try ;) )

**Comment by timurhai** [comment]
Done https://github.com/CGRU/cgru/pull/137
