### ISSUE TITLE
Blender parser error

### ISSUE THREAD

**Issue by g-LuL** [CGRU/cgru#138]
Hi !

On cgru 2.0.5 on windows 7 64, I think there's a mistake in the blender parser.
in parsers/blender.py (40) : self.appendFile(line.strip())
in parsers/parser.py (43): def appendFile(self, i_file, i_onthefly)
When a render is working, an error appears in the console of the render machine.
Error parsing output:
Traceback (most recent call last):
  File "S:\cgru\windows\cgru\afanasy\python\parsers\parser.py", line 122, in par
se
    result = self.do(data, mode)
  File "S:\cgru\windows\cgru\afanasy\python\parsers\blender_cycles.py", line 38,
 in do
    blender.blender.do(self, data, mode)
  File "S:\cgru\windows\cgru\afanasy\python\parsers\blender.py", line 40, in do
    self.appendFile(line.strip())
TypeError: appendFile() missing 1 required positional argument: 'i_onthefly'

As i do not know all the parser process at all, i can't pull a request...

**Comment by timurhai** [comment]
Hi!
It is my mistake. I added a new parameter to function, but i have not added its default value,
so it fails:
https://github.com/CGRU/cgru/blob/master/afanasy/python/parsers/blender.py#L40

Now i fixed
https://github.com/CGRU/cgru/blob/master/afanasy/python/parsers/parser.py#L43
and it should works

**Comment by timurhai** [comment]
https://github.com/CGRU/cgru/commit/b3f79b9e0c67486574c4273d8e1ef29e7f6878a2
