### ISSUE TITLE
Render node, group or pool

### ISSUE THREAD

**Issue by penthoy** [CGRU/cgru#143]
Everything works like charm! 
Except we can't assign certain shots to designate stronger or weaker groups of nodes, if this is possible would be perfect!

**Comment by ultra-sonic** [comment]
you can group with the "host mask" and you can distinguish between weak/powerful using the "capacity" - hope that helps...I never had issues dealing with this kind of fine-grained job assignment and I would say Afanasy is the most flexible render-manager in that regard. But you need to get your around all your possibilities and this can take a while ;)

**Comment by penthoy** [comment]
Thank you very much for the reply ultra-sonic, I've tried it and it works great for our purpose
