### ISSUE TITLE
/tmp/test_C.tiff : No such file or directory error

### ISSUE THREAD

**Issue by penthoy** [CGRU/cgru#144]
We have encountered this error many times(with houdini 14 scene), and at first I thought it was problem with the rendered scene, almost 90% of the scene will give this error at the end:

Error: Failed to create file "/tmp/test_C.tiff : No such file or directory".

Usually the render goes to 100% and then the image rendered, but then it'll restart the render again and again after throwing this error. but eventually it'll be done after around the third or fourth try, so if there's no wrangler manually stop the frame at 100% it'll run average 3 times before it became done...

Also not all frames throw this error, some frames don't and its completely random, so I was suspecting it had something to do with the process of thumbnail creation at the end of the render. since a thumnail is only created every few frames. could it be the cache file of this thumbnail? but I could be wrong. I have searched this keyword anywhere, from our scenes or the sources of cgru... I have no idea where this came from...

anyone can shred some light on this issue will be greatly appreciated~.

**Comment by penthoy** [comment]
I was suspecting it had something to do with the process of thumbnail creation. at the end of the render.

**Comment by timurhai** [comment]
Hi.
Afanasy operates only with /var/tmp/afanasy folder on linux (by default).
This is probably a houdini error, i think.

Try to launch task command simple in the console (w\o afanasy).
To get task command you can double click a job, then double click a task.

btw, what OS?

**Comment by penthoy** [comment]
Thanks for the reply timurhai ~ the problem is solved, the render nodes are windows 7, I also believed it to be a houdini problem, I just created a tmp folder under C:, and strangely enough it did write out a test_c.tiff that we're unaware of... very strange, but at least it can now render out nice. 

Thanks~.
