### ISSUE TITLE
8396: Fatal error: Segmentation fault

### ISSUE THREAD

**Issue by penthoy** [CGRU/cgru#145]
occasionally some frames in the farm will stuck at 100%, the frame is good, if I manually press skp, it'll be fine, but if no one manually do that, it'll stuck at 100% forever. 

in the log it gives this error:
Memory: 44.93 GB of 45.53 GB arena size. VM Size: 45.74 GB

8396: Fatal error: Segmentation fault
-- TRACEBACK BEGIN --
Traceback from mantra 14.0.291 (Compiled on windows-x86_64-cl17):
+0xec372925 [UT_StackTrace::doTracebackIntoBuffer]
+0xec286a43 [UT_StackTrace::`default constructor closure']
+0xec286c28 [UT_StackTrace::`default constructor closure']
+0xec370c56 [UT_Signal::processSignal]
+0xf8bef5c5 [XcptFilter]
+0x3f2a353e 
+0xf8bee98b [_C_specific_handler]
+0x77039d0d [RtlDecodePointer]
+0x770291af [RtlUnwindEx]
+0x77061278 [KiUserExceptionDispatcher]
+0xeaa34487 [VEX_Instance::clearLocalWordData]
+0xeaa33c33 [VEX_Instance::~VEX_Instance]
+0xeaa03e38 [VEX_Code::clearInstances]
+0xeaa03594 [VEX_Code::clearCode]
+0xeaa033bf [VEX_Code::~VEX_Code]
+0xeaa030b7 [VEX_ChannelCache::~VEX_ChannelCache]
+0xeaa05550 [VEX_CodeList::clear]
+0xea9fcb2b [VEX_Assemble::~VEX_Assemble]
+0xeaa14807 [VEX_Context::clearFunctions]
+0xeaa148da [VEX_Context::clear]
+0xeaa19ee8 [VEX_ContextManager::clearContext]
+0xe26c343e [VRAY_Scene::shutdown]
+0xf45644a5 [CMD_Manager::runCommand]
+0xf455966d [CMD_Manager::internalExecute]
+0xf4562d2e [CMD_Manager::processInput]
+0xf4563466 [CMD_Manager::internalSendInput]
+0xf4563094 [CMD_Manager::sendInputNoLock]
+0xe26cd920 [VRAY_Scene::load]        <--btw we don't use vray..
+0x3f2a1698 
+0x3f2a2eef 
+0x76f0652d [BaseThreadInitThunk]
+0x7703c521 [RtlUserThreadStart]
-- TRACEBACK END --

all render nodes are on windows 7, the afserver is on centOS7. version 2.05, render nodes are at 2.04. rendering houdini 14.
Any help would be appreciated. Thank~

**Comment by timurhai** [comment]
Hi.
This is a vray output and not an afanasy (afrender) problem. Better to ask vray help for this.
Stuck can cause some window raise with an error. Such windows usually wait for some button to be pressed by user (gui mode).


1. Afrender can close windows itself
http://cgru.info/afanasy/render#windows_must_die

2. Afrender parser can consider that task is done, even when its process is not finished
http://cgru.info/afanasy/render#finishedsuccess

ps
better to solve child process (vray) problem

**Comment by ultra-sonic** [comment]
actually it's not VRAY, but mantra...side effects just named one of their
libraries VRAY years ago ;) anyway it is not really an afanasy issue even
though it should receive a non-zero error-code.
@penthoy: find mantra.py inside afanasy/pthon/parsers and add *"**Fatal
error: Segmentation fault"* to the errors dictionary. This should tell the
afanasy parser to treat this as a failed job - I know that the output is
good, but you definitely have a mantra issue here that you should look into!

**Comment by penthoy** [comment]
Thank you guys for the answer!

@ultra-sonic: i'll definitely look in that direction, and come back for an update~ :)
