### ISSUE TITLE
Launching render.cmd with psExec

### ISSUE THREAD

**Issue by ramellij** [CGRU/cgru#148]
Hello Timur, 

I'm would like to launch my render nodes from my Workstation using paExec. 
The command is :
paexec \\CREATURE-RN-01 C:\cgru-windows\start\AFANASY\render.cmd

afrender is launched but doesn't render because he can't recognize the path of my network drive, strange... :/
When I launch it directly from the remote computer (without paExec) there is no problem. Do you know what the problem could be ? Maybe I don't call the good file or I need to add a specific comand...

Thanks for your help
JR

If you know a better way to do it just tell me ;)

**Comment by ramellij** [comment]
well in fact it works only when I use the full network path and not my network drive
\\Workstation-pc\path...\file instead of R:\path...\file

**Comment by timurhai** [comment]
Hi.
I am not a windows admin.
But check by what user psexec runs program.
Does that user has all needed paths? (drive letters)
You can specify exact user for psexec to run from.

**Comment by ramellij** [comment]
yes adding the user administrator doesn't change anything. It's strange.
