### ISSUE TITLE
AFERROR: accept: Too many open files

### ISSUE THREAD

**Issue by penthoy** [CGRU/cgru#149]
I've encountered the following error:

#############################
AFERROR: name_afnet.cpp writedata:: Broken pipe

AFERROR: af::msgwrite: Error writing message.

AFERROR: writeMessage: can't send message to client.
Address = 192.168.2.44 Port = 59010
THTTPGET: Length=24368, type=52
AFERROR: accept: Too many open files

AFERROR: The per-process limit of open file descriptors has been reached.
AFERROR: accept: Too many open files
#############################

Other than the background and some buttons nothing shows up in the web interface,
I'm using version 2.06 on centOS 7.
I'm not sure where to begin to fix this.
Any help is appreciated!

**Comment by timurhai** [comment]
Hi.
This is a bad result of some previous error.
"accept: Too many open files" - any process on any os has files descriptors limit.
But it should not happen in the normal situation.

How many clients you have?
http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/
May be you really need to increase this limit.

**Comment by penthoy** [comment]
Thanks for the reply timurhai! 

if you mean render clients I have average 45 running at the same time.

This happend before, when the server was at v2.05 and I had to migrate to a new ip and updated to v2.06 in order to fix it(although I wasn't sure what really fixed this last time, since it was fixed start fresh)

But this time it was ok after a server restart, I was freaking out a little bit, since a lot of jobs are in queue :x

**Comment by penthoy** [comment]
This same issue have happened continuously, and became more frequent as of late, although I can restart the server sometimes by pressing ctrl+c, and then use '/opt/cgru/start/AFANASY/_afserver.sh' to restart the server, but whenever I do this, all the previously modified tasks are gone(as if all the previously cleaned up or deleted tasks are back...) I wonder how was the modified record stored or if there's anyway for me to force the server to save current record, would be great.

Also the last time I restart, it didn't work, until I saw an an error that indicates coming from an ip(sorry didn't took note on that error), I go inside remote into ip, which was a render node, and saw some popup error on the render node, after I pressed close on that, and restart the server it worked again... so in summary, this error was caused by some render node that had error and got frozen?

I really wished I know deeper about how afanasy works, since we're using it for for some pretty mission critical works now, Thanks for your help in advanced.

**Comment by penthoy** [comment]
I have changed the file descriptor limit, but it require a restart, right now I'm really afraid to restart because I'm afraid all the task might be gone once I restart it. would be nice to know a way to force save the current status...

**Comment by timurhai** [comment]
Hi.
read this
https://github.com/CGRU/cgru/issues/142

also try this:

    netstat -nat | grep 51000

and read this:
http://www.fromdual.com/huge-amount-of-time-wait-connections

Then give me an answer.

**Comment by penthoy** [comment]
Hi, I have tried to increase the max descriptor limit, and have just restarted.
I read the #142 but it doesn't seemed like we have the same error, I don't recall seeing this 'no error' message, and i'm on windows 7 instead of windows 8.

I've tried both netstat -nat | grep 51000 and also netstat -nat 

I have tried the solutions sections in http://www.fromdual.com/huge-amount-of-time-wait-connections but i'm don't fully understand the article as I'm a noob in networking.

server just restarted. I don't think there should be any other application using port 51000 as in this server there is only afanasy.

**Comment by timurhai** [comment]
Hi.
Try

   netstat -nat | grep 51000 | wc -l

and

    ss -tan state time-wait | wc -l

and send results here.

**Comment by penthoy** [comment]
[root@localhost Desktop]# netstat -nat | grep 51000 | wc -l
2755
ss -tan state time-wait | wc -l
2774

**Comment by timurhai** [comment]
try also

lsof | grep afs | wc -l

**Comment by timurhai** [comment]
:) and this:

    netstat -nat | egrep ':51000.*:.*TIME_WAIT' | wc -l

I want to know whether the reason is TIME_WAIT socket state.

**Comment by penthoy** [comment]
[root@localhost Desktop]# lsof | grep afs | wc -l
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
8923

**Comment by timurhai** [comment]
Hi.
Can you count open file descriptors, sockets and TIME_WAIT sockets at the same time.
Launch 3 commands one by one, and print 3 numbers here.

    lsof | grep afs | wc -l

    netstat -nat | grep 51000 | wc -l

    netstat -nat | egrep ':51000.*:.*TIME_WAIT' | wc -l

We should find what that open descriptors do.
Better to try to run this when afserver "feels bad".
As far as i understand it commonly works fine, but sometimes hung.

**Comment by penthoy** [comment]
OK, I'll do this when server hung again~ thanks!

**Comment by timurhai** [comment]
Also do in any case, just you have time.

**Comment by penthoy** [comment]
sure~, just ran it, here is the result:

[root@localhost Desktop]# ss -tan state time-wait | wc -l
2774
[root@localhost Desktop]# lsof | grep afs | wc -l
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
8923
[root@localhost Desktop]# lsof -p [afserver process PID] | wc -l
lsof: illegal process ID: [afserver
lsof 4.87
 latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/
 latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ
 latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man
 usage: [-?abhKlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-f[gG]] [+|-e s]
 [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+m [m]] [+|-M] [-o [o]] [-p s]
[+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]
Use the ``-h'' option to get more help information.
0
[root@localhost Desktop]# netstat -nat | grep 51000 | wc -l
2599
[root@localhost Desktop]# netstat -nat | egrep ':51000.*:.*TIME_WAIT' | wc -l
2465

**Comment by penthoy** [comment]
farm just frozen right now here is the repeating output:

ERROR Sat 31 Oct 03:28.16: AfContainerIt::get(): node == NULL : id = 28
Sat 31 Oct 03:28.16: Monitor registered: coord@pc:-12[13] v'2.0.6' 192.168.2.72
ERROR Sat 31 Oct 03:28.16: AfContainerIt::get(): node == NULL : id = 28
Sat 31 Oct 03:28.16: Monitor registered: coord@pc:-13[14] v'2.0.6' 192.168.2.48
Sat 31 Oct 03:28.16: Monitor registered: coord@pc:-14[15] v'2.0.6' 192.168.2.42
Sat 31 Oct 03:28.16: Monitor registered: coord@pc:-16[16] v'2.0.6' 192.168.2.48
AFERROR: accept: Too many open files

AFERROR: The per-process limit of open file descriptors has been reached.
ERROR Sat 31 Oct 03:28.16: AfContainerIt::get(): node == NULL : id = 28
Sat 31 Oct 03:28.17: Monitor zombie: coord@pc:-17[18] v'2.0.6' 192.168.2.72
Sat 31 Oct 03:28.17: Monitor zombie: coord@pc:-34[35] v'2.0.6' 192.168.2.48
Sat 31 Oct 03:28.24: Monitor registered: coord@pc:-17[18] v'2.0.6' 192.168.2.77
Sat 31 Oct 03:28.24: Monitor registered: coord@pc:-18[19] v'2.0.6' 192.168.2.48
Sat 31 Oct 03:28.24: Monitor registered: coord@pc:-19[20] v'2.0.6' 192.168.2.48
Sat 31 Oct 03:28.24: Monitor registered: coord@pc:-20[21] v'2.0.6' 192.168.2.144
ERROR Sat 31 Oct 03:28.24: AfContainerIt::get(): node == NULL : id = 33
ERROR Sat 31 Oct 03:28.24: AfContainerIt::get(): node == NULL : id = 33
AFERROR: accept: Too many open files

AFERROR: The per-process limit of open file descriptors has been reached.
ERROR Sat 31 Oct 03:28.24: AfContainerIt::get(): node == NULL : id = 33
Sat 31 Oct 03:28.25: Monitor zombie: coord@pc:-4[5] v'2.0.6' 192.168.2.42

I'll run your commands next and paste the output

**Comment by penthoy** [comment]
[root@localhost Desktop]# lsof -p [afserver process PID] | wc -l
lsof: illegal process ID: [afserver
lsof 4.87
 latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/
 latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ
 latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man
 usage: [-?abhKlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-f[gG]] [+|-e s]
 [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+m [m]] [+|-M] [-o [o]] [-p s]
[+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]
Use the ``-h'' option to get more help information.
0
[root@localhost Desktop]# netstat -nat | grep 51000 | wc -l
99
[root@localhost Desktop]# netstat -nat | egrep ':51000.*:.*TIME_WAIT' | wc -l
71

**Comment by penthoy** [comment]
[root@localhost Desktop]# ss -tan state time-wait | wc -l
1972

forgot to run this... ran after the server restart, not sure it'll still be helpful.

**Comment by timurhai** [comment]
New server-client architecture where client does not listen any port, and so server does not connects clients manually, make such issues obsolete. But may be some new bugs will appear. Testing needed.
