### ISSUE TITLE
imagemagick die on un-cropped exr images

### ISSUE THREAD

**Issue by penthoy** [CGRU/cgru#150]
I found a very annoying problem with images after reformat in nuke while writing it out as exr without adding a crop node at the end, will result in crashing imagemagick(convert.exe) and in term disconnects afrender client.

strangely windows must die will not detect this... while manually clicking on close hundreds of times will work...

This problem have been causing constant disconnects with render clients, and have to click on close all day manually... although I've told artists try to use crop nodes whenever possible but its impossible to track all scenes to make sure all of them have crop node, if one scene have one of such node that exports uncrop exrs, it was enough to disconnect the whole farm.

so I was wondering if there's any good way to solve this? I have downloaded the latest imagemagick, and it seemed to have the same result.

This is the particular command that will cause the crash:

convert -identify "C:\uncrop.exr" -set colorspace RGB -thumbnail "100x100^" -gravity center -extent 100x100 -colorspace sRGB "C:\uncrop.exr.jpg"

Thanks in advanced.

**Comment by penthoy** [comment]
My mistake, instead of reformat, what I meant is adding a transform and move the image out of frame, and then output it as exr before adding a crop node under it.

**Comment by timurhai** [comment]
Yes, i know the problem
http://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=25324&sid=bada99e0c55b1c39efdde52816ffc68a

On linux there is just no thumbnails, as a task post command does not mean task error (at least by default). On windows use windows-must-die option to make afrender to close annoying dialogs.
http://cgru.info/afanasy/render#windows_must_die
https://github.com/CGRU/cgru/blob/master/afanasy/config_default.json#L54

**Comment by penthoy** [comment]
unfortunately windows_must_die doesn't seemed to work with this particular scenario,  the image magick windows was by default in Windows Must Die list? I also added convert.exe at the end but never saw it worked, although it works perfectly for nuke.exe... I have seen it happend many times, it closed a few hanged nuke.exe just fine, and then image magick came and it never able to close it...

**Comment by penthoy** [comment]
Is there a way to disable thumbnail creation? perhaps only for all nuke renders?

**Comment by penthoy** [comment]
Seems to work fine after I take out exr from "af_thumbnail_extensions" :) atleast no more client disconnects and errors, will disable thumbnail creation for now on exr images... will keep this thread open, I hope this problem can be fixed from image magic...
