### ISSUE TITLE
[FEATURE REQUEST] desktop notifications for errors

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#151]
Hi timur,

I'll just post this here in case you ever find the time to implement new features.

I think it would be awesome to have desktop notifications for errors. I could imagine this being done as system-tray notification as part of afwatch. 

So basically if a job of user JohnDoe has errors he get's notified immediately on the machine(s) where he is currently logged in.

What do you think?

**Comment by timurhai** [comment]
Hi.
Some time ago i need the same.
I used events to send emails on job error, and setup mail to notify it.

**Comment by ultra-sonic** [comment]
do you think we could extend those events to send messages/commands to
afwatch?

**Comment by timurhai** [comment]
May be more simple to extend Keeper that uses PyQt (PySide) if it can raise desktop notifications (or use some tray icon animation). More simple to send event to Keeper.

But if afwatch is launched, it already know about some error job, and we can raise some window (no events needed i this case).

I just want to say that you can already desktop notifications about emails.

But if afwatch will gave some checkbox option to raise an error message - it is enough simple and useful feature.

**Comment by timurhai** [comment]
Done in code. Now i am testing it ( on linux ).
You can test it too ( as far as i remember you have mac ).
I am not using any system desktop notification methods as they are platform-depend.
Just raising an always on top window with no borders in a top-left corner (i hope).

For now code is still compatible with 2.0.x versions.
When there will be written 2.1.0 it will be not.
https://github.com/CGRU/cgru/blob/master/version.txt
( it will not be very soon )

**Comment by predat** [comment]
Could not compile afwatch after 92211b5639ad252b2b065936d7a4d5da51cde295 on macosx with clang-600.0.57.
Error message is strange:
```bash
[ 62%] Building CXX object watch/CMakeFiles/afwatch.dir/opt/cgru.git/afanasy/src/watch/popup.cpp.o
In file included from /opt/cgru.git/afanasy/src/watch/popup.cpp:1:
In file included from /opt/cgru.git/afanasy/src/watch/popup.h:5:
In file included from /opt/cgru.git/afanasy/src/watch/watch.h:3:
In file included from /opt/cgru.git/afanasy/src/watch/../libafqt/name_afqt.h:3:
In file included from /opt/cgru.git/afanasy/src/watch/../libafqt/../libafanasy/name_af.h:28:
In file included from /opt/cgru.git/python/include/python3.4m/Python.h:65:
In file included from /opt/cgru.git/python/include/python3.4m/pytime.h:6:
/opt/cgru.git/python/include/python3.4m/object.h:435:23: error: expected member name or ';' after declaration specifiers
    PyType_Slot *slots;
    ~~~~~~~~~~~       ^
1 error generated.
make[2]: *** [watch/CMakeFiles/afwatch.dir/opt/cgru.git/afanasy/src/watch/popup.cpp.o] Error 1
make[1]: *** [watch/CMakeFiles/afwatch.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by timurhai** [comment]
Hm.
Try to clear the project. May be some mess that new files appeared that uses Qt signal-slots.
run ./clear.sh in afanasy/src/project.cmake or use a fresh repo clone.

**Comment by predat** [comment]
Already done: same result !

**Comment by timurhai** [comment]
Hm.
Try co compile each commit (if you have time), this way we can find needed commit.
Then you can comment changes of the commit, and we can find the problem.

**Comment by timurhai** [comment]
Windows shows the same error and it fixed now.
https://github.com/CGRU/cgru/commit/d10408c3df84e24719c48cfb80bfa8f084847d63

**Comment by predat** [comment]
I confirm, it fixed.

**Comment by ultra-sonic** [comment]
cannot test on osx until beginning of december...but will let you know as
soon as i did!

**Comment by ultra-sonic** [comment]
Hi Timur,
do I need to enable those notifications? I just updated to 2.0.8 but didn't
see any of them yet...

**Comment by timurhai** [comment]
Hi.
Yes, you should enable them in settings.
RMB menu on an empty space (border) -> "Notifications.." item.

**Comment by ultra-sonic** [comment]
just to follow up on this one....i never received a notification so far.
And I am pretty sure I enabled them ;) I'm on Centos 7 using MATE
Desktop...maybe that's the problem.

**Comment by ultra-sonic** [comment]
do i need keeper running or is it afwatch that opens those popups?

**Comment by timurhai** [comment]
afwatch only
also, there are sound notifications, does they work?
and try to check all notification types: added, done, error, may be just some type(s) not work

**Comment by ultra-sonic** [comment]
will do!

**Comment by predat** [comment]
I can confirm that sound notification is working on Macosx platform.
But notification window is placing over screen... I need to multiply by 3 the size in 'watch/popup.cpp':
```c++
setGeometry(QStyle::alignedRect(
    Qt::RightToLeft,
    Qt::AlignTop,
    size() * 3,
    qApp->desktop()->availableGeometry())
);
```
to have the windows into the screen.

**Comment by timurhai** [comment]
You can put this change for macosx in `#ifdef MACOSX` block and commit :)
( on linux and windows it works fine )

**Comment by predat** [comment]
i've push 78d31366d1c54beca33a117508e829ad0128325b.
It fix window notification placement for macosx.
I've test on linux and it does not change anything. But i can't test on Windows...

**Comment by timurhai** [comment]
Works fine on windows too!
