### ISSUE TITLE
job telemetry reports

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#152]
Hi Timur,

another feature request...in case you find the time.

Since we have "render-telemetry" already I would like to be able to check how much resources were used by a job over it's render-time as a graph. So this would basically be another log file that get's plotted as a graph containing useful information like CPU-usage,RAM,network-IO and so on. 

Not urgent, but I just needed to write it down somewhere ;)

cheers
Oli

**Comment by lithorus** [comment]
#400 seems similar

**Comment by timurhai** [comment]
Closed as an less discussed duplicate.
