### ISSUE TITLE
Houdini distributed simulations 

### ISSUE THREAD

**Issue by sergeneren** [CGRU/cgru#153]
Hi Timur,

It would be great if we could add distributed simulations to afanasy. I know HQueue exists but houdini tracker.py can track peers and jobs externally. And since new h15 uses distributed flip it would be awesome. 
Thanks ahead

**Comment by timurhai** [comment]
Hi.
If you can tell what commands should be launched on master and slaves, i can guide you (or anybody else) how to write such submission script.

Afanasy supports several clients per task. Also is has mechanism to change task command "on-the-fly" on a client side just before launch (slaves should know who is their master). So Afanasy architecture can distribute simulations.

ps
Afanasy already used to render VRAY in a "distributed" way, when one frame being rendered by several machines (master machine asks slaves to render buckets).

**Comment by sergeneren** [comment]
Hi again Timur, 

the tracker computer should be running the tracker.py that comes shipped with houdini via hython.exe after setting the ports, and the slaves just need their $SLICE attribute set up. The rest of communication is done via tracker unit. Actually Jeff Wagner has a beautiful explanation on the subject and an sh script ready at:

http://www.sidefx.com/index.php?option=com_content&task=view&id=1516&Itemid=216

Thank you for your time.

**Comment by timurhai** [comment]
Hi.
I see. Interesting theme. But for now i can`t say when i can do this.
But i am ready to guide somebody any time.
( lets keep this issue opened )

**Comment by sergeneren** [comment]
Ok. I don't think it is urgent anyway since houdini now can fully employ flip sim distribution with houdini 15 and not many studios have upgraded yet.

**Comment by timurhai** [comment]
You can distribute simulations within Afanasy,
but you should case about tracker manually.
Tracker is a python script from houdini, that helps to exchange info between slices,
it is not hqueue, but hquere cares about tracker stop/start and its address/port itself.
Take care about tracker will be the next step for Afanasy.
But you can simple it on some(any) machine manually and point scene to it.

**Comment by sebastianelsner** [comment]
Handling the tracker would mean that afanasy needs to pass the tracker's ip address from one task to another right? Can it do that?

**Comment by timurhai** [comment]
Afanasy server engine can't pass info from one task to other.
So it can't launch a tracker task on some host, and then specify it for other tasks.
We can think how to imrove server to be able to do it.
But for now we can simple specify tracker host name in a submisson script, it can create a block with a host mask matches this host, and other tasks will know about tracker location at submission stage.

**Comment by sebastianelsner** [comment]
Yes, sounds like a plan. The only thing to keep in mind then: If I remember correctly only one tracker can run on one machine.

**Comment by ultra-sonic** [comment]
this sounds like it could be doable by using multi-host rendering - maybe
in a slightly adjusted fashion, where the service of the job knows who the
master (in this case the tracker) is...does this make sense?

**Comment by timurhai** [comment]
Hi.
It looks like multihost, but has a principal difference. Multihost master task it is a major task to take care, parse ouput and so on. It uses slaves to send buckets and take care about an entire picture itself.
Simulation tracker task is not a major task, it is like 1 slave for several masters.

So on slice simulation, we should take care about slices tasks, parse their ouput and so on.
Simulation is on the contrary to multihost, here is several masters and 1 slave.
So one simulation will definitely have as much tasks as hosts (at least +1 may be for tracker).
And i do not see any ways to use multihost technology for slices.

**Comment by timurhai** [comment]
It is done.
Tracker address and port passed to simulation tasks via job block environment manipulation.
Testing needed.
