### ISSUE TITLE
[Feature Request] Redshift integration

### ISSUE THREAD

**Issue by penthoy** [CGRU/cgru#154]
would be awesome if afanasy can support redshift GPU render, as our studio is in the process of integrating gpu rendering technology to accelerate rendering, and it'll be the biggest trend in rendering technology for the next few years to come. at the moment, deadline seems to have the best integration with redshift. Just wish we can use afanasy instead for this purpose.

**Comment by timurhai** [comment]
Hi.
Afanasy can support or not to support GPU or whatever. It just run commands (server sends clients commands to run). Child process can use or not to use any hardware feature, like GPU.

When we say for example "Afanasy supports Blender" - this means that there is some submission script that comes with CGRU "out-of-the-box". Such script allows to construct and send job (tasks commands to run) from 3(2)D application GUI to Afanasy server.

Also there is AfStarter stand-alone dialog, that allows to select some file(s) that can be a sequence of frames to render and construct+send job.

**Comment by penthoy** [comment]
Thanks Timur, I understand, I'll try to look into the existing submission script and try to develop our own, when we're ready to move forward with the Redshift renderer. will check back if I'm stuck.
