### ISSUE TITLE
AFERROR: af::removeDir: Can't delete file

### ISSUE THREAD

**Issue by penthoy** [CGRU/cgru#157]
when I try to delete a task from browser, in the server it'll give this error:
AFERROR: af::removeDir: Can't delete file:/var/tmp/afanasy/jobs/0/filename.nk-afanasy/tasks
Is a directory

and when the server crashed on error, and I had to exit it by using ctrl+c, to restart it, the same task come back and never gets deleted. I wonder if that was related to this error.

Thanks in advanced.

**Comment by timurhai** [comment]
Strange error. Server names job folders like: /var/tmp/afanasy/jobs/[ID-thousand]/[ID].name
And you have no ID before name. It should be /var/tmp/afanasy/jobs/0/123.filename.nk-afanasy
"tasks" is always a folder in a job store folder, it used to store tasks processes outputs.

How about other job folders names?
They have "[ID]." prefix?
Try to stop server and delete this folder by hand.

**Comment by penthoy** [comment]
Sorry it does have the [ID].name, I must have over simplied the name, on my first question, here is an example of the raw output:
perhaps you can see some hint to the problem.

AFERROR: af::removeDir: Can't delete file:
/var/tmp/afanasy/jobs/0/29.MK2_20_1020_cmp_wangzheng_pre_v011.nk-afanasy/tasks
Is a directory

ERROR Fri 30 Oct 20:26.43: Unable to remove old store folder:
/var/tmp/afanasy/jobs/0/29.MK2_20_1020_cmp_wangzheng_pre_v011.nk-afanasy
Fri 30 Oct 20:26.43: Job registered: "MK2_20_1020_cmp_wangzheng_pre_v011.nk-afanasy"[29]: dexter@dexter-5[2] - 18372 bytes.

**Comment by penthoy** [comment]
farm just frozen right now here is the repeating output:

ERROR Sat 31 Oct 03:28.16: AfContainerIt::get(): node == NULL : id = 28
Sat 31 Oct 03:28.16: Monitor registered: coord@pc:-12[13] v'2.0.6' 192.168.2.72
ERROR Sat 31 Oct 03:28.16: AfContainerIt::get(): node == NULL : id = 28
Sat 31 Oct 03:28.16: Monitor registered: coord@pc:-13[14] v'2.0.6' 192.168.2.48
Sat 31 Oct 03:28.16: Monitor registered: coord@pc:-14[15] v'2.0.6' 192.168.2.42
Sat 31 Oct 03:28.16: Monitor registered: coord@pc:-16[16] v'2.0.6' 192.168.2.48
AFERROR: accept: Too many open files

AFERROR: The per-process limit of open file descriptors has been reached.
ERROR Sat 31 Oct 03:28.16: AfContainerIt::get(): node == NULL : id = 28
Sat 31 Oct 03:28.17: Monitor zombie: coord@pc:-17[18] v'2.0.6' 192.168.2.72
Sat 31 Oct 03:28.17: Monitor zombie: coord@pc:-34[35] v'2.0.6' 192.168.2.48
Sat 31 Oct 03:28.24: Monitor registered: coord@pc:-17[18] v'2.0.6' 192.168.2.77
Sat 31 Oct 03:28.24: Monitor registered: coord@pc:-18[19] v'2.0.6' 192.168.2.48
Sat 31 Oct 03:28.24: Monitor registered: coord@pc:-19[20] v'2.0.6' 192.168.2.48
Sat 31 Oct 03:28.24: Monitor registered: coord@pc:-20[21] v'2.0.6' 192.168.2.144
ERROR Sat 31 Oct 03:28.24: AfContainerIt::get(): node == NULL : id = 33
ERROR Sat 31 Oct 03:28.24: AfContainerIt::get(): node == NULL : id = 33
AFERROR: accept: Too many open files

AFERROR: The per-process limit of open file descriptors has been reached.
ERROR Sat 31 Oct 03:28.24: AfContainerIt::get(): node == NULL : id = 33
Sat 31 Oct 03:28.25: Monitor zombie: coord@pc:-4[5] v'2.0.6' 192.168.2.42

I'll run your commands next and paste the output
