### ISSUE TITLE
Unknown message recieved: TRESERVED11: Length=78, type=125

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#166]
Hi timur,
any chance you could tell me what's wrong here. I am using afanasy through a VPN and double-checked firewall rules already and they seem fine.

afwatch output
```
TJSONBIN: Length=78, type=125
{"get":{"type":"jobs","mode":"thumbnail","ids":[2],"binary":true}}
TJSONBIN: Length=78, type=125
{"get":{"type":"jobs","mode":"thumbnail","ids":[3],"binary":true}}
AFERROR: qtcom::readdata::read: Operation now in progress
AFERROR: qtcom::recvMessage: read message header.
AFERROR: QThreadClient::sendMessage: recieving message failed.
AFERROR: qtcom::readdata::read: Operation now in progress
AFERROR: qtcom::recvMessage: read message header.
AFERROR: QThreadClient::sendMessage: recieving message failed.
```

afserver output
```
Thu 10 Dec 09:51.00: Monitor registered: omarkowski@quad-03-lx:51002[1] v'2.0.8' 79.214.xxx.xxx:51002
ERROR Thu 10 Dec 09:51.00: Unknown message recieved: TRESERVED11: Length=78, type=125
ERROR Thu 10 Dec 09:51.00: Unknown message recieved: TRESERVED11: Length=78, type=125
Thu 10 Dec 09:51.30: Monitor registered: omarkowski@quad-03-lx:51002-1[2] v'2.0.8' 192.168.x.xx:51002
ERROR Thu 10 Dec 09:51.31: Unknown message recieved: TRESERVED11: Length=78, type=125
ERROR Thu 10 Dec 09:51.31: Unknown message recieved: TRESERVED11: Length=78, type=125
```

**Comment by timurhai** [comment]
Hi.
It can be when various server and client versions.
When they became totally incompatible, an this can cause hang, there will be 2.1.0.
2.0.x clients can work together but they can miss some new functions, message types.

**Comment by ultra-sonic** [comment]
hmm....I am pretty sure that I compiled using the same sourcecode...will double check again

**Comment by timurhai** [comment]
May be not the same?
https://github.com/CGRU/cgru/commit/93d118181035e75d0f6ce53115c32b9e57b6282e#diff-ec8c7d1b7103c4bd3bd70ac16f983ca5L655

**Comment by ultra-sonic** [comment]
that looks like it....will investigate further :)
thx a lot so far!

**Comment by ultra-sonic** [comment]
solved....even though ```git log``` shows the same last commit hash it seems I screwed up somewhere in between. copied the binaries over to the remote networks server and now it works!
Thx mate!
