### ISSUE TITLE
how could we WOL-sleep rendernodes only close to full "uptime-hours"

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#167]
Hi Timur,

i am running afanasy on the Amazon Cloud and I want my instances to WOL-sleep only if their uptime is close to a full hour (55min, 1h55m, 2h55,....,12h55m,....,etc). This is of course because amazon charges by the hour and not by minute like google and I don't want to waste money.

Any chance I can do that in code by myself? Can you point me to the part of the code where I should do that modification?

Another idea is to modify the WOL-sleep command to check if I am in a good "uptime-window" and do nothing if this is not the case. Would that work? How often does the server trigger the WOL-sleep command? Can I return unsuccessful somehow so that the server does not assume the client went to sleep?

thanks in advance
Oli

**Comment by timurhai** [comment]
Hi.
Time check should be here
https://github.com/CGRU/cgru/blob/master/afanasy/src/server/renderaf.cpp#L677
You can modify it for your specific situation, but i wonder how it can be configurable?

    wol_time_mod - ( time() % wol_time_mod ) < wol_time_delta

Can it be so? In your case wol_time_mod=3600 and wol_time_delta=300

btw
Now there is 2.1.0 in repo, not very tested and incompatible with 2.0.x

**Comment by lithorus** [comment]
Is this relvant anymore? Hasn't all the cloud providers switch to per minute (or less) billing?

**Comment by ultra-sonic** [comment]
this is irrelevant now...thanks for the pointer...didn't notice that AWS is
per second now...

**Comment by lithorus** [comment]
Will close the issue then :)
