### ISSUE TITLE
Not Render Blender Cycles in Linux

### ISSUE THREAD

**Issue by calimanoliveira** [CGRU/cgru#168]
Hi,

my problem is that the blender cycles is not rendering using the GPU in Linux Mint 17.02 and blender is 2.76b, the blender only rendering in CPU.

Thanks

**Comment by predat** [comment]
I don't think this problem is relative to cgru. Have you try to render your scene from command line ?
What is the output log from afrender or afwatch ?

**Comment by calimanoliveira** [comment]
does not show error, but not render use GPU, only CPU, the render is usaully done.

**Comment by predat** [comment]
Have you try to render from the command line ?

**Comment by calimanoliveira** [comment]
Yes normally, print of the render in command line

![captura de tela de 2015-12-21 21 39 58](https://cloud.githubusercontent.com/assets/16392355/11944232/b45683d4-a82b-11e5-9e3f-7b8e7f441aa8.png)

**Comment by calimanoliveira** [comment]
Time render is correctly.

![captura de tela de 2015-12-21 21 42 09](https://cloud.githubusercontent.com/assets/16392355/11944275/09f4d1ba-a82c-11e5-9e2c-280ef62872db.png)

**Comment by predat** [comment]
Do you send your job from blender using the add-on ? If so what is the json output in terminal ?

What is the output block message in afwatch or in the browser ?

Cgru/afanasy does not change your render settings.

**Comment by calimanoliveira** [comment]
No i'm submit Job for Keeper

**Comment by calimanoliveira** [comment]
Configuration for submit Job and time for the watch, not good time.

![captura de tela de 2015-12-21 21 57 42](https://cloud.githubusercontent.com/assets/16392355/11944575/35c9406c-a82e-11e5-8dc0-153a8182b9b4.png)

**Comment by calimanoliveira** [comment]
my configuration

![captura de tela de 2015-12-21 21 51 08](https://cloud.githubusercontent.com/assets/16392355/11944643/c8025716-a82e-11e5-94a2-6b55e6e70f16.png)

**Comment by predat** [comment]
If you rigth click on frame 1 and output, what do you see ?

**Comment by calimanoliveira** [comment]
nothing, render not finalization, see a print.

![captura de tela de 2015-12-21 22 08 32](https://cloud.githubusercontent.com/assets/16392355/11944803/db04f4e4-a82f-11e5-850c-2849d3c3dc82.png)

**Comment by predat** [comment]
If you copy/paste the command show in the task window in a terminal, what is the result ?

**Comment by predat** [comment]
Have you find the problem ?
What has the solution ?
Can i close this issue ?
Better post those problems at http://rules.cgru.info

**Comment by calimanoliveira** [comment]
Hi predat, i'm sorry, i'm testing other solutions, but however all giving error.

![captura de tela de 2015-12-22 11 07 09](https://cloud.githubusercontent.com/assets/16392355/11955847/7d49aeea-a89c-11e5-9688-b54cd6006f34.png)

For command line is OK, time is good, but send use Submit Job of Keeper, it does not work properly

![captura de tela de 2015-12-22 11 01 54](https://cloud.githubusercontent.com/assets/16392355/11955791/02a4b07c-a89c-11e5-8dee-ee8a55779a0a.png)

**Comment by predat** [comment]
I'm thinking afanasy is not using your blender gpu preferences. Have you try to launch blender from keeper to see what your prefs are ?

**Comment by calimanoliveira** [comment]
Yes my blender is configure in launch for keeper.

**Comment by predat** [comment]
When you right click on a frame in afwatch, you can see the blender blog for this frame. At the beginning of the blender log, you can see witch preferences file is in use.

**Comment by calimanoliveira** [comment]
where it is ?? i can't find.

![captura de tela de 2015-12-22 12 17 03](https://cloud.githubusercontent.com/assets/16392355/11957095/6a219576-a8a6-11e5-815c-cd542245a5fc.png)
![captura de tela de 2015-12-22 12 17 14](https://cloud.githubusercontent.com/assets/16392355/11957099/6a4b3822-a8a6-11e5-9c13-d6f8d81882d9.png)
![captura de tela de 2015-12-22 12 17 24](https://cloud.githubusercontent.com/assets/16392355/11957096/6a21e1fc-a8a6-11e5-8a8e-65985c0cddba.png)
![captura de tela de 2015-12-22 12 17 31](https://cloud.githubusercontent.com/assets/16392355/11957098/6a49a7fa-a8a6-11e5-85a7-1a0aeae70af0.png)

**Comment by predat** [comment]
Righ click on a frame and 'log' or 'output' i don't remenber ! Or 'listen'

**Comment by calimanoliveira** [comment]
This is the initial result:


HOSTNAME=gpu02
read blend: /mnt/Arquivos/Projetos3D/WilliamTokis/LOBITO/modelos/casa_PMC_Office_animacao_antigo.20151222124855.blend
Fra:8 Mem:585.62M (0.00M, Peak 585.62M) | Time:00:00.39 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Porta02_GEO.002
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.41 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Camera
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.41 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Plane
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.41 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Janela02_GEO.002
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.41 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Sun
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.41 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Base_GEO.002
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.41 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Line006
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.41 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Parece04_GEO.001
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.41 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Porta02_GEO.001
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.41 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Base_GEO.001
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.41 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Rodape_GEO.001
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.41 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Batente_Porta02_GEO.001
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.41 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Object015.001
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.41 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Janela02_GEO.001
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.41 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Parece01_GEO.001
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.41 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Batente_Porta01_GEO.001
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.41 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Corrimao_Esc02_GEO.001
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.41 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Parece03_GEO.001
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.41 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Line005
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.42 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Corrimao_Esc01_GEO.001
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.42 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Janela03_GEO.001
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.42 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Parece02_GEO.001
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.42 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Shape002
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.42 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Rock02_LP
Fra:8 Mem:585.62M (0.00M, Peak 590.77M) | Time:00:00.42 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Base_GEO.003
Fra:8 Mem:402.68M (0.00M, Peak 1340.40M) | Time:00:08.12 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | grama.001
Fra:8 Mem:402.68M (0.00M, Peak 1340.40M) | Time:00:08.12 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Initializing
Fra:8 Mem:402.68M (0.00M, Peak 1340.40M) | Time:00:09.61 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Loading render kernels (may take a few minutes the first time)
Fra:8 Mem:402.68M (0.00M, Peak 1340.40M) | Time:00:09.63 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Waiting for render to start
Fra:8 Mem:402.68M (0.00M, Peak 1340.40M) | Time:00:09.63 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Updating Scene
Fra:8 Mem:402.68M (0.00M, Peak 1340.40M) | Time:00:09.63 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Updating Shaders
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:09.75 | Mem:0.01M, Peak:0.01M | Scene, RenderLayer | Updating Background
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:09.75 | Mem:0.01M, Peak:0.01M | Scene, RenderLayer | Updating Camera
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:09.75 | Mem:0.01M, Peak:0.01M | Scene, RenderLayer | Updating Objects
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:09.75 | Mem:0.01M, Peak:0.01M | Scene, RenderLayer | Updating Objects | Copying Transformations to device
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.02 | Mem:167.86M, Peak:167.86M | Scene, RenderLayer | Updating Objects | Applying Static Transformations
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.06 | Mem:167.86M, Peak:167.86M | Scene, RenderLayer | Updating Meshes Flags
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.06 | Mem:167.86M, Peak:167.86M | Scene, RenderLayer | Updating Meshes
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.06 | Mem:167.86M, Peak:167.86M | Scene, RenderLayer | Updating Mesh | Computing normals
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.06 | Mem:167.86M, Peak:167.86M | Scene, RenderLayer | Updating Mesh | Copying Mesh to device
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.06 | Mem:169.78M, Peak:169.78M | Scene, RenderLayer | Updating Mesh | Computing attributes
Found APP1 XMP! length 3856
Found APP1 XMP! length 4678
Found APP1 XMP! length 4678
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.18 | Mem:322.37M, Peak:322.37M | Scene, RenderLayer | Updating Mesh | Copying Attributes to device
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.18 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Mesh BVH Janela02_GEO.001 2/5 | Building BVH
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.18 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Mesh BVH Plane.005 5/5 | Building BVH
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.18 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Mesh BVH Corrimao_Esc01_GEO.001 3/5 | Building BVH
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.18 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Mesh BVH Porta02_GEO.001 1/5 | Building BVH
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.18 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Mesh BVH Porta02_GEO.001 1/5 | Packing BVH triangles and strands
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.18 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Mesh BVH Porta02_GEO.001 1/5 | Packing BVH nodes
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.18 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Mesh BVH Porta02_GEO.001 1/5 | Packing BVH triangles and strands
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.18 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Mesh BVH Porta02_GEO.001 1/5 | Packing BVH nodes
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.18 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Mesh BVH Porta02_GEO.001 1/5 | Packing BVH triangles and strands
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.18 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Mesh BVH Porta02_GEO.001 1/5 | Packing BVH nodes
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.20 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Mesh BVH Porta02_GEO.001 1/5 | Packing BVH triangles and strands
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.20 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Mesh BVH Porta02_GEO.001 1/5 | Packing BVH nodes
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.27 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Scene BVH | Building
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.28 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Scene BVH | Building BVH
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.66 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Scene BVH | Building BVH 1%, duplicates 0%
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.91 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Scene BVH | Building BVH 83%, duplicates 0%
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.95 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Scene BVH | Packing BVH triangles and strands
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:10.98 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Scene BVH | Packing BVH nodes
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.41 | Mem:322.41M, Peak:322.41M | Scene, RenderLayer | Updating Scene BVH | Copying BVH to device
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.41 | Mem:458.14M, Peak:458.14M | Scene, RenderLayer | Updating Objects Flags
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.43 | Mem:461.95M, Peak:461.95M | Scene, RenderLayer | Updating Images
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.43 | Mem:461.95M, Peak:461.95M | Scene, RenderLayer | Updating Images | Loading concreto1.jpg
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.43 | Mem:461.95M, Peak:461.95M | Scene, RenderLayer | Updating Images | Loading uba_tuba_b.jpg
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.43 | Mem:461.95M, Peak:461.95M | Scene, RenderLayer | Updating Images | Loading Rocks02_DiffuseAtlas_01.png
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.43 | Mem:461.95M, Peak:461.95M | Scene, RenderLayer | Updating Images | Loading Rocks02_NormalAtlas_01.png@1
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.43 | Mem:462.01M, Peak:462.01M | Scene, RenderLayer | Updating Images | Loading sky_cloudy_free.hdr
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.64 | Mem:577.77M, Peak:577.77M | Scene, RenderLayer | Updating Camera Volume
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.65 | Mem:577.77M, Peak:577.77M | Scene, RenderLayer | Updating Hair Systems
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.65 | Mem:577.77M, Peak:577.77M | Scene, RenderLayer | Updating Hair settings | Copying Hair settings to device
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.65 | Mem:577.77M, Peak:577.77M | Scene, RenderLayer | Updating Lookup Tables
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.65 | Mem:578.02M, Peak:578.02M | Scene, RenderLayer | Updating Lights
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.65 | Mem:578.02M, Peak:578.02M | Scene, RenderLayer | Updating Lights | Computing distribution
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.71 | Mem:578.02M, Peak:578.02M | Scene, RenderLayer | Updating Particle Systems
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.71 | Mem:578.02M, Peak:578.02M | Scene, RenderLayer | Updating Particle Systems | Copying Particles to device
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.71 | Mem:578.02M, Peak:578.02M | Scene, RenderLayer | Updating Film
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.71 | Mem:578.02M, Peak:578.02M | Scene, RenderLayer | Updating Integrator
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.71 | Mem:578.05M, Peak:578.05M | Scene, RenderLayer | Updating Lookup Tables
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.71 | Mem:578.06M, Peak:578.06M | Scene, RenderLayer | Updating Baking
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.71 | Mem:578.06M, Peak:578.06M | Scene, RenderLayer | Updating Device | Writing constant memory
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.71 | Mem:578.06M, Peak:578.06M | Scene, RenderLayer | Path Tracing Tile 0/2040
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.71 | Mem:578.77M, Peak:578.77M | Scene, RenderLayer | Path Tracing Tile 3/2040
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.71 | Mem:579.72M, Peak:579.72M | Scene, RenderLayer | Path Tracing Tile 7/2040
Fra:8 Mem:406.76M (0.00M, Peak 1340.40M) | Time:00:11.71 | Mem:579.96M, Peak:579.96M | Scene, RenderLayer | Path Tracing Tile 8/2040

**Comment by predat** [comment]
Who is the user that start afrender ? If it start as a service it must be start be root.
And your settings are not taken into account when your start the job...

Then, you have solutions:
1 - You could try to start afrender with your user account.
2 - You could copy your prefs into root's home folder
3 - You could add a python file to the command line (with -P) to set GPU preferences correctly:

```python
import bpy
FlagCUDA = False

#Select CUDA
try:
    bpy.context.user_preferences.system.compute_device_type = 'CUDA'
    FlagCUDA = True
except:
    print("No CUDA-Device")
    FlagCUDA = False
 
#Choose CUDA device
if FlagCUDA:    
    try:
        bpy.context.user_preferences.system.compute_device = 'CUDA_MULTI_2' #Use all graphics cards if available.
    except:
        bpy.context.user_preferences.system.compute_device = 'CUDA_0' 
#Check which GPUs are there
print("Rendering on: " + bpy.context.user_preferences.system.compute_device)

#set compute device to GPU (in render settings tab in .blend file)
bpy.context.scene.cycles.device = 'GPU'
```

**Comment by predat** [comment]
Who is the user that start afrender ? If it start as a service it must be start be root.
And your settings are not taken into account when your start the job...

Then, you have solutions:
1 - You could try to start afrender with your user account.
2 - You could copy your prefs into root's home folder
3 - You could add a python file to the command line (with -P) to set GPU preferences correctly:

```python
import bpy
FlagCUDA = False

#Select CUDA
try:
    bpy.context.user_preferences.system.compute_device_type = 'CUDA'
    FlagCUDA = True
except:
    print("No CUDA-Device")
    FlagCUDA = False
 
#Choose CUDA device
if FlagCUDA:    
    try:
        bpy.context.user_preferences.system.compute_device = 'CUDA_MULTI_2' #Use all graphics cards if available.
    except:
        bpy.context.user_preferences.system.compute_device = 'CUDA_0' 
#Check which GPUs are there
print("Rendering on: " + bpy.context.user_preferences.system.compute_device)

#set compute device to GPU (in render settings tab in .blend file)
bpy.context.scene.cycles.device = 'GPU'
```

**Comment by predat** [comment]
Who is the user that start afrender ? If it start as a service it must be start be root.
And your settings are not taken into account when your start the job...

Then, you have solutions:
1 - You could try to start afrender with your user account.
2 - You could copy your prefs into root's home folder
3 - You could add a python file to the command line (with -P) to set GPU preferences correctly:

```python
import bpy
FlagCUDA = False

#Select CUDA
try:
    bpy.context.user_preferences.system.compute_device_type = 'CUDA'
    FlagCUDA = True
except:
    print("No CUDA-Device")
    FlagCUDA = False
 
#Choose CUDA device
if FlagCUDA:    
    try:
        bpy.context.user_preferences.system.compute_device = 'CUDA_MULTI_2' #Use all graphics cards if available.
    except:
        bpy.context.user_preferences.system.compute_device = 'CUDA_0' 
#Check which GPUs are there
print("Rendering on: " + bpy.context.user_preferences.system.compute_device)

#set compute device to GPU (in render settings tab in .blend file)
bpy.context.scene.cycles.device = 'GPU'
```

**Comment by calimanoliveira** [comment]
Hi Predat, you first soluction was the correct, thanks you for your help, my afrender is started in other user accont, with that i was not having access to prefs of blender.

Thanks
