### ISSUE TITLE
How to have 1 heavy frame rendering on 15 machines ?

### ISSUE THREAD

**Issue by senshine** [CGRU/cgru#169]
Hi everyone!
I am not sure if this is the right place to post questions, but i couldnt find another CGRU forum.
I have recently setup afanasy renderfarm with 1 manager and 15 clients. I could send out a maya (arnold) render to afanasy from within Maya via the CGRU maya plugin, the files output correctly too. So the drives and basic settings i guess are done correctly.
My problem is i am trying to set it up such that i could use all machines to render 1 heavy frame at one time. Say 1 frame split amongst 15 clients to render? Is it possible? If so how can i set it this way?

I have been reading up on the documentation and i thought it is the Frame per task settings, so i set it to -15, but it didnt work. I think my technical understanding is not very good, so any help will be appreciated!
Thanks again!

cheers
Senshine

**Comment by timurhai** [comment]
Hi.
I know 2 methods to split 1 frame over several machines.
1. Render tiles. Compute just a part of frame on each machine, then combine parts together.
2. Master and slaves. One machine can be a master and send individual buckets on slaves. I know that RenderMan, Mantra and VRay supports it, may be other renders too.

There are 2 solutions "out-of-the-box" in CGRU. Maya-VRay master-slaves method and Houdini-Manta tile render.

Note, that Afanasy just run commands. If your task can be solved in a command line, it can distributed by Afanasy over a farm. No matter what is it, tile render, master-slave or just archive or copy a file.

If you want to do something custom with Afanasy, you should be familiar with a command line and Python.

Just an advice from my experience:
Distribute such heavy frames on shading-lighting only. Usually soft, like Max, Houdini allows this from own GUI w/o any render manager. When shading-lighting will be finished, do not distribute heavy frames, render 1 frame on 1 machine - this is always more effective farm usage.

**Comment by ultra-sonic** [comment]
Arnold is nice, but it's too bad it doesn't support distributed rendering
like mantra or vray.
You need to go the Tile-based approach.

**Comment by senshine** [comment]
Hi Timurhai and ultra-sonic 

Many thanks for the replies! I will see into tile based approach then:)

Timur, you mentioned when shading-lighting will be finished it is better to not distribute heavy frames and render 1 frame on 1 machine, i am just curious why is this more effective in farm usage? 

cheers
-sen

**Comment by timurhai** [comment]
I want to say that:

As usual 10 machines will render 1 frame not 10 times faster than 1 machine will render it.
( and the difference will be noticeable, they can practically do it just 3-5 times faster )

But 10 machines will render 10 frames almost 10 times faster than 1 machine (if each machine will 
render an entire frame).

This i call not effective farm usage.

Why it is so - dig internet.

**Comment by ultra-sonic** [comment]
If you just have one frame then of course it makes no sense to render it on
one machine instead of 15.
But if you have 15 of those heavy frames it is better to render them on
single machines, because it reduces calculation overhead. But we are
talking about 5% speed-hit I guess.

**Comment by senshine** [comment]
Hi guys,
Thanks, i get it. It makes lots of sense.
then i guess my setup works perfectly already :+1: 
Once again, very insightful speaking to you guys :)
by the way, i am working in an animation school so we are setting this up for students to use.
afanasy rocks!

cheers
-sen
