### ISSUE TITLE
WOL wake - can I pass the IP of the sleeping machine to the WOL wake command

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#170]
Hi Timur,

since I am using the Amazon Cloud at the moment I need to modify the WOL wake command a little bit. 

Instead of the MAC-Adress I would need to get the last known IP of the sleeping machine, because the AWS command line interface takes the IP as an additional argument when launching an instance. That way I could prevent launching instances with random IPs all the time.

Is it maybe possible to pass the mac-address as the first argument to the wolwake and the IP as the second?

thx in advance
Oli

**Comment by timurhai** [comment]
Hi.
It is not a big deal to make such fix:
https://github.com/CGRU/cgru/blob/master/afanasy/src/server/renderaf.cpp#L462

But may be better to think up some more flexible way.
May be to pass all render data somehow, it is a complex for a simple command line.
( you can double click render item in afwatch and receive almost everything that server knows, in a web gui will receive a json object will all parameters )

We can do a small fix for you, just add IP if you are in a hurry.

But later we can make wake service as events service, event.py class receives complex data in JSON, and constructs a needed command. And it can be simple rewritten for any special needs.

**Comment by abuisine** [comment]
+1 on this, I would use it a lot :)
both sleep and wake up of an amazon ec2 instance would be greatly appreciated :)

**Comment by timurhai** [comment]
Ok :)
It will be realized as a service (like event), whole render info (entire json object) will passed to python service class, and it can construct any custom command.

**Comment by ultra-sonic** [comment]
awesome!

**Comment by timurhai** [comment]
Done.
Will be since 2.1.0.
From sources you can check now.

Now command is constructed in a Python service class:
https://github.com/CGRU/cgru/blob/master/afanasy/python/services/wakeonlan.py#L60
And its already passing ip address.

**Comment by lithorus** [comment]
Passing the hostname too would also be usefull. I'm already doing this for starting virtual clients on a different queuing system (MOAB). Will try and send a pull request of the changes to the wakeonlan service.

**Comment by timurhai** [comment]
Hi.
Now (in 2.1.0 not released) it pass whole afrender data as JSON to Python `wakeonlan` service class.
And you can do with this data whatever you want.
