### ISSUE TITLE
parsers, better error handling abstraction

### ISSUE THREAD

**Issue by abuisine** [CGRU/cgru#171]
Hi there,
I wrote a couple of parsers (some of them pushed on master) and I feel that it would be better to set warnings / errors / badresults / finishedsuccess strings as arrays in the [parser.py](https://github.com/CGRU/cgru/blob/master/afanasy/python/parsers/parser.py) constructor.

This way to code in parent ([parser.py](https://github.com/CGRU/cgru/blob/master/afanasy/python/parsers/parser.py)) would work with strings being setted in the child construct,
thus avoiding the need to create loops to string.find() in the child do() method.

This would avoid much redundant code in existing parsers.

I would have proposed a PR with everything rewritten but I do not have all softwares to test.

What do you think ?

**Comment by timurhai** [comment]
Hi.
This is a good idea.
I do not have any soft by hand.
But there is 2.1.0 in a master now, it will not be compatible with any later versions.
And the release will not be soon. So now it is a good time for such changes.

Also i checking parser with this command:
https://github.com/CGRU/cgru/blob/master/afanasy/python/check_parser.py
It can launch anything and correct soft is not needed to check syntax errors.

**Comment by abuisine** [comment]
solved in d96f2c2bdd28ccfa9ac378a46945dabc4e1f74c4
I did not have a chance to test all parsers, please feel free to reopen if you face any issue

**Comment by timurhai** [comment]
I was needed to perform small fixes. As i user that parser default strings (like `[ PARSER_BAD_RESULT ]` in lots of custom scripts at work. So to make previous and new parsing compatible, comparison should be case insensitive (we need to lower and strings and output). Previous default string was put to generic parser (i use only it for custom scripts at work :) ).

**Comment by abuisine** [comment]
ok sorry for the lower stuff, I missed that :) so obvious ... (this ends my day which was full of crap)

regarding the generic parser values, I am sorry I broke your scripts, I didn't know about it.
Could you please confirm if you want the keep the special strings in the generic parser long term 😁
I feel that the generic parser should leave simple words such as "error" amd "warning" because most of the softwares being run would have a natural catch.
Just as an example, I use a bunch of various softwares with the generic parser and the new default behavior was welcome.
That's my 2cts, but I can clearly live without the actual status.
Cheers

**Comment by timurhai** [comment]
Hi.
You made parsers better!
And default (base `parser.py` class) values better to keep "error" amd "warning", than "[ PARSER_BAD_RESULT ]" - you are right.
You probably confused naming "base"(parser.py) and "generic"(generic.py) in the latest post.
`parser.py` - is a base for all.
`generic.py` - was designed for an examples/tests and used so, it also became my favorite parser at work :)
And such such non-standard strings as "[ PARSER_BAD_RESULT ]" should not be in base `parser.py`, but in generic. Now this mistake is fixed.

**Comment by abuisine** [comment]
Ok I understood what you meant, but my point is that I do use the generic
parser as well for various softwares.
In fact, our usage of the generic parser conflits, so I am wondering where
to go now :) should I create a "generic2" parser ?
I mean, I am happy to create my "abuisine" generic parser for my usage, but
I think that other people might want a generic like mine (with just 'error'
and 'warning' simple strings) as most of the softwares around do produce
'error' and 'warning' by default.

:)

2016-06-24 13:07 GMT+02:00 Timur Hairulin <notifications@github.com>:

**Comment by timurhai** [comment]
May be create some `common` or `base` parser?
Or user `parser` class directly?

**Comment by timurhai** [comment]
As `generic` is designed for your hand written scripts. If you want to some print "error" manually you always can print "[ PARSER_ERROR ]". But if i launch some external command from my script, and it prints some "error" world - i do not want to stop task, may be just print some warning ("[ PARSER WARNING ]"). As i want to control errors manually. Some errors can be not critical. For example imagemagick convert utility prints lots of errors is some "config.xml" not founded, but works !!!

**Comment by abuisine** [comment]
Alright, no pb, I will create a kind of default for my project :)
