### ISSUE TITLE
multihost job - ignore losing connection to distributed host

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#172]
Hi Timur,

it seems that if a host disconnects during a multihost jobs then the task is restarted. Is there a way to just ignore the missing host and keep going? (e.g. Vray handles missing distributed hosts gracefully and just finishes the job.)

cheers
Oli

**Comment by timurhai** [comment]
Hi.
You are talking when afrender goes Offline?
This can be an issue.
Block can has such flag.
I'll look at it, but later, busy. And after i can say how much time it can take to implement.

**Comment by ultra-sonic** [comment]
No...not just when a render goes offline. Also wenn I eject the distributed
dummy-task on one of the slaves. This does also restart the task on the
master. Is this the intended behaviour?

thx and take your time...
Oli

**Comment by timurhai** [comment]
Hi.
What afanasy should do, if somebody ejected dummy task?
How we can tell master task to stop to use this slave?

**Comment by ultra-sonic** [comment]
>
> What afanasy should do, if somebody ejected dummy task?
>
In my case do nothing. It was just meant to handle a host going offline
gracefully - not for ejecting.

> How we can tell master task to stop to use this slave?
>
I'm afraid there is no way to do that...and as I said: It's just for error
handling. if slave goes away do nothing.

cheers
Oli

**Comment by timurhai** [comment]
Ok.
It is done and i preferred the same behavior.
Task just put to its log that it ignoring ejecting.
So you can check.
There is no docs about it (yet), but api already exists:
https://github.com/CGRU/cgru/blob/master/afanasy/python/af.py#L495

But!
It is new 2.1.0 version in repo, an it is not compatible with any previous.

**Comment by ultra-sonic** [comment]
we are pretty busy these days, but I can test 2.1.0 in march...

**Comment by ultra-sonic** [comment]
I am about to test this....is the current 2.1.0 branch stable enough for
testing?

**Comment by timurhai** [comment]
Yes.
