### ISSUE TITLE
temporarily disable WOL sleep using afwatch?

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#173]
Hi timur,

is there a way to disable WOL sleep on some renders using afwatch?

cheers
Oli

**Comment by timurhai** [comment]
Hi.
No, there is no such option in afwatch.
Also there is no "wol_disabled" flag (parameter) on afserver side.
For now wake-on-lan can be configured in farm setup only.

btw
May be for amazon (or some other cloud) manipulations we should think up some more specialized feature?
Or customizing WOL scripts is enough?

**Comment by ultra-sonic** [comment]
nevermind this issue....this is just a side-effect of not yet being able to shutdown nodes at the end of the full hour of uptime. closing the ticket!
