### ISSUE TITLE
Natron

### ISSUE THREAD

**Issue by ramellij** [CGRU/cgru#175]
Hello, 

I just report that issue to Natron guys :
https://github.com/MrKepzie/Natron/issues/1176
From Afanasy I get this : 
 "AFERROR: Service::parse: parser="natron" returned value is not a tuple"
And from Natron :
 "Spawned process crashed, exiting."

Natron renders the frames but crashes at every end tasks. 
Do you know what it is ?
Thanks for your help
JR

**Comment by timurhai** [comment]
Hi.
What is CGRU version?
Or may be it is compiled from its latest sources?

**Comment by ramellij** [comment]
2.1.0

**Comment by timurhai** [comment]
Hm.
This version is still, in progress.
And i did not tested Natron with 2.1.0.
It seems that something was broken in this version, that affects Natron.
I will check.
I definitely will check all soft types before create 2.1.0 a release.
But right now i have no Natron by hand.

**Comment by ramellij** [comment]
Ok, thanks. 
How can I get previous versions ?

**Comment by ramellij** [comment]
same issue with 2.0.8

**Comment by timurhai** [comment]
Hm
This is strange.
If you have time, you can try it with 2.0.7, when Natron integration just started.

**Comment by olear** [comment]
Did Natron RC5 work? Could be related to changes made to integrate our new crash reporter, you could also send in the crash report and let us take a look (remember to add a comment that you used afanasy). Also note that RC6 on Windows has an issue with EXR due to wrong OpenImageIO version, I'm a bit unsure if that has been fixed, try a snapshot build if possible.

**Comment by ramellij** [comment]
Yes I send the report using NatronIssueReporter and I'm using RC6 "latest" snapshot. 
I'm doing more tests right now. It seems to work correctly using previous versions of Afanasy.

**Comment by olear** [comment]
Did you comment on the crash? Else it's impossible to find your report.

**Comment by ramellij** [comment]
Yes I did with the same message posted in natron issue github. I'll do more tests later and try to reproduce it. But with Afanasy version 2.0.8 it works finally.

**Comment by olear** [comment]
The latest crash reports on Windows is without comments, maybe your report has not been processed,  will check.

**Comment by ramellij** [comment]
I can't reproduce the bug, and now it works fine with all afanasy latests versions (2.0.7, 2.0.8, 2.1.0). I don't understand what happened. Maybe the bug was related to my other Natron versions installed. I removed them to let just the RC6 snapshot and set the path to the good exe. I'll do more tests and report bug if there is.

**Comment by ramellij** [comment]
One other thing
When I launch a job from afstarter I get the correct working directory, wich is my network drive so all clients can see it (//WORKSTATION-PC/...). And when I use Afanasy node in Natron it sets my local drive as working directory (C:\USER\...) and so they can't reach it and fail to render. 
My project settings in Natron are good but somehow it changes it. 

Also using afstarter thumbnails aren't created.

**Comment by timurhai** [comment]
Hi.
Checked RC6 and 2.1.0 - work fine.

May be when you took 2.1.0 sources, it was broken exactly that time.
Working on a new version i can commit some half of changes, just to store.

**Comment by timurhai** [comment]
ps
Better to use releases.
And sources for tests/develop only.

**Comment by ramellij** [comment]
Hi Timur, 

Sorry to bother you with this but I still can't use Afanasy with Natron. 
My tasks are rendering in loop and all I get from Output is (at the very end, after all frames are done): 

`Spawned process crashed, exiting.`

I use Natron 2.3.9 and Afanasy 2.2.3, the officials releases. 
And I use afStarter to launch my jobs (Windows 7). 

Thanks for your help
JR

**Comment by timurhai** [comment]
Hi.
1. Try to launch task command in a console. You should use the same environment, with or w/o display, user, working folder.
2. Try to see Natron process output, Natron logs, script editor message. Try to find out what does not work and why. There should be some error messages somewhere or we do not know what to fix.
