### ISSUE TITLE
Run action on "No task progress for x time"

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#176]
I would like to implement a feature, which checks the progress of a task and if there was no or little progress an action is taken like killing the task. This is especially handy for tasks that are haning. Can this be done in a service or in a parser? Or do I need to touch the C++ core? Maybe you can point me in the right direction.

**Comment by timurhai** [comment]
Hi.

Some likely parameter already exists:
http://cgru.info/afanasy/job#block_tasks_max_run_time
But it is progress independent.

And you can implement such progress changes check in a parser:
http://cgru.info/afanasy/render#badresult

**Comment by sebastianelsner** [comment]
Nice, thanks! 
If there is no output after a while will the "do" or "parse" functions be called again? And can I store an instance variable named "previousProgressValue" in a service, or would it get lost between calls of "do"? Because I am trying to compare a previous progress value with a current progress value.

**Comment by timurhai** [comment]
You can store in a class anything.
Service and parser classes are instanced before task start and destroyed after task finish.
But, you are right, it is not suitable for you, because parser function is not called if there is no output.

https://github.com/CGRU/cgru/blob/master/afanasy/src/render/taskprocess.cpp#L380

It calls in any case (it there is no output) only one, just after task process finish.

**Comment by sebastianelsner** [comment]
Looking at the code, I think I could just remove L380 and have the parser running every time even if empty (always have i_read_empty=true). Do you think this could create any issues in terms of functionality or performance?

**Comment by timurhai** [comment]
Just very-very small performance issue, as parser will be called with no need.
Sure you can comment that check.

I think is can be better if parser will be called in any case 1 time from 100 calls.
 - if you do so, you can make a pull request.

**Comment by sebastianelsner** [comment]
Will get on it next week, thanks!

**Comment by ultra-sonic** [comment]
Glad you got your answer Sebastian!

**Comment by sebastianelsner** [comment]
So I have investigated a bit, if I run only every 100th cycle (i.e. every ~ min) this will be not enough for our usecase. So I removed the lines all along and the parser is invoked every run even when empty. If you want I can do a pull request.
