### ISSUE TITLE
custom resource keeps printing QString::arg: Argument missing:

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#177]
I have a very simple resource, that keeps printing:

` QString::arg: Argument missing: sebels, 1`

in the terminal I started afwatch in. the resource is like this. 

```
class loggedinusers(resbase.resbase):


	def __init__(self):
		resbase.resbase.__init__(self)
		self.value = 0
		self.valuemax = 0
		self.height = 20
		self.graphr = 0
		self.graphg = 255
		self.graphb = 0
		self.labelsize = 10
		self.labelr = 255
		self.labelg = 255
		self.labelb = 0
		self.bgcolorr = 10
		self.bgcolorg = 20
		self.bgcolorb = 5
		self.width = 0
		self.valid = True

	def update(self):
		self.label = "Users: " + ", ".join(set(u.name for u in psutil.users()))

```

**Comment by timurhai** [comment]
Hi.
If valuemax < 1, plotter calculates scale automatically.
This way Network and Disk speed works.
When scale computes automatically, it prints scale in a label by QString::arg function, that assumes that %1 sting presets in a label.

You can plot number of users, for example.
Set valuemax or use %1 in a label, for example:
self.label = "Users[%1]: " + ", ".join(set(u.name for u in psutil.users()))

Now added a check for "%1":
https://github.com/CGRU/cgru/commit/7ef4b550202dbabdabda0d3fd81438203a5f1b9f#diff-84f71a2182f960ef72e5425c84a7e89aR180
