### ISSUE TITLE
networking errors

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#178]
We have many errors like this:

```
AFERROR: af::msgread: can't read message header, bytes = -1 (< Msg::SizeHeader).
AFERROR: readdata: read: Resource temporarily unavailable
```
I have no clue what this is about....

and

```
Sun 14 Feb 23:43.10: Render: "station0404.rise" - ZOMBIETIME
Sun 14 Feb 23:43.10: Render Offline:  off                    station0404.rise@neuron[302] 10.10.11.150:51001
AFERROR: TaskRun::update: taskup.getClientId() != hostId (302 != 284)
AFERROR: TaskRun::update: taskup.getClientId() != hostId (302 != 284)
AFERROR: TaskRun::update: taskup.getClientId() != hostId (302 != 284)
AFERROR: TaskRun::update: taskup.getClientId() != hostId (0 != 284)
AFERROR: TaskRun::update: taskup.getClientId() != hostId (0 != 284)
Sun 14 Feb 23:43.40: Render:  ON                     station0404.rise@neuron[302] 10.10.11.150:51001

```
The computer was fine at the time, at least thats what /var/log/messages tells me. It did not reboot, or crash.

What can I do to debug this? No firewalls involved.

**Comment by ultra-sonic** [comment]
Hey Timur,

this seems here seems to become a shopstopper:
```
AFERROR: TaskRun::update: taskup.getClientId() != hostId (302 != 284)
AFERROR: TaskRun::update: taskup.getClientId() != hostId (0 != 284)
```
Any idea about a quick fix or patch that we could implement?

thx in advance!
Oli

**Comment by timurhai** [comment]
Hi.
What OS client runs on?

**Comment by ultra-sonic** [comment]
Centos6.6 - full logs coming your way via email

**Comment by timurhai** [comment]
Sorry for a delayed answer.
We have a deadline now.

**Comment by ultra-sonic** [comment]
We too ;) I totally understand...
Our old rendermanager couldn't handle the load we have at the moment so we
decided to go for afanasy but unfortunately we have issues to.

Could it be that "deleting a job" causes some confusion on afserver?

**Comment by timurhai** [comment]
I can't say.
Huge load debugging is always very difficult.

Try monitor sockets and on server and on some client.
For example:

   netstat -nat | egrep ':51000.*:.*TIME_WAIT' | wc -l
   ss -tan 'sport = :51000' | awk '{print $(NF)" "$(NF-1)}' | sed 's/:[^ ]*//g' | sort | uniq -c

**Comment by timurhai** [comment]
I saw logs. Looks like server and client can't connect each other sometime. And server thinks that client went offline. But after some time, render continues to sent task progress, when server already took that task from this render.
We should look for a socket connection problem reason.

**Comment by ultra-sonic** [comment]
>
> netstat -nat | egrep ':51000.*:.*TIME_WAIT' | wc -l
> ss -tan 'sport = :51000' | awk '{print $(NF)" "$(NF-1)}' | sed 's/:[^
> ]*//g' | sort | uniq -c
>
what exactly should we be looking for in those netstat and ss commands?

**Comment by timurhai** [comment]
May be open sockets quantity is big.
If so, we should state that they hanging on.
( usually if there is a huge quantity sockets problem - they are hanging in TIME_WAIT state )

**Comment by sebastianelsner** [comment]
Hey, we have about 70 TIME_WAIT sockets on the client, none on the server. Do you think its a good idea to set these values to sysctrl?

net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.ip_local_port_range = 15000 65000

**Comment by timurhai** [comment]
70 TIME_WAIT - is no problem at all
You can to change network tcp settings.
But i think you should know how many open ports (sockets) you have.
If not many - this is not a problem.

Also, when you checking ports?
When afserver works fine?
Try to check on a big farm load.
Also try to check when afserver woks bad.

**Comment by ultra-sonic** [comment]
Hey Timur,

could it be that running afserver in verbose mode (-V) cause a log flooding and therefore slows down everything else? because I have the feeling this might be the case here...the process cpu utilization is only 10% and some afserver threads are running idle....

**Comment by timurhai** [comment]
Hi.
Yes, too much logs flooding can be an issue.
Such problems appear only if hundreds of renders a busy?
( so hundreds are running and updating their percentage ? )

**Comment by ultra-sonic** [comment]
yes....there are 250 nodes and usually 20 afwatchers...

**Comment by timurhai** [comment]
May be this is 250 TCP connections per second problem.
As each task updates percentage every second.
We can try to make that if there is only percentage update (not task process state)
it can update every 5 seconds (for example), this can lower connection 5 times.
But any way, now we can't say if this is the reason or not.

**Comment by timurhai** [comment]
Server 100% hangs as soon as 250 tasks starts?
Or it can work fine for some time, but can hung any time?
How often is hangs on such load?

**Comment by ultra-sonic** [comment]
no...it was running quietly all night, but as soon as people were starting afwatch to check their jobs in the morning the log got flooded by message like:
"Task::updateState: Task is not running"
or
"RenderAf::closeLostTaks"
and they didnt stop to appear until we exited all afwatches and pasued all renders....

**Comment by timurhai** [comment]
So, you think that problem probably connected with afwatch?
Problem not starts is not to launch afwatch?

**Comment by ultra-sonic** [comment]
yes.....i think so.....everything fine over night and it started to freak out after the artists came in today and interacted with their jobs in some way

**Comment by ultra-sonic** [comment]
logs coming your way soon!

**Comment by timurhai** [comment]
I saw log.
Afanasy bugs starts from the beginning.
It can't connect to afwatches.
Afwatch registers on server and receive changes from server - server sends what have changed itselt.
So afwatch opens port, and listens it. And server can't connect to it.
Try to use WebGUI - it does not listen any port - it works like a classic web site - it asks server periodically for changes itself.
So it can increase traffic. If no changes - server does not send anything to afwatch.
But WebGUI always asks for changes.
 - But may be, some reason of this bug is here.

So - try WebGUI only.
(but this is just test - most probably it will be worst - as traffic will be increased)

**Comment by sebastianelsner** [comment]
I think this had nothing to do with the watch, see my other issue.

**Comment by sebastianelsner** [comment]
I close this issue for now, this seems to be a behavioral artifact of afanasy, which we are investigatting now in #181
