### ISSUE TITLE
Segfaulted Task considered as done

### ISSUE THREAD

**Issue by eliemichel** [CGRU/cgru#180]
I tried to run a task that segfaults (intentionally, for testing purpose) but afanasy's seems to consider it done anyway. When I try to get its output, I get the following:

```
Getting task output: Can't get file:
/var/tmp/afanasy/jobs/0/5.infinite-rec.003/tasks/0.0/output/1.txt
No such file or directory
Check task log.
If there is 'update timeout' check firewall.
Client should listen a port and server should be able to connect to it.
```

So,  `task/x.x/output/` is indeed empty, but the firewall is not an issue, since with valid tasks it works.

The Error Hosts remains empty:

```
The task has no error host.
```

I have a very basic test setup, with one server and one render, and just submitted a job with a block of tasks running this:

```python
#!/usr/bin/env python
import sys
sys.setrecursionlimit(999999999)
def ack(n, m):
  if n == 0: return m + 1
  if m == 0: return ack(n - 1, 1)
  return ack(n - 1, ack(n, m - 1))
print(ack(10, 10))
```

(`ack` stands for Ackerman function, a typical example of highly recursive function)

**Comment by timurhai** [comment]
Hi.
Please provide task log (along with output).
You can get it: jobs list -> double click on a job -> tasks list -> RMB on a task -> Log
Or in web gui almost the same, but press Log button.

**Comment by timurhai** [comment]
Also afrender log (client program stdout) can have useful info.

**Comment by eliemichel** [comment]
`Task log is empty`

And afrender output is the regular output, except for the mention to segfaults. A succession of such blocks:

```
Started PID=...
Finished PID=...
Task terminated/killed by signal: 'SegmentationFault'
```

**Comment by timurhai** [comment]
Task log can't be empty, if afrender launched something.
Afserver puts to log every change that it makes with a task.
May be this is log from other task?

**Comment by eliemichel** [comment]
I have only one job with all tasks set to the segfaulting one in this test.

**Comment by eliemichel** [comment]
Problem seems to come from the use of `WEXITSTATUS` in the `checkExitStatus()`.
When my job segfaults, it returns to afanasy an exit code of 11, and `WEXITSTATUS(11)` is equal to `0` on my machine... Ok, that is weird, so I'll keep on investigating, but I just wanted to give some heads up

**Comment by eliemichel** [comment]
```
WIFEXITED(status)
returns true if the child terminated normally, that is, by calling exit(3) or _exit(2), or by returning from main().
WEXITSTATUS(status)
[...] This macro should only be employed if WIFEXITED returned true.
```

In my case, it's been interrupted by a signal, so `WEXITSTATUS(status)` is not relevant!

**Comment by timurhai** [comment]
Ah. I see. This is a bug.
So, we should replace this line
https://github.com/CGRU/cgru/blob/master/afanasy/src/render/taskprocess.cpp#L526
with this:

    bool success = false;
    if( WIFEXITED( i_exitCode))
        success = m_service->checkExitStatus( WEXITSTATUS( i_exitCode));

**Comment by eliemichel** [comment]
It works, thanks!

**Comment by timurhai** [comment]
https://github.com/CGRU/cgru/commit/d4d48e14adf0cad56b0136e779d1ae330fb8aa60
