### ISSUE TITLE
Cascade of errors when a task timeouts

### ISSUE THREAD

**Issue by eliemichel** [CGRU/cgru#181]
I did a quick stress test with 100 nodes on the same machine.

First thing is that to do so, I had to disable the conditions in `rendercontainer.cpp:36` and `clientcontainer.cpp:55` because the `-hostname` option did not work. It did not work in the sens that the node was running, but not given any job and its Host info were looking different.

Anyway, once I had all of those nodes running, I started a bunch of fake jobs on it (basically replaying a houdini log line by line, waiting one second after each).

I lowered the `af_task_update_timeout` to 2s. As I have everything on the same machine and that the server is only waiting 1s in its loop, I though it should be ok, or just drop sometimes, but without it being a big trouble. If one job timeouts, it should just be rescheduled and that's it.

But... After the first timeout occurred, it's been a terrible tempest of errors. No task was able to finish. Note that I did several tests and sometimes it was happening by itself, sometimes I had to help it a little bit with some `ctrl+Z; fg` on the server.

For some reason, the server must mix things because it appeared to kill every single task almost as soon as they were started by the client.

I join a full log of the server run, plus a log of one of the node. Note that I added some custom debug lines that you may find useful.

[afrender-stress.log.txt](https://github.com/CGRU/cgru/files/153206/afrender-stress.log.txt)
[afserver-stress.log.txt](https://github.com/CGRU/cgru/files/153207/afserver-stress.log.txt)

**Comment by eliemichel** [comment]
This might help:

```
Wed 02 Mar 16:56.36: WARNING: currenttime: 1456934196 m_progress->time_done: 1456934187 (difference: 9) af::Environment::getTaskUpdateTimeout() 10
Wed 02 Mar 16:56.37: WARNING: currenttime: 1456934197 m_progress->time_done: 1456934187 (difference: 10) af::Environment::getTaskUpdateTimeout() 10
Wed 02 Mar 16:56.38: WARNING: currenttime: 1456934198 m_progress->time_done: 1456934187 (difference: 11) af::Environment::getTaskUpdateTimeout() 10
Wed 02 Mar 16:56.38: Stop task [job=47, task=9] on render #1(message: Task update timeout.)
Wed 02 Mar 16:56.39: WARNING: currenttime: 1456934199 m_progress->time_done: 1456934187 (difference: 12) af::Environment::getTaskUpdateTimeout() 10
```

It seems that after stopping a job because of a timeout, it iterates one more time on it. Is it expected?

**Comment by timurhai** [comment]
Hi.
Sorry for a delay.

Just checked "-hostname" works for me, strange. Also you can use AF_HOSTNAME env var:
http://cgru.info/installation#config_environment

I think af_task_update_timeout=2 is not a good idea, afserver and afrender "heartbeat" is 1 second + some time for data transfer. So 2 seconds can be not enough.

Sorry did not got your last message. What file and function you think has unexpected behavior?

I will perform such tests too.

**Comment by eliemichel** [comment]
I uncommented (and modified a bit) a debug line in `TaskRun::refresh`, just before the timeout check.
This shows a task timing out (the Stop task message is in `TaskRun::stop`) but then being refreshed again.

**Comment by timurhai** [comment]
I refreshes every round anyway. On task stop it "m_stopTime = time( NULL)" stores stop time. Later, if stop time is not zero, it will not ask to stop. This prevents double stop.

**Comment by timurhai** [comment]
For now i see such solution:
1. Increase af_task_update_timeout (only this we can do right now)
2. Task stop timeout should configurable and increased too.
3. Server should treat that client started/stopped anything only when the request message data  is written to socket.
4. Monitor number of client accepting threads and opened sockets.
5. Monitor number messages delivery.
6. **Messages delivery should not use blocking i\o.** - lots of coding needed and most probably platform depended. At first it will be linux and, i think:
http://man7.org/linux/man-pages/man7/epoll.7.html
And may be such things needed for linux only, people who use windows an macosx as servers usually has no big farm.
Anyway lots of time for it neeeded.

**Comment by ultra-sonic** [comment]
please also see  my latest comment here #179

**Comment by eliemichel** [comment]
@ultra-sonic I use a `af_serve_tasks_speed` of 3 as well, and you made a good point;
@timurhai Why do you say that "does not influence messages (tasks) delivery"? Isn't job solving actually involved in task delivery in the sens that it triggers it? If there is only 3 renders contacted per second, could this still introduce a delay as long as 10s?

**Comment by timurhai** [comment]
Ah, yes, sorry.
You are right, af_serve_tasks_speed influence delivery!
Lowering this value will lover delivery delay too. As less messages needed to be send per second.

**Comment by eliemichel** [comment]
@timurhai I'm a little confused: how do you plan to use `epoll` for emitting? That would be really interesting for reception of incoming messages, instead of using a different thread for each client, though.

**Comment by timurhai** [comment]
Now epoll is much more needed for messages distribution.
And may be not needed at all for an incoming connections.
Incoming connections already processed simultaneously as each works with socket in own thread.
But messages distribution queue process socket writing one by one, so 1 "bad" client can freeze it for some time.
Anyway i can't say now i planning to use epoll for anything, i just started to read docs about non-blocking  sockets.

**Comment by timurhai** [comment]
btw
There is some other solution than non-blocking delivery.
No delivery at all !!!
Clients are connecting to server themselves periodically (afrender update resources, for example).
They can read tasks from server back.
( any web-server workflow )
This way server will no need to connect clients manually.
This way client does not need any socket listening.
So afrender can work behind any firewall/router, no local network needed.
This way our web browsers work.

What do you think about it?

**Comment by eliemichel** [comment]
Yeah I've heard that this is what [Tractor](https://renderman.pixar.com/view/pixars-tractor) do. And also [Flamenco](https://github.com/armadillica/flamenco).

**Comment by eliemichel** [comment]
@timurhai This may interest you: http://www.ulduzsoft.com/2014/01/select-poll-epoll-practical-difference-for-system-architects/

It recommends that for a cross-platform application monitoring less than 1000 sockets, `poll` is much easier because it is portable and you won't lose in terms of efficiency.

**Comment by eliemichel** [comment]
I have a first draft of "deliveryless" server.

In `RenderAf`, `ms_msg_queue`has been replaced by a non static `m_msg_queue` with the very simple and standard type `std::queue<af::Msg*>`.

Then, when this queue is not empty, instead of replying to `TRenderUpdate` with a `TRenderId`, it replies with a message popped from this queue.

It works, basically, but I did not test it intensively. But the problem now is that a task is submitted only when the render heartbeats, so there might be a delay before the task is actually sent. In my opinion, the `start_time` of `TaskRun` should be defined when the message is popped from the queue, not when it is pushed in it.

Problem is that I don't know how to gracefully access the instance of `TaskRun` corresponding to the `TTask` messages when the latter is sent (the payload is a `TaskExec`).

**Comment by timurhai** [comment]
Wait a bit, a holidays started in RUS:
http://www.timeanddate.com/holidays/russia/

**Comment by sebastianelsner** [comment]
There is a bit of progress here. After a lot of investigation we found that a "flush" (like sys.stdout.flush()) can take very long on our CentOS installation, blocking the system and thus blocking updates being send to the afserver.

**Comment by ultra-sonic** [comment]
strange....have been working with afanasy on centos6 for many years and
never got such massive amounts if errors. But that was with Afanasy 2.0.4
and earlier (1.7.0)...

**Comment by aghiles** [comment]
Timur, I haven't followed the development of your software intensively, but if you have problems with IO operations, I recommend solving them before switching to another architectures.  Usually, it just takes some careful coding around the IO operations.  Also, consider using UDP message dispatch instead of stream connections (using sendto & readfrom). There is also ways to know if a write will be blocking or not in TCP/IP but it requires some very careful work. Good luck!

**Comment by eliemichel** [comment]
@aghiles Which I/O problems are you talking about specifically?
@ultra-sonic Note that the problem that @sebastianelsner reported is likely to be specific to our infrastructure

**Comment by sebastianelsner** [comment]
@ultra-sonic: I think this specific to our setup and is due to heavy Disk IO, that comes from big files and using fscache (https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Storage_Administration_Guide/ch-fscache.html). If there is a lot in the RAM cache and it needs to be written to the disc/network ("flushed"), this can create a lot of overhead. The cache is normally 10-20% of the RAM, so the data CAN be big.
We were able to see flush times of 50seconds with just a very simple python application completely outside of afanasy.
If you are interested, here is a bit of background:
https://serverfault.com/questions/472498/flush-0n-processes-causing-massive-bottleneck
https://lonesysadmin.net/2013/12/22/better-linux-disk-caching-performance-vm-dirty_ratio/

**Comment by timurhai** [comment]
New server-client architecture where client does not listen any port, and so server does not connects clients manually, make such issues obsolete. But may be some new bugs will appear. Testing needed.
