### ISSUE TITLE
job task assigned to each render exactly once

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#182]
I have the case where I would like every render to reboot after the currently running tasks are done. This is just for maintenance and should **not** be part of a job (like a post cmd). So I am looking for a way to define a system job that goes to every render exactly once and is always the next task assigned. Is that possible right now?

**Comment by timurhai** [comment]
Right now it is not possible.
There should be a job with an array of tasks, each task for each render.
Like "hostmask", but for each task. Now "hostmask" parameter has only a job and a block.
There is one way right now - but it is ugly:
You can create a job for each render with a hostmask for its name.

**Comment by timurhai** [comment]
But hosts mask for each task can be a useful feature.
You can solve various maintenance objectives with it.
For example install some soft.

**Comment by sebastianelsner** [comment]
Yes, indeed.

**Comment by sebastianelsner** [comment]
Some additions here. The task would need to

a) be assigned to a render exclusively
b) block all other tasks from being assigned
c) wait for all other tasks to finish

this is a very special maintenance task, I think this connot be achieved by only adding the hostmask to a task.

**Comment by timurhai** [comment]
Hi.
Why not?
If you have 100 machines, you should create a job with 100 such tasks - each can run only on specified host.

**Comment by sebastianelsner** [comment]
The **assignment** can be achieved, that is true, but not the **exclusiveness** of a), b) or c).

**Comment by timurhai** [comment]
Hm.
So it should be some special job.
For example it can has some special flag that will mean some special behavior.
And we should define this behavior.

 - This will be a job with the number of tasks equals to machines it needed to run on.
 - Each task will have something like hostmask and can be launch only on a one specian machine.
( we can simple can name tasks as machine names and special job flag will make afserver run such tasks only if task name equals to a machine name )
 - Task can run only if afrender runs no other tasks, no matter how much free capacity it has  (may be an extra flag to tune it ON or OFF).
 - This job will waits all other jobs to complete (may be an extra flag to tune it ON or OFF).

What do you think?

**Comment by sebastianelsner** [comment]
I agree with all.

> This job will waits all other jobs to complete (may be an extra flag to tune it ON or OFF).

This basically never happens here. So for us this would be turned off always

I would add:
- The task can be FORCED as the next one to run on the render and renders do not accept any other task before it is run. This is most important for example if you NEED something to be installed before any new render.

**Comment by eliemichel** [comment]
What about using  a task whose capacity is exactly equal to the render's capacity, with a higher priority than any other job?
Exclusiveness will be ensured by the capacity mechanism, and forced assignment as the very next task  by the priority.

**Comment by timurhai** [comment]
Hi.
Just `maintenance` added, no `exclusiveness` issues yet.
Soon i'll try to install some soft on our farm and test it.

**Comment by sebastianelsner** [comment]
Nice, thanks!
