### ISSUE TITLE
afwatch jump scrolls on click

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#183]
We have the problem here, that afwatch is jumping to a totally different place with the scrollbar once you click on any item (in job and render view) I was able so solve this issue by removing the "setSpacing();" calls on the QListViews. Now the jumping has gone away, but the spacing between the items is gone, too. Do you see the same problem? We are on CentOS 6.6. with Qt 4.6. but I have been told this is the same with newer versions and other Linuxes.

**Comment by sebastianelsner** [comment]
Ok, seems I am able to solve this AND keep the spacing. I only had to add a "setAutoScroll(false);" to "ViewItems" class. It seems there is someting strange going on with the "drag move" events. From the docs:

> This property holds whether autoscrolling in drag move events is enabled.
> 
> If this property is set to true (the default), the QAbstractItemView automatically scrolls the contents of the view if the user drags within 16 pixels of the viewport edge. If the current item changes, then the view will scroll automatically to ensure that the current item is fully visible.
> 
> This property only works if the viewport accepts drops. Autoscroll is switched off by setting this property to false
>

**Comment by timurhai** [comment]
You can create a pull request if you fixed some bug!

**Comment by sebastianelsner** [comment]
yes, i will! Just out of interest: were you seeing the same?

**Comment by sebastianelsner** [comment]
fixed in  #186

**Comment by ultra-sonic** [comment]
what a fantastic fix! thx

**Comment by timurhai** [comment]
Me - no :)
But i heard about it sometimes.

**Comment by sebastianelsner** [comment]
I found thet the "fix" is causeing some weird pixel by pixel jumping now in renders views due to the auto-update of the list and the pixel scrolling. Will investigate further.
