### ISSUE TITLE
What is the difference between `TaskExec` and `TaskRun`

### ISSUE THREAD

**Issue by eliemichel** [CGRU/cgru#184]
I see the difference in the code, but I don't 100% understand what's the rational behind the separation of those two notions.

**Comment by timurhai** [comment]
TaskExec is a full task info. Afserver sends this class to afrender to execute, it can send it to gui (on a double-click) for user to get full info.
TaskExec is generated on demand. To store full info for each task will be much more heavy.
Job, block and user stores some info for all its tasks. For example all tasks of the same block has the same capacity and working directory.
It is a libafanasy class and use widely.

TashRun is a server class.
Afserver creates it for each task to handle its running (execution on a client side).
( there is no need such functionality and data storing, when a task is not running - TaskProgress class needed to store not running task state )

Its all useful not only for memory saving, afanasy does not "eats" much memory. It is useful for code functionality separating (simplifying, "encapsulating").

**Comment by eliemichel** [comment]
Ok, thanks!
