### ISSUE TITLE
Use singletons instead of full static classes

### ISSUE THREAD

**Issue by eliemichel** [CGRU/cgru#187]
All members of `RenderHost` are `static`, and this is typically a use for the [singletons pattern](https://en.wikipedia.org/wiki/Singleton_pattern).

Basically, instead of having many static members, members are all non-static, but the number of instances of the class is limited to 1. In the case of `RenderHost`, it would also avoid this weird pattern of allocating the object (`render = new RendorHost()`) and actually never use it directly. It will ensure that the constructor has been called when using the methods.

Well, and imho there is no need to actually constraint this class to have only one instance, but it's likely to be because I don't know the code enough.

edit: There is already something that looks like a singleton with the `ms_obj` member.

**Comment by timurhai** [comment]
I did not got, what benefits we will have if RenderHost will be a singleton?
Less code or what?
Any way, lots of work needed for other issues.
And i do not have an ability to spend all day long with afanasy, just several hours in a day and also not everyday (((
(about every 2 days.)
But if you really see how to improve the project - you are welcome! :)

**Comment by eliemichel** [comment]
Sure, I open many issues more as a way to share my though and write them down than as feature requests. ;)

**Comment by timurhai** [comment]
Hi.
I've got it )
Now i think that if class has data, especially when this data need to be properly initialized, better to use singleton.
But we can still use full static classes if we just want to join some functions together. In this case, class is just like namespace.

**Comment by eliemichel** [comment]
Then why not using a namespace? ^^

**Comment by timurhai** [comment]
Hi.
Sorry, i did not got you (

**Comment by eliemichel** [comment]
Was a reply to this:

> But we can still use full static classes if we just want to join some functions together. In this case, class is just like namespace.

**Comment by timurhai** [comment]
Ah) Got it.
I have a very small practice with singletons.
In RenderHost case, we just provide its pointer to a several functions, but what to do when we need to use it in lots of places?
Always get an instance at first?

**Comment by timurhai** [comment]
But i think better not to discuss what to use globally, but discuss exact class during develop.

**Comment by eliemichel** [comment]
You have a good snippet here: http://stackoverflow.com/a/1008289/1549389
There is basically a singale static method, `getInstance()`, that returns the only instance.

But in the case of `RenderHost`, I would even say that there is no need for it to be neither a Singleton nor full static. We could just in fact use a single instance without constraining it to be unique, exactly because - as you said - we already provide it to any function that needs it.

In my opinion a typical use for singleton is more something like a configuration object: you need only one, but it'd be a lot of overhead to provided it to any place of the code that needs it. So one uses the singleton trick to have some kind of global variable.

So, yeah, let's make `RenderHost` a standard class, even though we use it only once.
