### ISSUE TITLE
Keep connections alive as much as possible

### ISSUE THREAD

**Issue by eliemichel** [CGRU/cgru#188]
Instead of initiating a new tcp connection at each message, client could try to keep sockets opened.
I suggest to implement it at the level of `msgsendtoaddress`, keeping a look-up table mapping addresses to sockets. I guess that insertion in it has to be thread-safe.

@timurhai Do you think that there would be noticeable drawbacks if I would add this?

**Comment by timurhai** [comment]
It can be a good feature. Web servers and browsers try to work so.
Now afserver starts a new thread for each connection.
I reads (blocking) data, reacts on a message (may be blocking - client can as for a task output, for example, and server should read a file), writes (blocking) an answer back to client socket.
Than thread stops.
For keep-alive connections - thread should do this job in a cycle, reads client again, until client closes socket.
But in this case we will have number of threads ~ number of all clients.
Or we should change this architecture.

Any way and server and client code should have much changes.
Also, if we are going to make server that does not connects to clients itself, msgsendtoaddress will not be used by server.
https://github.com/CGRU/cgru/issues/181
 - There was an idea not to use delivery queue at all.

**Comment by eliemichel** [comment]
I did first experiments of server not connecting to the clients here:
https://github.com/eliemichel/cgru/tree/elie-deliveryless

The diff is pretty simple, the core of changes being here:
https://github.com/eliemichel/cgru/commit/947f46f806a575247f25d9e9b09a2e4cc21383b8

Basically, instead of replying to `TRenderUpdate` message with `TRenderId`, I use teh heartbeat to flush the queue of messages to be sent to the render.

It still needs improvement because only one message can be transmitted at each beat, but the basic concept works fine.

I am also working on a way to keep connections alive. I'll start with the most naive approach, keeping indeed one thread per client, but will then switch to a setup where the client thread is started only when there is incoming data on its socket, keeping only one polling thread when nothing happens.

**Comment by timurhai** [comment]
Server networking architecture much changed from this issue creation.
