### ISSUE TITLE
Legacy code

### ISSUE THREAD

**Issue by eliemichel** [CGRU/cgru#189]
`dlMutex.h:23`: Only mention of the class `DlConditionVariable`
Bellow: no implementation provided for the two methods. Is it intended?

**Comment by timurhai** [comment]
dl* classes was got from 3delight.
When aghiles (main render engine developer) was needed afrender and afserver with no Qt.
( before this the entire afanasy was on QString, QTCPSocket, QThread and so on )
Now Qt is used by afwatch only.
