### ISSUE TITLE
afwatch changes

### ISSUE THREAD

**Issue by timurhai** [CGRU/cgru#193]
- Default theme should have no images on buttons.
 - Light and dark color theme.
 - "Common" (default mode) should have "Error tasks: 2", "expert" more should have "2e" (or may be "err:2")
 - Left panel for some buttons, right panel for some info and parameters. Like WebGUI already has, but it is not finished there http://afanasy.info:51000/
 - Make afwatch architecture to work like WebGUI - browser does not listen any port, and receives changes from server on its "heartbeat" - same way as we want for afrenders for now. This way no local network needed, afwatch can work behind any router/firewall.

**Comment by ultra-sonic** [comment]
sounds great! thumbs up man!

**Comment by sebastianelsner** [comment]
Add shortcuts for commonly used actions. very easy to implement in the panel. 
Taking this further: the panel could be configurable, so the user can put the actions as buttons on the panel, that he needs most often.

**Comment by sebastianelsner** [comment]
Concerning 

> Make afwatch architecture to work like WebGUI

Does the web gui pull all jobs on every refresh? Or is there some kind of trick to reduce the dataflow? (sorry I am not good with javascript...)

**Comment by timurhai** [comment]
Hi.
Their architectures are close.
 - Monitor (any gui) registers on server.
 - Subscribe on events, for example `jobs_change`.
 - Receive changed jobs ids. (afserver connects to afwatch itself, browser asking for changes periodically, but soon afwatch will just ask too and listen no port )
 - Construct/refresh GUI items.

GUI paint architecture:
Browser (Javascript) constructs widget on any text, any gui "sub-item".
Advantages:
 - Much easy to create unique style (draw some error text red or bold).
 - Each gui item can react somehow on mouse press and any other event if needed.
 - Each gui item can have own tooltip.
Disadvantages:
 - Low speed. But if items count is not huge, speed is normal.
 - 10 000 tasks job can freeze or even hung browser.

AfWatch Qt creates 1 widget on 1 job (user, render, task).
Advantages:
 - About 100 times faster then web GUI. You can open job with 1 000 000 tasks.
Disadvantages:
 - Harder to code. Much more code than in browser javascript.


We can create an unique widget in Qt for any gui info too.
( job will be a widget can that have child widgets, one to draw name, other for priority and so on )
But code lines number will be increased.
Speed lowers according to widgets number.
 - better to use javascript for this method.


So, Qt and Web guis will always have an unique differences.

**Comment by timurhai** [comment]
Hi.
Left panel buttons with customizeable hotkeys already exist.
For now only several actions for jobs (now i making for renders and users).
You can look at actions:
https://github.com/CGRU/cgru/blob/master/afanasy/src/watch/listjobs.cpp#L88

What do you think?
What actions to add?
What default hotkeys do you expect?

**Comment by predat** [comment]
Perhaps it'll be more explicit and appealing to use icons for buttons !

I don't when to bother you but it could be interesting to have Renders, Renders statistics, Jobs and tasks on the same widget like a lots of render manager do (like Deadline).

**Comment by timurhai** [comment]
May later make an option to open renders and users in the same window.
Icons can be added to, but later, lots more important stuff to do.

**Comment by timurhai** [comment]
Afwatch already does not listens any port. And afrender too.
Both and Afwatch and WebGUI can listen job & task.
So now listening goes though afserver, later afrenders sent tasks outputs directly to afwatch open port.
Remember that huge output now affects afserver load.

**Comment by timurhai** [comment]
Not all desired changes will appear in 2.1.0
Modes ("common", "expert", ...) and right panel with parameters will be delayed as we focused on a new server architecture when clients are listening no port.

Good news!
Out studio is using 2.1.0 for 3 weeks, some small bugs were fixed, but globally everything seems to be stable.
And I thinks that it time to produce 2.1.0 release.

**Comment by predat** [comment]
And what about switching to qt5 ?

**Comment by timurhai** [comment]
It works.
Code compatible and with Qt4 and with Qt5.
Linux packages are built with system libs versions.
Windows release will be on Qt5 (Python3.4.4-Pide1.2.2(Qt4) and MSVC 2015).

**Comment by predat** [comment]
Have you seen the pyqt5 branch i create ? What do you think about it ?

**Comment by timurhai** [comment]
Yes, i see.
I think that it is a good idea to test pyqt5 and make a code compatible and with pyqt4 and with pyqt5.

**Comment by predat** [comment]
Ok so this need more work !
