### ISSUE TITLE
afwatch and webgui 

### ISSUE THREAD

**Issue by itpony** [CGRU/cgru#194]
Hi,
this is more of a question. Is it by design that something is accessible only in webgui and something only in afwatch? I get that "Listen" is only for afwatch, but is there way to delete renderer in it? I have seen that only in webgui.
Second example is display of ETA - it is visible only in webgui and not in afwatch.

**Comment by timurhai** [comment]
Hi.

Listed can only be in afwatch, in a GUI that can listen a port.
When you listen tasks, afrender sending child process(es) output directly into some socket.
So, listening does not go though afserver, afrender -> afwatch direct connection needed.
Browser (web gui) does not listen any port, afrender can't connect(send) anything to it directly.

Delete render from server store is accessible only in admin more.
Afwatch: "Delete Client" menuitem.
WebGUI: "DEL" button in "POW" buttons block.

ETA is the same in both GUIs. But some version can have ETA only in web gui. Almost all new GUI things appear in a web gui first (java-scripting is more easy than Qt programming). Then (after some tests and turning) GUI feature appears in afwatch. But some version can be created in hurry (due some heed feature or bug). So afwatch can miss something.

**Comment by itpony** [comment]
Hi, thanks for clarification.

I have question about listening - will it work with new afwatch? I mean after changes mentioned in #193. Or are those changes only for getting updates, but for listening the listening port will be opened?

I do not recall seeing anything about admin mode of afwatch in documentation - is it based only on username or is there some special way to run afwatch in admin mode? I am asking because from the same computer with the same username I am able to delete render node just in web ui.

And that ETA - I have 2.0.8 version downloaded from cgru.info (windows version) and I do not see it there. But I get that it may be different in new  version.

**Comment by timurhai** [comment]
AfWatch will listen port only on tasks listening, to task listening will require a local network.
May be in the feature we will think up some other tasks listening workflow, but for a near feature we have lots of other things to do.

Default admin password is `iddqd`.
This sequence should be typed just in a main window, no other item should be focused and grubs keyboard. For example you can type it just after gui launch, or after clicking on a "CGRU VERSION" label (that does not accepts any focus), or somewhere in a dialog border.

**Comment by timurhai** [comment]
Now and afwatch and web gui can listen task & job w\o port listening on gui and on afrender side.
