### ISSUE TITLE
Just Questions - Afstarter

### ISSUE THREAD

**Issue by IvonneBurgos** [CGRU/cgru#196]
Hi, I was reading about CGRU on the main page, I found the afstarter and I have a a few questions. It is an alternative to the plugins for the programs? I works with any version of the software? How could I use it instead of the plugins?. Thanks

**Comment by timurhai** [comment]
1. Yes. Afstarter is a simple stand-alone application, it does not communicate with a software with an opened scene. Plugin is a script (usually Python) that can query/set some specific parameters, it is a more flexible way to tune job/scene for render.
2. What software? What versions? Afstarter or plugin generate a command(s), send them to afserver, afserver sends commands to afrender(s) to launch.
3. Just send jobs within afstarter, not from software plugins.

**Comment by IvonneBurgos** [comment]
Hello thanks for your answer. Now I got an issue. I just install Afanasy on Ubuntu 14.04. The problem is  that I can't summit a job. 

On the message section of afstarter 

Could not open socket
127.0.0.1 : [Errno 111]  Connection refused
null

I try ./start.sh and it says

Invalid interface to SNW_SERVICE
Could not open socket
127.0.0.1 : [Errno 111]  Connection refused
Can´t listen 50999 port
