### ISSUE TITLE
Error in rendering on remote render node

### ISSUE THREAD

**Issue by akashtalole** [CGRU/cgru#198]
When render node is on local system and job submitted through local system then rendering works properly. But when render node is on remote server then avoid host error is arises when job is submitted through local system.

**Comment by itpony** [comment]
I had these problems too. My solution was to open afwatch, start listening to specific frame (the one that will be dispatched next) and then performing "Reset Error Hosts" - that way in listen windows you can see error messages - either binary not in PATH, wrong data folder or something other... Can you send us output from that listen?

**Comment by akashtalole** [comment]
HOSTNAME=www.mydomain.com
/opt/cgru/software_setup/bin/blender: line 5: /usr/bin/blender: No such file or directory

**Comment by akashtalole** [comment]
"either binary not in PATH" is the problem .How to resolve this problem?

**Comment by akashtalole** [comment]
i have centos 6 installed on my server.

**Comment by itpony** [comment]
Have you installed blender on the rendernode? If yes, is its binary located in PATH?
On my debian 8 machine, at least as I understand it, afanasy looks for blender in PATH... But it can be changed in /opt/cgru/software_setup/start_blender.sh

**Comment by akashtalole** [comment]
Nope i didn't  install blender on render nodes.

**Comment by itpony** [comment]
Just a question: How do you expect job management system to manage binaries?
You have to install all binaries used for rendering to all nodes....

**Comment by akashtalole** [comment]
ok. Then i have to run /opt/cgru/software_setup/start_blender.sh or setup__all.sh for all types of software.

**Comment by itpony** [comment]
My guess would be to run "yum install blender" (if blender is in repositories you use, I do not use centos so I have no idea if it is in default repositories or you have to add another one) on all nodes you want to use as blender rendernodes.

**Comment by akashtalole** [comment]
and for other software like AfterFX, Cinema 4D, etc. Need to install all of binaries.

**Comment by predat** [comment]
I don't think there is a repo for blender on Centos. You need to download blender static binary from http://blender.org. You can place the blender folder on a shared folder and mount this folder on all your render nodes. So it's easier to manage blender version.
 Then you create a 'locate_blender.sh' file in 'software_setup' with this in it:
```
export APP_DIR="/path/to/your/blender/folder"
export APP_EXE="${APP_DIR}/blender"
```

You can also use keeper to setup this file for you: in 'Software', 'Setup Soft', 'Blender' et then select blender binary file. If you have write access to 'sofware_setup', keeper will create 'locate_blender.sh'.

One more thing, this site is reserved for development purpose; if you have more questions related to CGRU/Afanasy configuration it's better to ask on http://rules.cgru.info/. Thank you.

**Comment by akashtalole** [comment]
Thanks a lot for helping.
