### ISSUE TITLE
Web Portal

### ISSUE THREAD

**Issue by IvonneBurgos** [CGRU/cgru#199]
Hello, I got a new question. My idea is to develop a web application that sends jobs to the server using CLI. Is there any restriction? Sorry if it is obvious.

**Comment by timurhai** [comment]
Hi.
No restrictions. You can develop anything you want )
From web browser best way to communicate with afserver using JSON, like web GUI does.

btw, how you want to communicate with afserver using CLI? Who will launch commands? Browser - can't (or you should write some browser extension, and ask each user to install it - and such extension will be huge security hole).

Rules already can do this.
http://rules.cgru.info/#/CG_PROJECT/SCENES/A_SCENE/A_SHOT_01
When artist creating dailies, or converting material, it sends a jobs to afserver.
You can look at its code.

ps
Afserver has JSON and only JSON protocol, any CLI, plugin, script just transfers command line arguments into JSON objects and send them to afserver.

**Comment by IvonneBurgos** [comment]
The idea is the following. There is a render farm that uses Backburner, but I find Afanasy better because of the software integration. What we want the app does: Authenticate user, upload the files, see the progress of render and download the render files. 

While I was reading the I see 

"afjob.py - CLI Job Interface
This is a python program. It constructs job from command line arguments and send to server."

So I thought I can send the arguments to afjob.py and it to the server, but it seems that works differently

**Comment by timurhai** [comment]
afjob.py - is python script to transfer command line arguments into Python API instruction.
Python API just helps to construct a valid JSON object and sends it to afserver.

 - Software integration?
Afanasy just launch commands. If you want to write your own web submitter, you should not be interested in any integration. You will construct commands yourself.
Or what do you call "software integration"?

**Comment by IvonneBurgos** [comment]
About "software integration" was what I found convenient of Afanasy because it works with many programs (Blender Cinema 3D MAX Maya the ones that I'm using). I yes that is the name a web submitter + monitor . I want artists just see a progress bar and when render is complete download the files.

**Comment by timurhai** [comment]
I just can say again:
`afanasy just run commands`
It does not case that command launches, max, maya, ffmpeg or zip. We even use it just to queue files copying. If you want to write "web submitter + monitor" you should be interested in API only. And compare render managers by API only. There is no "software integration" stage in you task.

You should compare Backburner and Afanasy APIs. Forget about "software integration". Your submitter is your own site (not a plugin for some soft)!

**Comment by IvonneBurgos** [comment]
Ok that is clear. I'm going to do that. I promise to return with some real problems questions. Thanks for your time :)
