### ISSUE TITLE
block task on one host, or task dependency

### ISSUE THREAD

**Issue by abuisine** [CGRU/cgru#201]
Hi there :)
Is there a way to setup a task so that it will be launched on the same host than another one ?
Typical use case is that I launch a two pass process, and the metadata files produced by pass 1 are pretty small files written at the end.
Cgru is so fast that another host tries to read the file to go on pass 2 but it is not yet accessible on the network file system I use.

Cheers

**Comment by timurhai** [comment]
Hi!
There is no such way/option/parameter.
But you can:
Make a command that run 2 other commands (tasks).
Or adjust task 1 that it will wait (sync) data transfer.
