### ISSUE TITLE
Use afcmd json send test.json

### ISSUE THREAD

**Issue by IvonneBurgos** [CGRU/cgru#202]
Hello

I was trying to send some request to afserver via afcmd but I couldnt. I used the example from here
https://github.com/CGRU/cgru/issues/71 but I got this
![image](https://cloud.githubusercontent.com/assets/7851291/14566740/64d48150-02f6-11e6-9ae5-789453fd3ca2.png)
I also send this 

![image](https://cloud.githubusercontent.com/assets/7851291/14566838/d52fd42c-02f6-11e6-9489-60e3bef4c5d9.png)

but there wasnt any output. Maybe I need something else?, Am I doing something wrong?

**Comment by timurhai** [comment]
Hi.
It seems that afcmd is broken in 2.0.8.
( in 2.1.0 it works with many internal changes )
You can use Python API to send jobs.
Such soft as Blender has Python and it is much simple to use its API then create JSON objects manually and run an external afcmd command to send it.
( also you can use Python API just to send own custom JSON objects to server )

ps 
afcmd was designed for developing/testing, try not to use it at all

**Comment by predat** [comment]
If you launch blender from keeper, you can also use the blender cgru add-on to send job to afanasy.

**Comment by IvonneBurgos** [comment]
I sent jobs from afstarter before and it works. I was trying with afcmd because I want to develop a client on owncloud. I'm going to check Python API as Timur said.
