### ISSUE TITLE
Error running start.cmd

### ISSUE THREAD

**Issue by DramaKing19** [CGRU/cgru#205]
On one of my computers when I try to run start.cmd, Windows returns a message saying that "\OpenLibraries\python was unexpected at this time." This was the only computer that I had installed Python 2.7 on, but uninstalling it and restarting my machine had no effect. Any ideas what I should do?

**Comment by timurhai** [comment]
Hi.
It seems that "\OpenLibraries\python" is the last part of some path with space(s).
You computer environment has paths with spaces!
Everything should work in any case, but for some reason that i can't say for now, it does not.
You can dig this problem deeper, open cmd.exe in cgru, call setup.cmd, see output.
Than you can comment lines in setup.cmd and see defference, also comment lines in other cmd files from can be called from setup.cmd. There can be some bug (may be not in cgru scripts) that can't hold a path with spaces.

BUT!
( just an advice )
DO NOT USE PATHS WITH SPACES! )))))))))
 - especially in environment variables -  this can be after you installed some soft in the path with spaces.
( let only windows and its native applications use spaces as they want )(
