### ISSUE TITLE
Python Qt5 support (PyQt5 and PySide2)

### ISSUE THREAD

**Issue by predat** [CGRU/cgru#207]
I've start a new branch named 'pyqt5' for converting all python scripts to use pyqt5 or pyside2.
I don't have test with pySide2 because i don't use it myself.
Anyway, this branch need some more tests.

**Comment by sebastianelsner** [comment]
I just came across this: https://github.com/mottosso/Qt.py ans was remembered of this issue. Since the above repo is targeted at vfx/graphics it would be a good idea to go with something that looks like it could become standard.

**Comment by timurhai** [comment]
Good idea!

**Comment by predat** [comment]
I've seen recently that you use Qt5.7 for cgru windows release.
How do you mix QT5 and Pyside 1.2.2 when using keeper?

**Comment by timurhai** [comment]
Keeper and AfWatch using differenet Qts.
AfWatch uses Qt that it was compiled with and dlls are provided in `cgru/dll` folder.
Keeper uses Qt that installed with PyQt (PySide) in Python that it running on.

**Comment by predat** [comment]
What prevents the switch to qt5 ?

**Comment by timurhai** [comment]
Nothing special ))
But at first i am planning to switch to
https://github.com/mottosso/Qt.py
But you can already to compile afwatch with Qt5 on any platform, code is ready.

**Comment by timurhai** [comment]
I think if we decided to switch on https://github.com/mottosso/Qt.py
We do not need a pyqt5 branch.

**Comment by timurhai** [comment]
And this file will be removed when the switch will be completed:
https://github.com/CGRU/cgru/blob/master/lib/python/cgrupyqt.py

**Comment by predat** [comment]
I'm agree with you but perhaps you can use the work done in this branch to move to Qt.py.

**Comment by timurhai** [comment]
Done, checking needed.
( for now, only during develop, i checked only on PySide and PyQt5 )

**Comment by timurhai** [comment]
I think we already can delete pyqt5 branch.
( i used it to see what/where i need to change )

**Comment by predat** [comment]
Ok. Let's go
