### ISSUE TITLE
Win-32 Render node support

### ISSUE THREAD

**Issue by ColinCreamer** [CGRU/cgru#209]
There appears to be no 32-bit version of this for windows. (only the 64 bit version is currently available for windows) It would be useful to have a 32-bit compile of the renderer so that old 32-bit windows systems can be easily used as render nodes for Afanasy.

**Comment by timurhai** [comment]
This means that it was not needed to developers and very few number of users needed it.
But this is an open project.
You are welcome to compile and support it.
