### ISSUE TITLE
Windows Issues

### ISSUE THREAD

**Issue by ClonedPuppy** [CGRU/cgru#21]
Hi again, I'm back ;)

This time I've really tried to look around in the documentation before I start pestering you with questions again.
I'm working on setting up the windows machines currently, and I'm having some problems starting keeper.

From a shell in windows, I have tried to run almost every setup_\* file I can find, I have a feeling it must be due to the python environment, but not sure. When I run start.cmd I get "\cgru\lib\python was unexpected at this time."

I have no idea what that means...

Peter.

**Comment by 3dcoat** [comment]
Hi, windows > where is the pathmapping file set location ?
Trying to config set output folder = no luck
_explorer "\\IP#\folder name"_ works fine with winkey+R
Tkx !
