### ISSUE TITLE
softimage problems

### ISSUE THREAD

**Issue by derOesi** [CGRU/cgru#211]
I've recently upgraded from 1.8.3 to 2.0.8, and have problems with afwatch... the original 2.0.8 xsi plugin didn't even work in Softimage (2012sap) because of a "unicode conversion not supported" message of python. SI unfortunately is stuck at python 2.x and won't ever support 3.x

now, I got it to work by using a modified version of the old 1.8.3 submitter.... the plugin itself, export, and rendering on afanasy seem to work without any problems, but when I try to "browse", or view the output in afwatch, I get this (attached).

every letter of the path gets read as separate "node/image" in this case: p:\sehsucht.otelo\.... written top to bottom.

the path in softimage is correct, including the padding as far I can tell... is there anything I could do to overcome this?

Thanks! (love cgru btw.!)

![incorrect_imagepath_parsing](https://cloud.githubusercontent.com/assets/19190255/15019027/7870c1f8-121c-11e6-80ac-6fc14fc0553e.jpg)

**Comment by timurhai** [comment]
Hi.
There was not any 1.8.3 version of CGRU ))
But from 2.0.0 Python API slightly changes, see `setFiles` function:
http://cgru.info/changes_log#release200

In you case now it thinks that you giving an array of files with a single character name.

btw,
There is 2.1.0 release already!
http://cgru.info/changes_log#release210

**Comment by derOesi** [comment]
sry just checked it, it was 1.7.0... don't know how i got to 1.8.3..

thanks for your help!! I got it to work... even as a non-programmer ;) now when i figure out how to use git ;) and after a bit of polish I still have to do, i could provide this pimped softimage submitter..
![afanasy_redshift_xsi_cropped](https://cloud.githubusercontent.com/assets/19190255/15022105/5a41e9a6-122a-11e6-93be-e70f6ad3e475.jpg)

have a nice one!
