### ISSUE TITLE
coding rules

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#212]
cgru's Python code mostly complies to PEP8, but a few issues are existing. For example that indentations are TABs instead of spaces. This makes pep8 testing tools go mad. Would you consider changing the coding rules to comply to PEP8 for Python only?

**Comment by timurhai** [comment]
Hi.
Yes, we can use only spaces in Python.
( i think that anyway it will be better as indentation means code block in it )

**Comment by sebastianelsner** [comment]
OK, thanks, I will convert code I come in contact with then.
