### ISSUE TITLE
Can't run Rules!

### ISSUE THREAD

**Issue by hradec** [CGRU/cgru#219]
I've setup latest apache and php on an up2date arch linux machine, and when I try to open RULES in a browser, I got this error:

#4 12:56:59.111: Error: Unexpected token < in JSON at position 0

chrome console shows that the error happened at common.js:60 file.

Not sure if this error is what's preventing RULES from showing up something, but so far I'm not able to make RULES show anything, not even the rules_root example projects. 

Is there any better documentation on how to properly setup RULES?

**Comment by timurhai** [comment]
Hi.
Unfortunately there is no detailed documentation, or some step-by-step setup example.
But it is a common web site: apache+php

https://github.com/CGRU/cgru/blob/master/rules/common.js#L60

I do not see anything special in that line.
But, if execution meets this line (block), browser can't parse json data from server.
Browser and server exchange data via json in rules.

Ensure that your php has a json module. See apache error log (some php execution error may be there).

**Comment by hradec** [comment]
I've figured out. The problem is that the jason parser was receiving an HTML error due to the fact apache couldn't write in the cgru folder because it was owned by another user. 

Changing the folder permission solved the problem, and RULES created a USERS folder. 

Now it's going a bit further, without any errors, but it still doesnt shows up the projects inside the rules_root.

this are the last few lines from the console log:

```
#14 16:50:27.456: Post: navig
#13 16:50:27.451: /cgru/rules_root/
#12 16:50:27.445: Dummy folder "" pushed: "/"
#11 16:50:27.444: Goto ""
#10 16:50:27.444: recv 4 (0) walk GO: {"walkdir":[{"denied":true,"folders":[],"files":[],"rufiles":[],"rules":{"rules.site.json":{"has_filesystem":true,"afanasy_enabled":true,"put":{"input":"RESULT\/JPG,RESULT\/DPX"}}}}]}
#9 16:50:27.442: recv 3 (1) playlist: {"error":"No such file rules\/playlist.json"}
#8 16:50:27.415: send 4 (2) walk GO: {"walkdir":["rules_root/"],"depth":0,"rufolder":".rules","showhidden":true,"rufiles":["rules","status"],"lookahead":["status"]}
#7 16:50:27.414: Navigating to: /
```

is there anything special that I need to setup to make the folders inside rules_root show up as projects?

**Comment by hradec** [comment]
ok... after snooping around, I was able to finally make RULES list folders by altering htaccessPath() funciton in rules.php. 

I've un-commented a "return true;" line, and now everything is working as expected. 

not sure why htaccessPath is denying access here... any idea?

**Comment by timurhai** [comment]
You should setup apache digest authentication.
This is an example of .htaccess file in cgru root folder:
https://github.com/CGRU/cgru/blob/master/htaccess_example

RULES reads/stores permissions in the same way as apache does. So if somebody hacks GUI (everybody can see it javascripts in this open source project), it will be still needed to hack server (https+digest).

**Comment by timurhai** [comment]
ps
But you can play with it in the local network without any authentication.

**Comment by hradec** [comment]
hoooo... I see! I tought it was not required, since htaccess_example has it
all commented out!

I'll do that right away and let you known how it goes!!

thank you so much for the help so far!! Really appreciate!!
