### ISSUE TITLE
afWatch, sorting jobs

### ISSUE THREAD

**Issue by derOesi** [CGRU/cgru#223]
I've an Issue with how afWatch displays/sorts the jobs at the moment... there are too many sort options, and non of them does what's really needed IMHO. but maybe I'm missing something"?"

this is how it looks like, sorted by Priority:
![af_sorting](https://cloud.githubusercontent.com/assets/19190255/15393679/fb853214-1dce-11e6-9779-36b396a56cc7.jpg)
as you can see, its pretty much a mess.... 

so I'd recommend a combination of:
* overall sort by priority, but finished jobs are always at the bottom of the list.
* sort by creation time inside the same priority
(which is basically how most/all others do it)

[
(this could be confusing :D but maybe it helps to show what I mean)
this new sort mode would have the active jobs always on top, followed by jobs with the same priority sorted by their creationdate, followed by lower priorities sorted by their creationdate, followed by finished jobs sorted by their finish date, and therefor ending with the oldest finished job.
]

this would improve the readability of longer lists quite a lot... 
just my 0.02c ;)

--stephan

**Comment by timurhai** [comment]
Ok)
Later we can add the second sorting parameter.
(now it is always name https://github.com/CGRU/cgru/blob/master/afanasy/src/watch/itemnode.cpp#L50)

**Comment by derOesi** [comment]
sounds great! this would certainly help/improve the experience.

**Comment by timurhai** [comment]
Done. Checking needed.
