### ISSUE TITLE
Handle escape sequences in task output

### ISSUE THREAD

**Issue by eliemichel** [CGRU/cgru#224]
When a task uses escape sequences in task output, for coloring for instance, it makes it really hard to read it in the Task>*RightClick*>Output view.

It may be fastidious to effectively display colors since termcap/terminfo stuff is a real mess, but at least hiding the escape sequences should be manageable.

**Comment by timurhai** [comment]
Yes, better to remove them.

btw
AfWatch can import python module too, and there can be an extra function for each service - `escape2html` - to translate terminal stuff to html tags, and qt can accept html style tags (and least they say so, and i thing that such common directives as bold and color they are really accept)
 - but this is more complex work, we can delay it for less busy times ))

**Comment by eliemichel** [comment]
The `escape2html` is a nice solution.

This regexp could be used to just remove sequences: http://stackoverflow.com/a/33925425/1549389

And if one needs more, there are some Python "ANSI escape sequences to HTML" libs around, but no need to ship one with afanasy imho.

**Comment by timurhai** [comment]
I am just thinking...
An output should be changed on render side, or on GUI side?

Render side advantages:
- Any GUI (watch, web, may be other). Will see already good output. There will be no need to translate data in different programs and languages.
- More simple: `parser.do` Python function can do this work.

GUI side advantages:
- Server will store an original output. GUI can show it as needed.

What do you think?

**Comment by eliemichel** [comment]
I am definitely in favor of the GUI side. Different GUIs might have different needs of escaping (just remove escape sequences, convert them to HTML, etc.) so it's more logical to let them do it. And it's better imho to keep the original output on the server.

**Comment by timurhai** [comment]
Ok!

**Comment by timurhai** [comment]
Just started to implement, and one more issue appeared:
Lets name this convert function `toHTML` instead of `escape2html`.
As we can highlight any other needed details in this function.
( for example all lines that contain `error` string can be red )
Not just escape sequences.

**Comment by timurhai** [comment]
And in Python...
service.toHTML can call parser.toHTML, as it can already parse lines for an errors, warnings, percentage.

**Comment by timurhai** [comment]
It seems that af::MCTaskOuput class needed.
Now we can't just send some "data" to GUI to show.
GUI should know what "data" it is, and if it is task output, it should know service and parser.
Later, as we are going to make GUI task window, we definitely will not be satisfied, if server send some "data", we definitely will need to know, that it is task output, and from what concrete task (all ids should be sent too).
So new class and new message type is needed in any case.
( i am already in progress )

**Comment by eliemichel** [comment]
Ok it makes sense. There was a `MCTaskOutput` before, what happened to it?
Also, in which case there is a need for a `MC*` class, and in which case it is better to use some `af::Foo::readwrite()`?

**Comment by timurhai** [comment]
Yes, later it was, but it was used for listening:
https://github.com/CGRU/cgru/blob/27f2513617ef6c1e1cf0a239f318158f9dd564dd/afanasy/src/render/taskprocess.cpp#L359
Now listening procedure goes through `renderupdate` and `monitorevents`.
This classes collect all various info information exchange during heartbeats.

**Comment by timurhai** [comment]
o, just noticed your second question )
MC* just to gather classes by naming.
Any `Af` can readwrite and designed to use for data exchange.
MC* classes designed for data exchange only, on other hand, some af::Render has more functions and meaning for the system.
But this difference is blurry, some classes are in the "middle" and can be placed anywhere ( as developer wants :) )

**Comment by timurhai** [comment]
`MCTaskOutput` is a good example of an MC* class - it will have no meaning (functions) for system work, just data exchange.

**Comment by eliemichel** [comment]
Ok, thanks for the explanation! :)

**Comment by timurhai** [comment]
Done! Checking needed...

This function is designed to be re-implemented in child classes for special highlighting:
https://github.com/CGRU/cgru/blob/master/afanasy/python/parsers/parser.py#L210

Here is some base highlighting for any service:
https://github.com/CGRU/cgru/blob/master/afanasy/python/parsers/parser.py#L187
It calls common `parse` function to highlight errors, warnings and other things that `parse` does.
Also this function is an example what to do in `tagHTML` function.

I think that some base escape sequences replacements can be done in `toHTMLline` to use it in any service. And may be special ( by service ) implementation (`tagHTML`) is not needed at all.
