### ISSUE TITLE
Afserver Error

### ISSUE THREAD

**Issue by IvonneBurgos** [CGRU/cgru#227]
Hello 
I’m using version 2.1.0 since maybe two days after release. 

So I was working with afanasy perfectly but today something weird happened.

Until now If I start keeper I could send jobs and everything was fine. But today keeper didn't start and if I want to start it from console it send me an error 
"Socket could not be open " or something like. 
I tried everything but nothing worked so I uninstalled and installed again afanasy. 
At the end of all I source ./setup.sh and then afserver and it send me this
```
master@master:/opt/cgru$ afserver
Compilation date = 'May  6 2016 00:54:37'
CGRU version = '2.1.0'
Afanasy build revision = '4c60391d6b14fb54ea98984133f234046c731fc0'
Python version = '2.7.6'
GCC version = '4.8.4'
RLIMIT_NOFILE: Files descriptors limit: 1024
RLIMIT_NPROC: Processes (threads) limit: 31349
Database connection "AFDB_update" is not working.
AFERROR: AFDB_upTables: Database connect failed: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
```

It worked but I dont want to source each time I want to use Afanasy. I was fine until friday, last day I worked with it.

**Comment by predat** [comment]
Duplicate
