### ISSUE TITLE
Provide access to task actions from the task dialog

### ISSUE THREAD

**Issue by eliemichel** [CGRU/cgru#231]
Currently, when one wants to perform an action on a task, such as restarting it, watching its output or its log, etc. one needs to go through the task context menu in the job dialog.

It is very confusing, from a UX point of view, not to be able to perform _task actions_ from the _task dialog_.

One practical issue, is that know let's say I want to be able, from the render list, to perform task actions on "the task currently being ran on this very render". One solution would be to copy every entries of the task context menu in the render context menu, but it would duplicate a lot of things and will be a heck to maintain.

So a logical mean would be to just have a "Open Current Task" entry in render's context menu, that would open the task dialog and let the user do anything on the task from here.

**Comment by timurhai** [comment]
Hi.
How is going with this issue?
And what is your goal?

Now i am thinking about such "Task" window too :) :
A special "Task" window will be raised on a task double click or from render item RMB.
This window will have such tabs as:
Exec * Log * Output * Error Hosts * Listen

Have you wrote something?
Or i think now i have some time to do it :)

**Comment by eliemichel** [comment]
I was not sure you agreed on this, which is why I did #237 instead. ;)
But what you describe now matches my idea!

**Comment by timurhai** [comment]
Ok. I'll start to do it!

**Comment by timurhai** [comment]
At first i did not expect so much changes in the code for such feature.
And this is not finished.

On the second stage i will remove/replace old code to switch to work with a task window only.
 - Renders list should just raise task window.
 - Task GUI item RMB menu should be reduced, all requests (output, log, listen, error hosts) should be removed too.

And later i am going to think up some new way to request task outputs from elder starts ( now task window can't, and there will be no old way from a task RMB menu )

**Comment by timurhai** [comment]
It is done.
Try to use it.
Output session can be chosen from a menu, again (if there is more than 1 starts).
 - may be something should be changed.

**Comment by eliemichel** [comment]
It's great! :)

**Comment by timurhai** [comment]
Skip and restart buttons are already exits.

**Comment by eliemichel** [comment]
Indeed, I had not pulled enough. ;) So it's just great now. ^^
I will comment here if I have suggestions (or anybody else) but I think we can close the issue anyway.

**Comment by timurhai** [comment]
Lets reopen issue, or i can forget to do the same for web gui ))
