### ISSUE TITLE
Exclusive service

### ISSUE THREAD

**Issue by eliemichel** [CGRU/cgru#241]
_(This is more a question than an issue)_

I have a set of tasks, say of a service `S`, in different jobs, which must not run at the same time. I don't care about the order in which they are ran, so it is not really a dependency, but I need them to be exclusive.

I see several ways to achieve this (somehow in order from the worst to the best):

 * Implementing in the task itself a lock system. Problem is that while the task will wait for its peers to finish, it will block some of the machine's capacity, so I should put the capacity to 0 or something, but it always ends up being dirty.

 * Submitting these tasks in a separate job (alone, instead of being other tasks of another service), and introducing a dependency to all the jobs with tasks of service `S` already present in the queue when submitting it. Works, but makes a lot of jobs: one for the tasks of the original job to run before the block of service `S`, one for this service, depending on the previous job and other `S` blocks, and one with the tasks to run after the block of service `S`. So it multiplies by 3, and loses the link between blocks.

 * Using a unique job of service `S`, and editing it to add the new `S` block every time I submit a job with such one. This spawns less jobs than the previous idea, but requires to maintain and edit this unique job.

 * Using a host mask for the `S` block constraining them to run all on the same machine, and putting a high capacity to limit to one the number of blocks running at the same time.

 * Adding a feature to afanasy to make a service _exclusive_, so that the solver always makes sure that only one block of this service runs at the same time.

 * Using a magic feature that I don't know yet and does exactly this. :D

**Comment by sebastianelsner** [comment]
Make a service, that has a max client limit of 1. So there will always just run ONE task of this service.

**Comment by timurhai** [comment]
Hi.
Also see service limits, that can be used for licences limits.
They can limits hosts number and total launched number.

**Comment by eliemichel** [comment]
Perfect :)
