### ISSUE TITLE
`ListJobTasks` is much slower than it used to be

### ISSUE THREAD

**Issue by eliemichel** [CGRU/cgru#243]
Openning a job window, with the list of tasks in this job, takes much longer than in 2.0.8.
The difference is felt only for non numeric blocks I think, but here it takes me several seconds to open a job with only 50 tasks, though not numeric. The size of the `TJob` message is 18kB.

**Comment by timurhai** [comment]
On Afanasy from master, I just opened 100 000 tasks for about 1 second.

**Comment by eliemichel** [comment]
Non numeric tasks? I'll investigate, it may be my particular job.

**Comment by timurhai** [comment]
May be, just may be somehow, when Item and ItemJobTasks were `Q_OBJECT`s.
But since task got its own window for info and manipulation, they are not `Q_OBJECT`s now.

**Comment by eliemichel** [comment]
It's a bit faster. I think that now the only limitation is that there are indeed a lot of data to transfer for a big block with hand-made tasks, since each task has its own definition. It's not to be considered as a bug any more.

Plus, there is always a way to make it numeric by putting all the actual commands in a text file and making each task check out in this file which task it must run.
