### ISSUE TITLE
Sort RENDERS by current tasks runtime

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#244]
Hi guys,

would it be possible to add a sorting option to the RENDERS view that lists renders by the duration of the current job. I always find myself checking for possible farm-blockers and it would be much easier if there would be such an option!

thanks in advance!
Oli

**Comment by timurhai** [comment]
Ok)

**Comment by sebastianelsner** [comment]
How do you handle renders with multiple tasks?

**Comment by eliemichel** [comment]
Since the final goal is to find farm-blocker jobs, I suggest that we sort by `max({duration(t) for t on render})`. :)

**Comment by timurhai** [comment]
Yes. Most elder task should be compared.

**Comment by timurhai** [comment]
Was easy to implement. It is called "Running".
btw, if you have some better ideas how name this parameter by one word you are welcome

**Comment by ultra-sonic** [comment]
Awesome!

I would call it "task runtime"...
