### ISSUE TITLE
render random frames

### ISSUE THREAD

**Issue by cg-cnu** [CGRU/cgru#245]
I tried looking around but couldn't find it. 
Is there any way to render set of _missing_ **random frames** and **frame ranges**?
eg; 2, 4, 10-20, 25, 26

**Comment by timurhai** [comment]
Hi.
 - You can send new jobs - a job for each continuous frame range.
 - Create a job with non-numeric block for all needed frames.
 - Use http://cgru.info/afanasy/job#block_flag_checkrenderedfiles
 - Just restart this frames, if you have a previous job.

**Comment by cg-cnu** [comment]
hey, 

* Yes, that's a valid suggestion. 
* I didn't got **non-numeric block**. Can you provide more details.
* I will have a look at the **checkrenderedfiles**. But I guess, its just to validate the render sequence, won't resubmit the frames. 
* Yes, that's an option, I can restart the task but most of the times, I will have a fpt of 10 and the error frames are 5 . Restarting it will result in rerunning all the 10 frames? It would be awesome if cgru can figure that out and render only the missing ones. 

Correct me if am wrong and any explanation would be helpful. Thanks!

**Comment by timurhai** [comment]
You can resubmit a job with frames per task = 1 and `checkrenderedfiles` flag enabled.
But remember, block should have correct `files` parameter (to let afrender know a file to check).

**Comment by cg-cnu** [comment]
Hey sorry for the delay in response, 
So, looked around a bit and ``skipExistingFiles`` is what am looking for.
I guess there is no gui (checkbox) I tick when submitting the job ?
I tried adding ``block.checkRenderedFiles()`` in afjob.py in ``for cmd in cmds:`` loop. 

But its skipping all the frames... 
Let me know if am doing anything wrong...

**Comment by timurhai** [comment]
Read tasks logs and output.

**Comment by cg-cnu** [comment]
Hey, 

I redered 10 frames with default cgru 2.1.0 and deleted the job.
Added ``block.skipExistingFiles()`` and ran the same job. 

Its skipped all the frames....

Here is the afrender log...

```
Skipping: [maya_arnold:1000] salapati: test.ma-1[maya_arnold][frame 11]
Service: Task file(s) exits.
Skipping: [maya_arnold:1000] salapati: test.ma-1[maya_arnold][frame 12]
Service: Task file(s) exits.
Skipping: [maya_arnold:1000] salapati: test.ma-1[maya_arnold][frame 13]
Service: Task file(s) exits.
Skipping: [maya_arnold:1000] salapati: test.ma-1[maya_arnold][frame 14]
Service: Task file(s) exits.
```

I was just wondering...  if we are doing rendering with multiple passes (which am doing) how will it be able to figure out if the file exists as we can't specify all the passes ? In my case i tried specifying the **output images:** path to the images folder as well as one of the render pass. 

Let me know if any additional info needed.

**Comment by timurhai** [comment]
Hi.
Now service does this:
https://github.com/CGRU/cgru/blob/master/afanasy/python/services/service.py#L60
Lets talk about what is wrong with that check, and how we can improve it.
We can specify all the passes, as functions:
http://cgru.info/afanasy/job#block_files
http://cgru.info/afanasy/job#task_files
Takes an array of files, so you can specify all the passes.

**Comment by cg-cnu** [comment]
Just to test out I did a render with out render passes and its also failing. 

Ok, regarding the code. 
I was trying to modify and see actually what's the ``vlaue of self.taskInfo['files'])`` is.
How do you print the value to see? I tried doing ``self.log(vlaue of self.taskInfo['files']) )`` but it didn't worked out.

Thanks for your help and answering all my questions :)
Am not that verse with afanasy code base. So, You have to help me out a bit before I can figure out stuff and fix at least small things. :)

**Comment by cg-cnu** [comment]
Sorry for the noob question...
you mean ./start.sh.. ?
which is logging submit job's output but not afservice.
And do i need to restart afrender/afserver after file changes?

**Comment by timurhai** [comment]
stop afrender service
go to cgru folder

   source ./setup.sh`
   afrender`

You need to restart afrender each time you modify service.py or parser.py.

**Comment by cg-cnu** [comment]
Cool!  Am able to debug now..  I am playing with it.. :)

**Comment by cg-cnu** [comment]
I guess ``images = os.path.normpath(output) `` is missing [here](https://github.com/CGRU/cgru/blob/master/afanasy/python/afjob.py#L619 ) 

set ``block.skipExistingFiles()`` over [here](https://github.com/CGRU/cgru/blob/master/afanasy/python/afjob.py#L834)

Fixed the issue of creating folders for each frame, which I raised an issue here #249 
And... single frame renders with skip existing frames is working fine.

On to checking, how to do for multiple passes... :)

**Comment by cg-cnu** [comment]
Waiting for confirmation on #249 

We are adding **images** to **wdir**  [here](https://github.com/CGRU/cgru/blob/master/afanasy/python/services/service.py#L62)
my guess is to add  **output** instead of **wdir**.

**Comment by timurhai** [comment]
Hi.
You should make changes, check it, and create a pull request.
Also.
`block.skipExistingFiles()` should be an option. It is a common situation to er-render the same files, so skipping should be.
here https://github.com/CGRU/cgru/blob/master/afanasy/python/services/service.py#L62
We just adding a filename to wdir, as filename can be relative. This is not related to afstarter, afjob, maya and so on. This is an important system file, that works with various other things. I do not want to say that there can't be a bug. But remember - all submission scripts/dialog/plugins - can be just called an "examples" to TDs to create their own. They can have bugs, most because that any soft is changing, progressing, and submissions are often late.

**Comment by cg-cnu** [comment]
Ok, I work on that and create a pull request. Thanks :)

**Comment by cg-cnu** [comment]
I think am close, I need one last piece of info.
What is the best way to pass the **'-output'** value available in **afjob** to service.
I want **taskInfo['output']** to be available [here](https://github.com/CGRU/cgru/blob/master/afanasy/python/services/service.py#L62).
I tried looking around, I couldn't find a place where **service** is initialized with **taskInfo**.

**Comment by eliemichel** [comment]
Chech out [`libafanasy/service.cpp`](https://github.com/CGRU/cgru/blob/master/afanasy/src/libafanasy/service.cpp#L108)!
`taskInfo` is used to communicate info from C++ code to Python.

**Comment by cg-cnu** [comment]
Hey, thank. But, I don't think I can mess around with c++ code now.
Is there any other way ?

**Comment by timurhai** [comment]
Hi.
I can't get exactly what are you want Afanasy to do.
You should say more clean:
 - I do this ...
 - Expecting this ...
 - But Afanasy does this ...
 - Is it a bug, or it designed to do so?
 - If it is a bug, lets fix it
 - If not, may be add some option, as I very need another behavior.

And try not to mix more that 1 issue. If you want afrender to skip frames, lets task about it.
If AfStarter or afjob.by or may be Maya creates and renders in not needed folder, it is another issue.
If AfStarter or afjob.by can't pass correct ['files'] array to Afanasy, it is the third issue.

**Comment by cg-cnu** [comment]
Hey, Sorry for the confusion. I guess this thread is already mixed up with multiple issues. I will break down the problem and create new issues.
Thanks.
