### ISSUE TITLE
Deleted old jobs coming up online

### ISSUE THREAD

**Issue by cg-cnu** [CGRU/cgru#246]
* Run few jobs
* Delete jobs from the web UI

Later...
*  restart afanasy server...

All the old deleted jobs are coming up online... and some of them start rendering.

what is the proper way to delete the job ?

**Comment by timurhai** [comment]
Hi.
What is the version?
Strange situation. But, for example:
If you start afserver service by one user, this user will write store. Send jobs. The user will write them to store folder. Restart afserver by other user, that can only read store (not write). Server will read jobs. Than, you delete jobs from GUI. Server will delete them from "memory" (and GUI), but can't delete them folders in the store. Then you restart afserver. And it will read all jobs from store.

**Comment by cg-cnu** [comment]
hey, 

I am using version 2.1.0
Thanks for the explanaion, it makes sense. 
I was launching afserver and afrender with different user logins and that created a bit of permission issues. Now, I launched all the services with render login. And for the old jobs, I checked the `` /var/tmp/afanasy/jobs/0 `` folders and there are files with different user names. I deleted them manually.
Now all fixed. 

But, as you said i checked the afserver log and found this error when am trying to delete from the web ui
``AFERROR: af::removeDir: Can't delete file: /var/tmp/afanasy/jobs/0/3.FurAndBall.hip-1/tasks Is a directory`` 

``AFERROR: af::removeDir: Can't delete file: /var/tmp/afanasy/jobs/0/16.titanBRightHand.ma/tasks Is a directory
``

If you need any other info to debug let me know..

**Comment by timurhai** [comment]
So, after permissions issue fix, it still does not delete jobs from store, and all deleted jobs return after afserver restart?

**Comment by cg-cnu** [comment]
yes... 
One thing I have noticed is... the folders inside **/var/tmp/afanasy/jobs/0** are written in the old user name. So, I went ahead and changed the permissions on the folders manually to the user **render** and restarted the afserver and clients with the same user. 

Still its throwing the same error.

**Comment by timurhai** [comment]
It is just flowing the error, or restores jobs after restart?

**Comment by cg-cnu** [comment]
It restores all the jobs.

**Comment by timurhai** [comment]
It seems that `af::removeDir` does not correctly check whether an item is a file or folder.
And some platform it can cause a bug.
What is a platform? ( is see that it is not windows, as folder starts with /var/ but what Linux?)

**Comment by cg-cnu** [comment]
its `CentOs 7 3.10.0-229.1.2.el7.x86_64`

**Comment by timurhai** [comment]
Just tried on CentOS7 - the same. But i will fix it!

**Comment by timurhai** [comment]
Yes, default CentOS 7 file-system type `xfs` was not supported in `af::removeDir`.
Now it does.

**Comment by cg-cnu** [comment]
That's quick! Awesome!! :+1:
