### ISSUE TITLE
afanasy "Farm Summary"

### ISSUE THREAD

**Issue by cg-cnu** [CGRU/cgru#247]
Is it possible to get a summary of what is happening right now on the whole farm in one location 

# Nodes:
* **Total**: Count of machines registered in afanasy database.
* **Rendering**: Count of machines rendering.
* **Nimby**: number of Machines in Nimby.
* **Waiting**: Machines waiting for task.
* **Offline**: Number of offline machines.
* **Error**:  Machines throwing errors.

# Jobs:
* **Total**: Number of jobs registered in afanasy database.
* **Active**: Count of jobs currently running.
* **Paused**: Jobs on pause.

# Time:
* **Total**: Total time left to finish off all the jobs

and on and on... and can be extended to user also

I can see that all this info is already available, but in different places...
Eg: to get the number of nodes on Nimby and number of nodes rendering, I have to go and manually count them. Would be really helpful to get a overall picture of the farm, especially if you are rendering a lot of jobs.

I guess, I made my point clear. Would like to know your opinion...

**Comment by timurhai** [comment]
There is some counts in the afwatch window title, but they are not so informative.
Some info i even do not know how to calculate - "Total time left to finish off all the jobs".
This can be based only on some statistics, and anyway will be very-very approx.

But the entire idea (feature) can be useful - have some 1 place with all brief farm info.
Lets keep this issue.

**Comment by cg-cnu** [comment]
That's awesome! :+1: 

Yes, its not the accuracy of the time but the over all estimation. 
Anyway, am just using that as an example to explain the summary concept. 
We can basically start with the nodes and jobs info.

**Comment by ultra-sonic** [comment]
That brings up a little "bug" that I wanted to post a long time ago that has to do with the current way the ETA is calculated...there is a more accurate way and maybe I can send a PR on this....

**Comment by eliemichel** [comment]
If you are ready to use the API, it should provide everything you need. Here is a sample of a summary generation script I use:
https://gist.github.com/eliemichel/7880c101557297beeccda05978aeb278

**Comment by cg-cnu** [comment]
Thanks, am just starting to understand afanasy. I will give it a shot.
