### ISSUE TITLE
@###@ pattern creating folder

### ISSUE THREAD

**Issue by cg-cnu** [CGRU/cgru#249]
Versoin: 2.1.0

Issue:

In afanasy starter submit a maya job with output images with pattern...
``/path/to/folder/fileName.@####@.tif``
Previously versions I remember it creating files with the padding given...
Now Its creating folder for each frame like this....

```
/path/to/folder/fileName.0001.tif/fileName.0001.tif
/path/to/folder/fileName.0002.tif/fileName.0002.tif
/path/to/folder/fileName.0003.tif/fileName.0003.tif
```

instead of this...
```
/path/to/folder/fileName.0001.tif
/path/to/folder/fileName.0002.tif
/path/to/folder/fileName.0003.tif
```

My guess -rd in command should be ``/path/to/folder/`` instead of ``/path/to/folder/fileName.0001.tif``

```
if output != '':
	cmd += ' -rd "%s"' % os.path.dirname( os.path.normpath(output) )
```
fixes that.

**Comment by cg-cnu** [comment]
Ok, my bad...

The above fix won't work if you just gave the path with out the frame pattern.
As it strips out the last folder. Need a better way of checking.

**Comment by cg-cnu** [comment]
Ok, sorry for the false alarm. 

I guess, we are not supposed to give the **@###@** pattern in the output images path.
It has to be given in **Afstarter: Advanced Tab > Preview**.

We can close this issue, but just want some one to conform that its true.

**Comment by timurhai** [comment]
Hi.
I do not have Maya (and most other soft) by hand.
AfStarter is just a dialog (Python+PyQt) that constucts a command for `afjob.py`.
`afjob.py` is a Python script too. It parses command its command line arguments and constructs an afanasy jobs using its PythonAPI. Job has a commands for afrender to launch.
You should specify (find) more concrete what step is bad.
You even can fix it if you are know Python.
