### ISSUE TITLE
afwatch lost ability to send text messages to other monitors

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#250]
... happened in: 091fa070cc708c5143d3d58397415a267ff48616

**Comment by timurhai** [comment]
Hi.
Yes it happen then it finished to listen a port.
Not only this message type became obsolete.
Such  things now goes via "monitor events", and for now there is no such event.
I was just in a hurry to make all functionality for a system work, and forgot about it.
But it not a big deal to add such event.
