### ISSUE TITLE
Windows - thumbnail not rendering or displaying on browser gui

### ISSUE THREAD

**Issue by tcheng00** [CGRU/cgru#253]
Hi, 

I can't seem to get the thumbnail to generate from the web interface.  Any idea what I need to do?  
Running windows 10, Blender 2.77a, ran afserver manually, and use keeper to launch local render.

Thanks.

**Comment by timurhai** [comment]
What is the version?
Thumbnails are generated by afrender.
What is afrender application output? Does it really generate thumbnails?
If thumbnails are generated, does AfWatch shows it?

**Comment by tcheng00** [comment]
Sorry about that.  I corrected the title.  I just installed cgru 2.1.0.    I meant to say that the thumbnails are not being rendered and therefore not displayed on the gui either.   From my understanding of the documentation, it should start generating thumbnails after the render task is complete, but that doesn't seem to happen.  I'm running windows so maybe it only works on Linux for now?  

I'm also unclear if I need to set any environmental variables on Windows or does keeper set it up for me.  Thanks.

**Comment by timurhai** [comment]
You need to setup environment manually, only you want to launch something manually (from some custom script, for example).
Are you sure that you have correct ['files'] array?
http://cgru.info/afanasy/job#block_files
Or your parser should parse files to make render know output images.
http://cgru.info/afanasy/render#thumbnails

**Comment by tcheng00** [comment]
I got the environment variable setup.  Thanks.  

I'm not sure if I have the correct array, but I'm only using the default settings.  I haven't touch the configuration except to setup the exe file for Blender and set the server host name.  I'll try to read up more on the documentation, but there seems to be less info for the window OS.  Thanks.

**Comment by skrmn** [comment]
Hi guys!
I have the same issue. CGRU 2.1.0. Default setup. Config almost untouched.
Thumbnails are generated, I could see them in place - I mean files.
But however browser shows nothing, and I got log from afanasy server about some errors:
<img width="668" alt="screen shot 2016-06-21 at 19 05 05" src="https://cloud.githubusercontent.com/assets/20071630/16238994/1ecad5b6-37e3-11e6-9d82-2784e2405588.png">

Please tell me where to check!

Thanks!

**Comment by timurhai** [comment]
Hi.
Does afwatch show thumbnails?

**Comment by tcheng00** [comment]
Hi,

afwatch also does not show thumbnails.  Thanks.



On 6/21/2016 1:13 PM, Timur Hairulin wrote:

Hi.
Does afwatch show thumbnails?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/CGRU/cgru/issues/253#issuecomment-227507704>, or mute the thread<https://github.com/notifications/unsubscribe/AFcJd9hTmSXYXAPstZdSWENEsx8IdqGuks5qOBungaJpZM4I6Bkb>.


[https://ipmcdn.avast.com/images/2016/icons/icon-envelope-tick-round-orange_184x116-v1.png]<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=emailclient&utm_term=icon>      Virus-free. www.avast.com<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=emailclient&utm_term=link>

**Comment by skrmn** [comment]
Hi! No, unfortunately... Afanasy is on Windows7, clients on Win7/Win10/Mac...

**Comment by skrmn** [comment]
Small update. 
I can see thumbnails on Mac OSX in afwatch (it was a manual build from sources on 10.11.5 with a pain )))
But on windows machines and in browser - no.
May be this helps to find an issue.

**Comment by timurhai** [comment]
Hi. I have performed some tests.

 - Windows Afanasy server does not serve GET requests correctly. It is bug (probably not in 2.1.0 - probably it was always so). I'll fix it.
 - Blender submission script does not provide correct result file names. Blender parser does not parse rendered files from blender output, but it can. I see that blender prints out what have it rendered.

To make afrender to generate thumbnail from a rendered image, it must know what the image is (its file name path). This info can be provided in 2 ways:
 - On a job submission: Script should query from application, where the scene is configured to render files and this files naming. And set this files to the job block.
 - During render by parser. Applications usually print out files that it starting or finished to render. Parser can parse images from output.
The best way is to do both, and in submitter, and in parser.
As during submission it can be difficult to query correct image name. Because render engine can change naming, for example if output images name is `img.####.exr`, but passes/layers are turned on, the result file can be `img_diffuse.0012.exr`. In this case parser can help. But folder is usually correct on submission stage. This info can help to open it from GUIs.
So.
I do not remember how i use to query files from blender in an old submission, but it seems that new one, with a new parses does not care about output files. And i want to ask from blender artists who knows Python (especially that artists who wrote a new submission script :) ) to help with this issue.

**Comment by tcheng00** [comment]
I'm not a programmer, but I can post your request on Blenderartists.org.  Would that be ok?

**Comment by predat** [comment]
@tcheng00 you could but i don't think they are technical user that can provide answer to this issue.

**Comment by timurhai** [comment]
You can post this request anywhere.
I can guide/help.

**Comment by tcheng00** [comment]
Couldn't hurt to try.  I'll let them know and see who bites.  What email address should I use?

**Comment by timurhai** [comment]
http://cgru.info/contacts

**Comment by tcheng00** [comment]
I posted here:

http://blenderartists.org/forum/showthread.php?401583-CGRU-Afanasy-Blender-Submitter-Help

**Comment by tcheng00** [comment]
Great news, can't wait to get the update.

**Comment by timurhai** [comment]
I just looked at parser you wrote.
They could parse an output image.
But it seems that a new blender version prints rendered image in a slightly new way.
Now there is an extra space after `Saved: ` string, and timing info goes in the new line (no need to trim it)

So this small fix:
https://github.com/CGRU/cgru/commit/b28064c4c200d8100a4c22f1b78eca47c1675508
fixed it to adopt the new style.

Such things should do blender users!
I've make it to should you how it is simple to do! ))

**Comment by timurhai** [comment]
Summary:
This issue have 3 issues:
 - afserver on windows os did not send thumbnails to WebGUI at all - fixed
 - blender parser could not understand new blender version otput - fixed
 - blender submitter did not provide any info in job, what output images should be - not implemented, but this need for come image actions before they are rendered, to open an (empty) output folder, for examaple, if you need this you can write it.

I am closing this issue, wait for 2.2.0
Or i can compile it for windows for testing by you.
But some new 2.2.0 afserver changes are bot well tested, i am advising you not to use it at work.

**Comment by skrmn** [comment]
Thank you! This are good news. I will wait for 2.2.0
But if it's possible to get for test version with fixed thumbnails it would be great, I could test it in working enviroment as well.
Thanks again.

**Comment by timurhai** [comment]
You can get it here:
http://rules.cgru.info/#/downloads/testing

**Comment by skrmn** [comment]
Thank you. Downloaded.
Will update overnight and post results after.

**Comment by skrmn** [comment]
I'm testing new build. Thumbnails are working in browser GUI, but do not work in afwatch, or maybe I need to do something with configs?
Thanks.

**Comment by timurhai** [comment]
There is no configs about showing thumbnails, just some for generating (that are good by default).
I've just tests, my afwatch shows thumbnails on windows10 (all on win10).
May be some error in server logs?

**Comment by timurhai** [comment]
ah, afwatch have some preferences for thumbnails size and quantity in "Customize GUI..." window.

**Comment by skrmn** [comment]
![afanasy](https://cloud.githubusercontent.com/assets/20071630/16412309/e1de2826-3d2b-11e6-890e-7ea240456c7f.PNG)

I checked - it looks normal.

**Comment by timurhai** [comment]
It is strange, but if you have 2.1.0 version, WebGUI should not show thumbnails, instead of afwatch :)
Check versions, it all should be 2.2.0.

**Comment by skrmn** [comment]
This is strange, because I've installed http://rules.cgru.info/#/downloads/testing
Let me double check things....

**Comment by skrmn** [comment]
![af](https://cloud.githubusercontent.com/assets/20071630/16412541/188425f0-3d2d-11e6-8787-059a04c6f597.png)

**Comment by timurhai** [comment]
https://github.com/CGRU/cgru/blob/master/version.txt
But sources revision is correct.
May be you have mixed some files from various versions.

**Comment by skrmn** [comment]
Yes, you were right it was a mix. Now it's ok. But thumbnails are not working in afwatch, only in web gui.
I'm using version 2.0.2 from testing (with sql support).
