### ISSUE TITLE
connect afrender->afserver failure after afrender IP address changed (mswin).

### ISSUE THREAD

**Issue by ramellij** [CGRU/cgru#255]
Hello,

I have a problem maybe someone has experienced the same issue : after launching some Vray job one of my windows render node just kill afrender by himself. I get this log : 

> Mon 27 Jun 15:09.08 : Initialized from store.
Mon 27 Jun 15:09.08 : Registered offline.
Mon 27 Jun 15:21.52 : Online '2.1.0'.
Mon 27 Jun 15:46.34 : ZOMBIETIME: 60 seconds.
Mon 27 Jun 15:46.34 : Ejecting task: [vray:1000] workstation2: test_cam4_masterLayer.vrscene[vray][frame 54]
Mon 27 Jun 15:46.34 : 
Resources: la[0,0,0]; C3492x8 u100% n0% s0% i0% o0% r0% f0%; M16281 F3568 C0 B0 S32560/12840 H59/15 N1/0 D0"3:0%
Mon 27 Jun 15:46.34 : Offline.

It happens in the middle of the first frame, only with big scene using lot of RAM (12Go with 16Go in total). For small animation it renders as it should. I can't find who's killing afrender. Does someone know what it could be ?

I'm using 2.1.0, all on Windows. 
Thanks for your help
JR

**Comment by timurhai** [comment]
Hi.
You should provide task Log and Output too.

**Comment by ramellij** [comment]
This all I have (task stopped rendering at 30%) : 
task : 
> frame 83
vray[vray]:1000 frames(83,83,1):
Command:
vray -sceneFile="\\Workstation2-pc\00_wip2\2015_WIND_TREE_II\01_MAYA\vrscenes\test_cam4_masterLayer.vrscene" -frames=83-83,1 -display=0 -autoClose=1 -verboseLevel=4 -showProgress=2
Working Directory:
\\Workstation2-pc\00_wip2\2015_WIND_TREE_II\01_MAYA\vrscenes

task output (this one is strange) : 
> Task output error:
Can't get file:
c:/temp/afanasy\jobs\0\2.test_cam4_masterLayer.vrscene\tasks\0.82\output\4.txt
No such file or directory

task log : 
> Mon 27 Jun 22:46.25 : SESSION #4: Starting on "creature-rn-02"
Mon 27 Jun 23:12.23 : Task update timeout.
Mon 27 Jun 23:12.52 : Finished - render zombie.

task error host : 
> Task[82] error hosts: 
creature-rn-02: 1 at Mon 27 Jun 23:12.23

render show log:
> Mon 27 Jun 22:46.06 : Initialized from store.
Mon 27 Jun 22:46.06 : Registered offline.
Mon 27 Jun 22:46.18 : Online '2.1.0'.
Mon 27 Jun 23:12.52 : ZOMBIETIME: 60 seconds.
Mon 27 Jun 23:12.52 : Ejecting task: [vray:1000] workstation2: test_cam4_masterLayer.vrscene[vray][frame 83]
Mon 27 Jun 23:12.52 : 
Resources: la[0,0,0]; C3492x8 u100% n0% s0% i0% o0% r0% f0%; M16281 F3465 C0 B0 S32560/12964 H59/15 N0/0 D0"3:0%
Mon 27 Jun 23:12.52 : Offline.

render task log:
> Mon 27 Jun 22:46.25 : Starting task: [vray:1000] workstation2: test_cam4_masterLayer.vrscene[vray][frame 83]
Mon 27 Jun 23:12.52 : Finished task: [vray:1000] workstation2: test_cam4_masterLayer.vrscene[vray][frame 83]

**Comment by ramellij** [comment]
And when I relaunch some job I get from server : 

> Mon 27 Jun 23:41.08: Removing not listening task: frame 83[creature-rn-01]
Mon 27 Jun 23:41.08: Removing not listening task: frame 90[workstation-pc]
Mon 27 Jun 23:41.08: Removing not listening task: frame 88[creature-rn-05]
Mon 27 Jun 23:41.08: Removing not listening task: frame 89[creature-rn-06]
Mon 27 Jun 23:41.08: Removing not listening task: frame 86[creature-rn-03]
Mon 27 Jun 23:41.09: Removing not listening task: frame 87[creature-rn-04]
Mon 27 Jun 23:41.09: Removing not listening task: frame 83[creature-rn-01]
Mon 27 Jun 23:41.09: Removing not listening task: frame 90[workstation-pc]
Mon 27 Jun 23:41.10: Removing not listening task: frame 88[creature-rn-05]
Mon 27 Jun 23:41.10: Removing not listening task: frame 89[creature-rn-06]
Mon 27 Jun 23:41.10: Removing not listening task: frame 86[creature-rn-03]
Mon 27 Jun 23:41.10: Removing not listening task: frame 87[creature-rn-04]
Mon 27 Jun 23:41.10: Removing not listening task: frame 91[workstation2-pc]

I don't know what it means exactly but I can see that [creature-rn-02], the one who's causing problem, is not in the list, but renders and then stop after few minutes as I mentioned before.

**Comment by timurhai** [comment]
Your afrender does not sending task progress to afserver.
This situation only on one machine?
Mon 27 Jun 23:41.10: Removing not listening task: frame 91[workstation2-pc]
 - have you listen it?
 - if not, are you sure that afserver and all afrenders are the same version?

**Comment by ramellij** [comment]
Yes I listened it and everything's fine until it stop. No error message from Vray log. 
Everyone is on version 2.1.0 (I just redownloaded last version and change it on workstation and render node to be sure) 

My last vray log : 
> [2016/Jun/28|09:17:30] Rendering image...: 23.55% [ 0h 14m 39.8s] [ 0h 47m 35.1s est] [5361 MB resman] [0 MB texman]

render log : 
> Tue 28 Jun 09:01.41 : Initialized from store.
Tue 28 Jun 09:01.41 : Registered offline.
Tue 28 Jun 09:01.53 : Online '2.1.0'.
Tue 28 Jun 09:18.36 : ZOMBIETIME: 60 seconds.
Tue 28 Jun 09:18.36 : Ejecting task: [vray:1000] workstation2: test_cam4_masterLayer.vrscene[vray][frame 146]
Tue 28 Jun 09:18.36 : 
Resources: la[0,0,0]; C3492x8 u100% n0% s0% i0% o0% r0% f0%; M16281 F3548 C0 B0 S32560/12827 H59/15 N0/3 D0"3:0%
Tue 28 Jun 09:18.36 : Offline.

task output : 
> Task output error:
Can't get file:
c:/temp/afanasy\jobs\0\2.test_cam4_masterLayer.vrscene\tasks\0.145\output\2.txt
No such file or directory

I don't understand this output because this path never exist. 
From render nodes I have more something like : 
> C:\temp\afanasy\tasks\2.0.5_15

How can I save afrender log before it killed himself ?

**Comment by ramellij** [comment]
Ok I managed to get this from afrender : 

>AFERROR: msgsendtoaddress: connect failure for msgType 'TRenderUpdate':
192.168.27.66:51000: No such file or directory
Connection lost count = 1 of 3
Error parsing output:
Traceback (most recent call last):
  File "C:\cgru-windows\afanasy\python\parsers\parser.py", line 144, in parse
    self.result = self.do(data, mode)
  File "C:\cgru-windows\afanasy\python\parsers\vray.py", line 39, in do
    percentframe = float(match[-1][1])
ValueError: could not convert string to float: '26.17% [ 0h 17m 42.9s] [ 0h 49m
58.5s est] [5361 MB resman] [0 MB texman]\r[2016/Jun/28|10:48:11] Rendering imag
e...: 26.17% [ 0h 17m 43.2s] [ 0h 49m 59.1s est] [5361 MB resman] [0 MB texman]\
r[2016/Jun/28|10:48:11] Rendering image...: 26.17% [ 0h 17m 43.4s] [ 0h 49m 59.7
s est] [5361 MB resman] [0 MB texman]\r[2016/Jun/28|10:48:12] Rendering image...
: 26.17'
AFERROR: msgsendtoaddress: connect failure for msgType 'TRenderUpdate':
192.168.27.66:51000: No such file or directory
Connection lost count = 2 of 3
Error parsing output:
Traceback (most recent call last):
  File "C:\cgru-windows\afanasy\python\parsers\parser.py", line 144, in parse
    self.result = self.do(data, mode)
  File "C:\cgru-windows\afanasy\python\parsers\vray.py", line 39, in do
    percentframe = float(match[-1][1])
ValueError: could not convert string to float: '26.22% [ 0h 17m 43.8s] [ 0h 49m
53.4s est] [5361 MB resman] [0 MB texman]\r[2016/Jun/28|10:48:12] Rendering imag
e...: 26.22% [ 0h 17m 44.1s] [ 0h 49m 54.0s est] [5361 MB resman] [0 MB texman]\
r[2016/Jun/28|10:48:12] Rendering image...: 26.22% [ 0h 17m 44.3s] [ 0h 49m 54.6
s est] [5361 MB resman] [0 MB texman]\r[2016/Jun/28|10:48:13] Rendering image...
: 26.22% [ 0h 17m 44.5s] [ 0h 49m 55.3s est] [5361 MB resman] [0 MB texman]\r[20
16/Jun/28|10:48:13] Rendering image...: 26.22'
AFERROR: msgsendtoaddress: connect failure for msgType 'TRenderUpdate':
192.168.27.66:51000: No such file or directory
Connection lost count = 3 of 3
Error parsing output:
Traceback (most recent call last):
  File "C:\cgru-windows\afanasy\python\parsers\parser.py", line 144, in parse
    self.result = self.do(data, mode)
  File "C:\cgru-windows\afanasy\python\parsers\vray.py", line 39, in do
    percentframe = float(match[-1][1])
ValueError: could not convert string to float: '26.22% [ 0h 17m 44.9s] [ 0h 49m
56.5s est] [5361 MB resman] [0 MB texman]\r[2016/Jun/28|10:48:13] Rendering imag
e...: 26.22% [ 0h 17m 45.2s] [ 0h 49m 57.2s est] [5361 MB resman] [0 MB texman]\
r[2016/Jun/28|10:48:13] Rendering image...: 26.22% [ 0h 17m 45.4s] [ 0h 49m 57.8
s est] [5361 MB resman] [0 MB texman]\r[2016/Jun/28|10:48:14] Rendering image...
: 26.22'
AFERROR: msgsendtoaddress: connect failure for msgType 'TRenderUpdate':
192.168.27.66:51000: No such file or directory
Connection lost count = 4 of 3
Render connection lost, connecting...
Finished PID=3884: Exit Code=0 Status=0 (stopped)
Task terminated/killed
AFERROR: Render with this hostname 'creature-rn-02' already registered.
Tue 28 Jun 10:48.15: INFO   Exiting render.
C:\cgru-windows>

The parsers errors are common and don't affect renders, I always have them so they can't be related. But connections lost are new for me ...

**Comment by timurhai** [comment]
Hi.
You client machine (afrender) can't connect server machine (afserver).
Try to ping server from client 192.168.27.66, when vray strarts to render.
( because if it registers and got a task - it was able to connect at first )
Try connect port 192.168.27.66:51000, by telnet, for example.
btw,
is this adress 192.168.27.66 correct?

**Comment by ramellij** [comment]
Yes this adress is correct. 
I ping render and server from both sides without irregularity. Except that client IP changed during render (because of where I am I can't give fixed IP) but without interrupting render and kipping link to server. And then after some times I got this : 
> AFERROR: msgsendtoaddress: connect failure for msgType 'TRenderUpdate':
192.168.27.66:51000: No such file or directory
Connection lost count = 1 of 3
AFERROR: msgsendtoaddress: connect failure for msgType 'TRenderUpdate':
192.168.27.66:51000: No such file or directory
Connection lost count = 2 of 3
AFERROR: msgsendtoaddress: connect failure for msgType 'TRenderUpdate':
192.168.27.66:51000: No such file or directory
Connection lost count = 3 of 3
AFERROR: msgsendtoaddress: connect failure for msgType 'TRenderUpdate':
192.168.27.66:51000: No such file or directory
Connection lost count = 4 of 3
Render connection lost, connecting...
Finished PID=7776: Exit Code=0 Status=0 (stopped)
Task terminated/killed
AFERROR: Render with this hostname 'creature-rn-02' already registered.
Tue 28 Jun 12:45.46: INFO   Exiting render.
C:\cgru-windows>

**Comment by timurhai** [comment]
I faced such situation the first time.
May be something should be reinitialized after IP address change.
We should dig inet for this.

**Comment by ramellij** [comment]
Ok. Strange thing is with others clients there is no problem. I'll make more tests with fixed IP. Could we use hostname in place ? On Windows we can't use hostname to setup server, only IP works. I don't know if it's a bug or normal.

**Comment by lithorus** [comment]
Constantly changing the ip address while rendering sounds like disasters
waiting to happen either way. Is this really something we should take into
account?

**Comment by ramellij** [comment]
I agree. Those IP changes shouldn't be, this is something I need to fix.
