### ISSUE TITLE
Render Non-sequential preview-frames with a different (slightly higher) priority

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#259]
Hi Timur,

I was thinking about rendering preview-frames with a different prio. I am unsure if the job should get an additional "Preview Priority" parameter, or if it should just be a global "af_preview_prio_offset" variable in config.json. I think I would prefer the latter with an default of "10".

This would mean that **preview frames** of a job with prio 99 should be treated as if they had prio 109 (99+10). Is that doable?

thanks in advance
Oli

**Comment by timurhai** [comment]
No.
Priority role affect on job choosing.
Later job creates a task.
It will be very complicated to calculate "effective" priority for each job frame.
Much more easy to change priority after preview frames done.

**Comment by ultra-sonic** [comment]
all good...i understand! Let's close this!
