### ISSUE TITLE
clearer overview of max allocated hosts per user (user priority)

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#260]
Hi Timur,

I always have a hard time setting "user priorities" right, because this "each point gives 10% bonus" is not very clear in my opinion.  Is it possible to show actual numbers here? 

For example if my farm has 100 nodes and I have 4 user with prio 99 I would expect to see an additional number (maybe next to the running jobs) which shows "max allocated hosts per user". In this case 25. If I then change one users prio to 100 I would the like to see how the overall balance is affected. This does not need to be service-specific!!!! It's just to get a general overview about the theoretical node distribution if all user would have lots of active jobs!

thx
Oli

**Comment by timurhai** [comment]
http://cgru.info/afanasy/user#user_priority
If user jobs solving method is "order" (default), a job with the greatest priority will be solved first, then all others.
I solving method set to "parallel", the same formula will be applied to user jobs.
