### ISSUE TITLE
pop up a confirm-dialog after clicking "restart" on a job.

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#261]
Hi Timur,

is it possible to get an additional confirm dialog after pressing one of the following job actions:
"restart job"
"restart & pause"
"restart running"
"restart skipped"
"restart done"

Sometime you click this accidentally and then at least one person is crying because they have wrangle the job by hand. 
This also bring up a question regarding issue #109 which I just posted there.

Cheers
Oli

**Comment by timurhai** [comment]
This items in an own sub-menu for this reason.
But we can add an option for a confirm dialog.

**Comment by timurhai** [comment]
Hm.
Since 2.1.0 they are already in an own submenu.
