### ISSUE TITLE
Arnold render individual frame progress

### ISSUE THREAD

**Issue by cg-cnu** [CGRU/cgru#262]
Current WebUI and AfWatch won't show arnold render individual frame progress.
As mentioned in #146, @eoyilmaz did you got it working ? 
Hope its not too much to ask, planning for pr anytime ?
It would be nice to have it in the UI.
Thanks.

**Comment by lithorus** [comment]
Perhaps the block was not marked as maya_arnold service?

- JImmy

**Comment by eoyilmaz** [comment]
As I see my pull request is merged in ea9d866 so it should be working, but I'm behind a couple of hundreds of commits on my repository, so may be there are changes that broke something.

**Comment by cg-cnu** [comment]
@eoyilmaz Ah... make sense. I am currently using 2.1.0 release version.
 
@lithorus Am sure the block is registered as a maya_arnold service. Are you able to see the progress?

**Comment by timurhai** [comment]
Simple check your task output and how maya_arnold.py script works, may some new version of arnold have some differ in output and we should fix parser to adopt new version (and better if it will be able to parse an old version too).
