### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by cg-cnu** [CGRU/cgru#264]
Hey guys,

We have been using cgru for quite some time and finished a good number of project on it. Got used to the terminology and the workflow. Thanks @timurhai  for cgru. Its really good and feature rich.

From the user perspective, one thing which I feel lacking is the documentation. While http://cgru.info/ has a good amount of documentation,  its mostly catering to the api. Lot of time, I found my self guilty of asking support questions in github issue. And, It would be too much to ask @timurhai to do the documentation along with the coding tasks.

I am no expert in cgru, but I can put in some time and help out in what ever role I can. So, with that I would like to invite ideas from the community as to how we can start taking the documentation forward. 

Please pitch in your ideas and suggestions.

**Comment by eliemichel** [comment]
:+1: 

When I started hacking on afanasy, I put some term definition in a file. They are available in the readme of [this branch](https://github.com/eliemichel/cgru/tree/socketpool), section *Concepts*.

Though it was just for myself, and written when I was still not 100% confident with the definitions, it could be a good basis to a more official doc defining the core Concept terms used by afanasy.

I definitely agree that afanasy (and I guess also cgru, but I only looked at afanasy) needs more documentation, both for promotion toward end users and for internal use between developers. But indeed, it takes a lot of time and efforts to organize a good doc.

I don't have much time to allocate to writing doc, unfortunately, but let's define a plan for it:

1. Promotion -- synthetic and appealing overview of the programs capabilities

 * A first word about what cgru/afanasy is. Assuming the user knows nothing about it. But not too long, maybe just one sentence.
 * An overview of the main *concepts*. Words like "Task" or "Job" sound very familiar once one is used to them, but it should be very clear to new users what it means, even *before installing* afanasy. This is important for people to know whether the application will fit their need, and how they can translate the terms they are used to into afanasy's vocabulary.
 * A list of the main features, i.e. what the program *performs* with these concepts. But a list organized in a pertinent way. Don't try to put everything in it, the next section will be made for this, but show that afanasy is flexible enough to do very various tasks.
 * other ideas?

2. User documentation -- a more systematic description of anything the user might need to know

 * A more complete glossary of concepts
 * A full list of features
 * A description of the configuration system. This is the first thing people have to do when setting up afanasy for the first time.
 * API Documentation
 * Tutorials, like how to create a new service, how to plug in a custom software.
 * other ideas?

3. Development documentation -- description of the program's design

 * A description of the subprojects. What does belong to `libafanasy`? Or other projects?
 * A technical description of the messaging system. How to add fields to some message payload? How to create a new message type and when one should do it?
 * Something about technical concepts, not shown to the end user but present in the code. Like `AfNode`, `AfContainer`, etc.
 * A roadmap. Both for future and past. Seeing the evolution of a project is a really good way to understand it better.
 * Internal (C++) API Documentation, at least for libafanasy.
 * Advanced Tutorials
 * other ideas?

Practically, 1. and 2. could be on cgru.info while 3. would be on Github's wiki. Just a suggestion. Also note that I put the bullet points in a random order, as it was coming to my mind.

Another thing to be careful about is to make this documentation live. We need a pipeline that ensures the documentation to stay in sync with the actual state of the program as much as possible. By pipeline, I mean good practices more than some technical solution.

Asking for systematic documentation of any new feature may add too much friction to contribution, but at least *mentioning* in some `doc.todo` that the feature exists and should be added to the documentation is a first step. And it would make easy tasks for new people taking over the project. They could write missing documentation from this todo list as a way to dive into the code.

Also, putting as much TODOs directly in the code as soon as an idea about something missing, or dirty comes is a good way to be able to `grep` the code for things to do then. And it's a good way to now, as a dev, what is legacy code, what is good practice.

**Comment by timurhai** [comment]
Hi.
Good ideas. Let me think.
Also i am thinking about some more resource, along with http://cgru.info/. It should be online too, but constructed from code. May be just to host doxygen output. May use some https://readthedocs.com/.

ps
I am in vocation right now, and will be in a village till 1 Aug. Very slow internet. And no chance to code ))

**Comment by cg-cnu** [comment]
Hey guys, thanks for your input.

@eliemichel That's a very good breakdown. I didn't see anything missing in the list. 
If we can get that working, we will be in good shape.

Just a few thing I would like to add...
1. Promotion: companies using cgru ?
    Contributors: @timurhai and others...?
2. User Documentation: FAQ?

@timurhai doxygen sounds good :+1: 

While we can decide where to put the docs, the main task would be to actually write them. For now we can start writing it in cgru wiki and replicate the same on the website later ?

And how do we start doing the work?  
Create a github issue for each one and tag it with website & documentation? People can pick up and start working on it and send pr.

**Comment by timurhai** [comment]
Now there is a forum for such discussions:
http://forum.cgru.info
