### ISSUE TITLE
Houdini 15.5 Tile Render Issue

### ISSUE THREAD

**Issue by fsimerey** [CGRU/cgru#265]
Hi, since H15.5, when i try to render an image in Tile Render mode (option in the Separate Render tab of an afanasy ROP), each render nodes are rendering the entire image and not only the part of the tile...

**Comment by timurhai** [comment]
It seems that they something changed.
I`ll check it when i will have some time for it.
Or you can check how it work manually.

**Comment by fsimerey** [comment]
After exploring, the bug comes from SideFX. If you enter the command 'echo ray_show renderer | mantra' in H14.x, H15.0.xxx, the property image:crop is set by default to [0,1,0,1] for (xmin,xmax,ymin,ymax). Since H15.5, this command returns [1,0,1,0]....
I submitted the bug to sidefx.

**Comment by fsimerey** [comment]
SESI submitted this as bug #76632.
But effectivly, they changed some options. Here the reply from SESI:

```
Hello Francois,

Our developers tell me that this was changed when we added support for overscan and generic data windows in images.

The mantra default crop window is to have no crop window (i.e. an invalid crop window). This allows mantra to know whether a bounding box was actually specified in the IFD or not.

This allows mantra to have a data window that's outside the visible window for rendering.

Note that when hqueue does tiled rendering, instead of using the crop window, it uses a separate setting in mantra (pixelcrop). It's the intersection of these two rectangles which is used to determine the pixels to be rendered.

How is CGRU tiled rendering dependent on the default value for the crop window? 

Cheers,
Silvina
```
And another one :

```
As a note, the code in mantra looks something like:

crop = getProperty("crop");
pcrop = getProperty("pixelcrop");
screen.makeInvalid();
if (pcrop.isValid())
    screen = pcrop;
if (crop.isValid())
{
    crop.convertToPixels();
    if (screen.isValid())
        screen.intersect(crop);
    else
        screen = crop;
}
if (!screen.isValid())
    screen = [0, xres-1, 0, yres-1] 



Cheers,

Silvina
```
I think it will be better to define crop tiles with the image:pixelcrop option because this option is in pixels value against the camera space value for image:crop (a floating between 0 to 1).

**Comment by timurhai** [comment]
Hi.
So how is going with this issue?

**Comment by fsimerey** [comment]
Hi.
I have tested my commit with H15.5, and all is fine. I would like to test with H13, H14 and H15.0.
Is there a way to specify the version (maj.min) from afanasy otl like the option in [mantra -N](http://www.sidefx.com/docs/houdini/render/batch#control-options) to execute houdini HXX.X on the render nodes ?
When i look in setup_houdini.sh, the script search the last hfs folder, but it is frequent to have different versions intalled and need to render with a specific version.

**Comment by timurhai** [comment]
I use this way
https://github.com/CGRU/cgru/issues/263

( just to check you can simple rename earlier HFS on some machine )

btw
this pull request is to your repo, not this:
https://github.com/fsimerey/cgru/pull/1

**Comment by fsimerey** [comment]
I use too #263 on my workstation, especially for daily builds (i have script to update and deploy daily builds on different machines every night). My request was more for the render nodes, but yes rename temporarily the hfs folders is a solution ;).
And thanks, the pull request is merged now.

**Comment by timurhai** [comment]
So, you have not created any pull request to this repo. ))
Can you create?

**Comment by fsimerey** [comment]
Ah sorry, not totally awake today... ))
Done.

**Comment by timurhai** [comment]
It is merged. Thank you!
