### ISSUE TITLE
use same software version on render, that was used with submitter

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#268]
Submitting in Houdini 15.0.222 with the afanasy node, I want afrender to use the exact same version. Even if newer ones are installed. I can't rely on setup_houdini.sh, it uses the newest version or the one definded in locate_houdini.sh. But what if the Houdini version used is changing often and changing per shot?

Right now I do this:
1) in the Houdini submitter (afanasy.py) set the  AF_CMD_PREFIX:
    os.environ["AF_CMD_PREFIX"] = "export APP_DIR=%s;" % os.getenv("HFS", "")
2) have an essentially empty locate_houdini.sh, so APP_DIR is actually picked up and overwritten in setup_houdini.sh

Is there already a better way? Or a better way in the future, that can be implemented?

**Comment by timurhai** [comment]
Hi.
The best way is to use own `houdini` command.
It can run any version you want denending on environment.
( we use working directory to set soft version, and any other environment )

**Comment by timurhai** [comment]
https://github.com/CGRU/cgru/issues/263

**Comment by sebastianelsner** [comment]
I see, thanks!
