### ISSUE TITLE
osx installer package needed

### ISSUE THREAD

**Issue by pomidorov333** [CGRU/cgru#27]
My farm is mostly built with 10.6.8 Snow Leopards, about 15 nodes. Would love to use CGRU's Afanasy as my renderfarm manager. Yet building sources by hand and paying for an older 'xcode' version just to get the AFrender going is what's keeping me from deploying the manager. Would it be possible to make a OSX package for easy OSX installation?

**Comment by NNois** [comment]
Hi,
Do you are always on that ? if so maybe you have an 2.0.5 installer for OSX to share ?

A++

**Comment by predat** [comment]
I'm very busy and i really need vacation ! So i can't provide a package before the end of august. Sorry for that !

**Comment by NNois** [comment]
You're right this is not the time to do so, in the middle of the summer what i was thinking about !!! Don't be sorry i was just about to do the same in about some weeks with the kids ;-)
but...
I just notice your homebrew-cgru and give it a try, appart from installing pyqt what it this about ?

**Comment by predat** [comment]
This really really a wip package... I've start this long time ago and i don't think it working fine...
However, it's not that work to compile cgru/afanasy. If you have homebrew installed, you can look at this:  https://github.com/CGRU/cgru/issues/27#issuecomment-43304811
If you have some problems, i can help you solve it...

**Comment by ultra-sonic** [comment]
I am building afanasy on osx since ages without problems!

**Comment by predat** [comment]
And ?

**Comment by NNois** [comment]
ok guys,
i've managed to compile cgru/Afanasy correctly on mac/homebrew

```
brew update
brew install ffmpeg imagemagick pyqt cmake openexr
git clone https://github.com/CGRU/cgru
cd cgru/afanasy/src/project.cmake
./build.sh --nosql -j9
```
--nosql because if not the build fail

now if i launch the server of course i have 

````
mdp-macpro2:afanasy magicprod$ bin/afserver 
Setting Afanasy root to "/Users/magicprod/github/cgru/afanasy"
Setting CRGU location to "/Users/magicprod/github/cgru"
Compilation date = 'Jul 15 2015 16:48:06'
CGRU version = ''
Afanasy build revision = '742005aa72a7417a9642ecf45a456cfde486014e'
Python version = '2.7.6'
GCC version = '4.2.1'
Config file does not exist:
/Users/magicprod/github/cgru/config.json
Database connection "AFDB_update" is not working.
AFERROR: AFDB_upTables: Database connect failed: (null)
Getting renders from store...
0 renders found.
0 renders registered.
Getting users from store...
1 users found.
1 users registered from store.
Getting jobs from store...
1 jobs found.
System job retrieved from store.
1 jobs registered from store.
Wed 15 Jul 17:42.02: Job registered: "afanasy"[1]: afadmin[0] - 14759 bytes.
Available addresses:
IP = '0.0.0.0'
IPv6 = '::'
IPv6 is disabled by config.
Using IPv4 addresses family.
Listening 51000 port...
```

is a database needed, and if not am i ok for the next things ? ;-)

cheers,
Noël

**Comment by timurhai** [comment]
Hi.
Database needed for statistics only.
You probably made 2.0.6 version ?

**Comment by NNois** [comment]
yep probably... is this a problem ?

**Comment by timurhai** [comment]
No.
It`s good to know that it is all good with 2.0.6 on OSX. (2.0.5 has compilation erros)

**Comment by timurhai** [comment]
Now there is a forum for such discussions:
http://forum.cgru.info
