### ISSUE TITLE
Maya plug-in builds

### ISSUE THREAD

**Issue by sergeneren** [CGRU/cgru#271]
If anyone needs the maya 2017 plug-in, i compiled it and put at https://drive.google.com/folderview?id=0BxQKssG4_Yy4SkJKM3ItWmxKRms&usp=sharing

**Comment by ultra-sonic** [comment]
What plugin are you talking about?

**Comment by sergeneren** [comment]
https://github.com/CGRU/cgru/tree/master/plugins/maya/src

**Comment by timurhai** [comment]
Hi.
Great!
I put here
http://rules.cgru.info/#/downloads/maya/2017
It will come with next releases.
If anyone can compile it for Linux and OSX will very helpful.

**Comment by sergeneren** [comment]
No problem, thank you for the great work.

**Comment by timurhai** [comment]
Now there is a forum for such discussions:
http://forum.cgru.info
