### ISSUE TITLE
building failes on CentOS 6

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#273]
cc1plus: error: unrecognized command line option "-std=c++11"

**Comment by timurhai** [comment]
I added with line when was playing with std::regex
https://github.com/CGRU/cgru/blob/master/afanasy/src/project.cmake/CMakeLists.txt#L51
But i forgot that old compilers can not recognize this option.
For now you can just comment this line.

**Comment by sebastianelsner** [comment]
yes, I just wanted to log this.
