### ISSUE TITLE
[BUG] Web GUI is getting "jobs_changed" event even if there is none

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#274]
I compiled current master and viewed the json "net log" in the WebGUI.
I noticed that every time when asking for events, the gui gets specific jobs in the queue as "changed", even when there are no changes to those (verification: all jobs in my test queue are ready and offline, and no render is online). I noticed all of these jobs have one thing in common: they have one block, that has a block dependency on all the other blocks. I was able to verify that this is causing the "jobs_change" problem by sending the same job without this dependency. This is a bug in the current afserver core, but not an issue in 2.0.8. 2.1.0 is also affected.

Related problem: I then removed the block dependency on the job with the issue, expecting that it would go away, but the issue remained, which means: the server does not correctly update the block dependency mask internally when setting it via the gui.
This can be one of those blockers for 2.2 i was getting ready to do testing for.

screenshots:

![screenshot](https://cloud.githubusercontent.com/assets/902798/17674422/c1e9c7c6-6325-11e6-9437-91bed8b0c959.png)
![screenshot-1](https://cloud.githubusercontent.com/assets/902798/17674426/c469b254-6325-11e6-9151-15f784de41c5.png)

**Comment by timurhai** [comment]
Hm. Strange.
I can't repeat the situation.
Can you create a minimum job via Python (or JSON directly) and provide its code (JSON object).

**Comment by sebastianelsner** [comment]
Yes, I will look into it.

**Comment by sebastianelsner** [comment]
So, I have looked into it further, but find no reason why this could be happening. Here is the json of a job that does NOT exhibit this problem

`
{
"name":"RnD.Maya_lighting_torusSphere_v002_sebels.main",
"id":2,
"priority":50,
"custom_data":"{\"project\": \"RnD\", \"department\": \"3D\", \"no_progress_for\": -1}",
"user_name":"sebels",
"host_name":"stationstu0411.rise",
"st":513,
"state":" RDY OFF",
"user_list_order":1,
"time_creation":1471284009,
"folders":{
"input":"/mutter/projects/RnD/scenes/Maya/setup-houdini",
"output":"/mutter/projects/RnD/scenes/Maya/img-cgi/Maya_lighting_torusSphere_v002_sebels/main/beauty"
},
"hosts_mask":"stationstu0411.*",
"blocks":[
{
"command":"export APP_DIR=/opt/hfs14.0.474;hrender_af -s @#@ -e @#@ --by 1.0 -t \"_current_\" \"/mutter/projects/RnD/scenes/Maya/setup-houdini/Maya_lighting_torusSphere_v002_sebels.hip_RnD.Maya_lighting_torusSphere_v002_sebels.main.0815-200008-971.hip\" \"/out/main\"",
"tasks_name":"",
"parser":"hbatch",
"working_directory":"/home/sebels",
"files":["/mutter/projects/RnD/scenes/Maya/img-cgi/Maya_lighting_torusSphere_v002_sebels/main/beauty/Maya_lighting_torusSphere_v002_sebels_main.@####@.exr"],
"name":"main - ifd",
"service":"hbatch",
"capacity":1000,
"flags":1,
"tasks_num":1,
"frame_first":1001,
"frame_last":1002,
"frames_per_task":20,
"frames_inc":1,
"sequential":10,
"need_memory":17000,
"block_num":0
},
{
"command":"export APP_DIR=/opt/hfs14.0.474;mantra -V a -f ",
"tasks_name":"",
"parser":"mantra",
"working_directory":"/home/sebels",
"name":"main - render",
"service":"mantra",
"capacity":1000,
"flags":1,
"tasks_num":2,
"frame_first":1001,
"frame_last":1002,
"frames_per_task":1,
"frames_inc":1,
"sequential":10,
"need_memory":17000,
"tasks_depend_mask":"main - ifd",
"block_num":1
},
{
"command":"export APP_DIR=/opt/hfs14.0.474;/mutter/standards/base-setups/risebase/production/scripts/rbbridge.py 0 RnD.Maya_lighting_torusSphere_v002_sebels.main sebels /mutter/projects/RnD/scenes/Maya/img-cgi/Maya_lighting_torusSphere_v002_sebels:/mutter/projects/RnD/scenes/Maya/img-cgi/Maya_lighting_torusSphere_v002_sebels",
"tasks_name":"",
"parser":"generic",
"working_directory":"/home/sebels",
"name":"risebase",
"service":"generic",
"capacity":1,
"flags":0,
"tasks_num":1,
"frame_first":0,
"frame_last":0,
"frames_per_task":1,
"frames_inc":1,
"block_num":2
}]
}
`

And this a a job that has this problem

`
{
"name":"RnD.Maya_lighting_torusSphere_v002_sebels.main-1",
"id":3,
"priority":50,
"custom_data":"{\"project\": \"RnD\", \"department\": \"3D\", \"no_progress_for\": -1}",
"user_name":"sebels",
"host_name":"stationstu0411.rise",
"st":513,
"state":" RDY OFF",
"user_list_order":0,
"time_creation":1471284479,
"folders":{
"input":"/mutter/projects/RnD/scenes/Maya/setup-houdini",
"output":"/mutter/projects/RnD/scenes/Maya/img-cgi/Maya_lighting_torusSphere_v002_sebels/main/beauty"
},
"hosts_mask":"stationstu0411.*",
"blocks":[
{
"command":"export APP_DIR=/opt/hfs14.0.474;hrender_af -s @#@ -e @#@ --by 1.0 -t \"_current_\" \"/mutter/projects/RnD/scenes/Maya/setup-houdini/Maya_lighting_torusSphere_v002_sebels.hip_RnD.Maya_lighting_torusSphere_v002_sebels.main.0815-200759-180.hip\" \"/out/main\"",
"tasks_name":"",
"parser":"hbatch",
"working_directory":"/home/sebels",
"files":["/mutter/projects/RnD/scenes/Maya/img-cgi/Maya_lighting_torusSphere_v002_sebels/main/beauty/Maya_lighting_torusSphere_v002_sebels_main.@####@.exr"],
"name":"main - ifd",
"service":"hbatch",
"capacity":1000,
"flags":1,
"tasks_num":1,
"frame_first":1001,
"frame_last":1002,
"frames_per_task":20,
"frames_inc":1,
"sequential":10,
"need_memory":17000,
"block_num":0
},
{
"command":"export APP_DIR=/opt/hfs14.0.474;mantra -V a -f ",
"tasks_name":"",
"parser":"mantra",
"working_directory":"/home/sebels",
"name":"main - render",
"service":"mantra",
"capacity":1000,
"flags":1,
"tasks_num":2,
"frame_first":1001,
"frame_last":1002,
"frames_per_task":1,
"frames_inc":1,
"sequential":10,
"need_memory":17000,
"tasks_depend_mask":"main - ifd",
"block_num":1
},
{
"command":"export APP_DIR=/opt/hfs14.0.474;/mutter/standards/base-setups/risebase/production/scripts/rbbridge.py 0 RnD.Maya_lighting_torusSphere_v002_sebels.main sebels /mutter/projects/RnD/scenes/Maya/img-cgi/Maya_lighting_torusSphere_v002_sebels:/mutter/projects/RnD/scenes/Maya/img-cgi/Maya_lighting_torusSphere_v002_sebels",
"tasks_name":"",
"parser":"generic",
"working_directory":"/home/sebels",
"name":"risebase",
"service":"generic",
"capacity":1,
"flags":0,
"tasks_num":1,
"frame_first":0,
"frame_last":0,
"frames_per_task":1,
"frames_inc":1,
"depend_mask":"main - ifd|main - render",
"block_num":2
}]
}
`
If I stop the server, remove the "depend_mask":"main - ifd|main - render" from the json and start the server again, the second job does not have the problem any more.
The json is taken directly from the afserver store.

**Comment by sebastianelsner** [comment]
Ok, here is a minimal job, that shows this problem. Can you give it a look?

```
import af

job = af.Job('some houdini job')
job.offLine()

block = af.Block('mainifd', 'hbatch')
block.setCommand('hrender_af')
block.setWorkingDirectory('/home/sebels')
block.setNumeric(1, 100, 10)
job.blocks.append(block)

block = af.Block('mainrender', 'mantra')
block.setWorkingDirectory('/home/sebels')
block.setCommand('mantra -V a -f ')
block.setNumeric(1, 100, 10)
job.blocks.append(block)

block = af.Block("other_block")
block.setDependMask("mainifd|mainrender")
block.setCommand("somecmd.py")
task = af.Task("othertask")
task.setCommand("somecmd.py")
block.tasks.append(task)
job.blocks.append(block)

job.send()
```

**Comment by sebastianelsner** [comment]
Again, if you remove the line

`block.setDependMask("mainifd|mainrender")`

then the problem does not show.

**Comment by timurhai** [comment]
Hi.
Now i see the same problem.
Will examine it.

**Comment by timurhai** [comment]
btw, simples job that i used during testing was
import af
`
job = af.Job('buggy')

block = af.Block('test1')
block.setNumeric(1, 2)
job.blocks.append(block)

block = af.Block('test2')
block.setNumeric(1, 2)
job.blocks.append(block)
block.setDependMask("test1")

job.send()
`
