### ISSUE TITLE
AfWatch render capacity manipulation for admins only.

### ISSUE THREAD

**Issue by timurhai** [CGRU/cgru#278]
What do you think about to move this render menu items for admins only:
 - Set Priority
 - Change Capacity
 - Change Max Tasks
 - Enable Service
 - Disable Service
 - Restore Defaults

**Comment by sebastianelsner** [comment]
+1

**Comment by abhishekgarg120** [comment]
Yes, that would be extremely helpful, we use CGRU as our rendering solution for over 400 artists, all the artist only use afwatch and they overwrite the default max running tasks settings which becomes an issue for other users.

**Comment by timurhai** [comment]
Wow 400 AfWatches!
What is CGRU version?
Since what version you started to use it?

**Comment by abhishekgarg120** [comment]
Yes, we have more then 400 artist using your application :)
currently using 2.1.0 and
 I started using cgru around 3 years back.
And I've deployed it to some other studios as well 👍

**Comment by sebastianelsner** [comment]
May I ask for the size of your farm?

**Comment by abhishekgarg120** [comment]
Our dedicated renderfarm is not that big, but we use all the workstations as rendering machines, its mostly nuke rendering on machines and maya rendering on renderfarm, but all of them are using CGRU only.

**Comment by timurhai** [comment]
Done for AfWatch:
https://github.com/CGRU/cgru/commit/467a6c97bc5d7e06c4505c1c12ff259c2d5ffab0
Soon will be the same for a WebGUI.
