### ISSUE TITLE
afcmd use JobID to stop or start

### ISSUE THREAD

**Issue by abhishekgarg120** [CGRU/cgru#280]
I'm trying to start / stop / delete jobs using the afcmd command but it gives me this error

```
AFERROR: REGEXP: Invalid preceding regular expression
 	jstop 	- Msg::TJSON
jstop [mask] Stop jobs which names match the mask.
```

what is the correct syntax for it, is there any python way to get a job by id and then start, stop or delete it?

I am trying something like this.

```
afcmd json send file.json | python -c 'import json,sys;obj=json.load(sys.stdin); jobs=obj["jobs"]; print [job["name"] for job in jobs if job.get("state", "") == "DON"]'
```

**Comment by timurhai** [comment]
- `afcmd jstop` is to stop job(s), which names matches provided mask (regular expression).
 - `afcmd json send file.json` sends data to server that soted in a file (assuming that the file contains a valid json object)

You can get all jobs and choose some by id. Or you can manipulate job(s) by name (mask).
