### ISSUE TITLE
Zero tasks number error using example JSON files.

### ISSUE THREAD

**Issue by Spudster3** [CGRU/cgru#281]
When submitting a new job with afcmd, the /cgru/examples/json/job_minimum.json and /cgru/examples/json/job_maximum.json scripts error out with the following:

> AFERROR: Invalid job 'job name'[0]:
> Block 'Nuke'[0]: Zero tasks number.

**Comment by Spudster3** [comment]
It appears that if the job has tasks defined, it works, but if the job is using numeric blocks, CGRU does not automatically create the tasks.

**Comment by Spudster3** [comment]
I think it might be related to the code in blockdata.cpp

if( m_tasks_num == 0)
	{
		*o_err += "Block '" + m_name + "'[" + af::itos( m_block_num) + "]: Zero tasks number.";
	}

**Comment by Spudster3** [comment]
It appears if you include the following in the "blocks" section, it should correct the issue in the JSON files:

"flags" : 1,
"tasks_num"  : 100,

**Comment by timurhai** [comment]
ps
Try to use Python API if possible.
It is designed to creatre a valid JSON objects.
And it always immediately updated to work with a new protocol changes.
