### ISSUE TITLE
Old jobs still in Web GUI

### ISSUE THREAD

**Issue by IvonneBurgos** [CGRU/cgru#283]
Hello, I deleted old jobs already rendered but they still appear in the web GUI, I checked the folder var/tmp/afanasy and they are not store there. 
![screenshot from 2016-08-22 17 17 48](https://cloud.githubusercontent.com/assets/7851291/17873767/2038f8bc-688d-11e6-96b6-170319d67deb.png)
Some of them present errors and it seems to keep waiting to finish but they dont exist anymore in my folder.

**Comment by sebastianelsner** [comment]
did you make sure you checked the /var/tmp/afanasy on the server?

**Comment by timurhai** [comment]
May be web browser page hang somehow. Try to refresh it (F5). Will be "old" jobs exist after refresh?

**Comment by IvonneBurgos** [comment]
Yesterday I did that and then I took the screenshot, today it works. Thanks
