### ISSUE TITLE
CentOS 6 build requires additional "rt" library now

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#284]
I had to add the line:

    export AF_ADD_LFLAGS="$AF_ADD_LFLAGS -lrt"

in the CentOS section of the build.sh to make the server link on CentOS 6. I cant see any related change, that would justify this. This was the original error

```
CMakeFiles/afserver.dir/workspace/cgru/afanasy/src/server/profiler.cpp.o: In function `Profiler':
/workspace/cgru/afanasy/src/server/profiler.cpp:49: undefined reference to `clock_gettime'
```

Is this intentional? Where does it come from? I just recently build (after the regex changes) and it worked fine....

**Comment by timurhai** [comment]
May be some distrib update caused this.
You can put it just for CentOS, or even just for CentOS 6:
https://github.com/CGRU/cgru/blob/master/afanasy/src/project.cmake/build.sh#L79

**Comment by sebastianelsner** [comment]
yes, hm, i did an update of a software yesterday..... will investigate

**Comment by timurhai** [comment]
Hi.
I've tested on CentOS 6.7 - works w/o `-lrt`.
Then i updated it and it CentOS became 6.8 - the same.
For special casese we can add some special flags in some other way, not to modify `build.sh` from repo.
