### ISSUE TITLE
global activity list

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#286]
Many times it can be interesting to see what renderfarm users have done on the farm as a whole not only per job/render. So this feature request means we need a log visible in Afwatch, this should be a combined log of what we see in the log of each job/block/task/render....

**Comment by timurhai** [comment]
May be create some verbosity level for afserver and it will log all users actions (may be in some other file).

**Comment by sebastianelsner** [comment]
Yes, + json request + simple Watch dialog.

**Comment by timurhai** [comment]
Now there is a forum for such discussions:
http://forum.cgru.info
