### ISSUE TITLE
houdini ifd files are not being removed after job deletion

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#288]
While temporary houdini .hip files are deleted after job deletion, ifd files are not.

**Comment by ultra-sonic** [comment]
i guess that's because ifds are supposed to be deleted after the render is
done if you select "delete ROP files" on the afanasy ROP. This mechanism
has caused me some headache in the past and I would also +1 for deleting
ifds only after the job is deleted from afanasy and ditch the old option.

**Comment by timurhai** [comment]
Hi.
You are talking about "Separate Render" of an Afanasy ROP, right?
This can be done in a block post command.
How we can construct a command?
Evaluate mantra "Disk File" parameter in a first and last frames and replace the difference with "*" character for some "rm" command?

**Comment by timurhai** [comment]
Hi.
You are talking about "Separate Render" of an Afanasy ROP, right?
This can be done in a block post command.
How we can construct a command?
Evaluate mantra "Disk File" parameter in a first and last frames and replace the difference with "*" character for some "rm" command?

**Comment by timurhai** [comment]
Hi.
You are talking about "Separate Render" of an Afanasy ROP, right?
This can be done in a block post command.
How we can construct a command?
Evaluate mantra "Disk File" parameter in a first and last frames and replace the difference with "*" character for some "rm" command?

**Comment by timurhai** [comment]
Hi.
You are talking about "Separate Render" of an Afanasy ROP, right?
This can be done in a block post command.
How we can construct a command?
Evaluate mantra "Disk File" parameter in a first and last frames and replace the difference with "*" character for some "rm" command?

**Comment by timurhai** [comment]
Hi.
You are talking about "Separate Render" of an Afanasy ROP, right?
This can be done in a block post command.
How we can construct a command?
Evaluate mantra "Disk File" parameter in a first and last frames and replace the difference with "*" character for some "rm" command?

**Comment by timurhai** [comment]
Hi.
You are talking about "Separate Render" of an Afanasy ROP, right?
This can be done in a block post command.
How we can construct a command?
Evaluate mantra "Disk File" parameter in a first and last frames and replace the difference with "*" character for some "rm" command?

**Comment by sebastianelsner** [comment]
Yes, I am currently testing this in production.

**Comment by timurhai** [comment]
Hi. Have you made something for this issue? Can you commit it?
( Soon i'am going make changes in houdini otl and submission scritp too. )

**Comment by timurhai** [comment]
I see that it is a job post command.
I though that job post command is to delete temp hip file.
And block post command can delete ifd files, if it generated ifds.

Also in what case they should be deleted?
This cause another question, what was the reason of generating ifds?
When you set "Enable Separate Render" parameter? Or "Custom Command"?
Various options can cause various ifds paths (names).

This commit fixed what? When it will delete ifds?

**Comment by sebastianelsner** [comment]
I sent this pull request only for review, not for merging, as per request description, to clear this exactly.

We always create ifds separately via the "separate render". When the job is deleted ifds should get deleted, because then we KNOW that the ifds are NOT needed any more. For example, when a mantra render task is restarted, without the hbatch ifd task beeing restarted.

**Comment by sebastianelsner** [comment]
Ah, now I see the confusion. "Delete ROP files" adds a command to the render block.... we dont use that since it creates the problem @ultra-sonic  mentioned above.

**Comment by timurhai** [comment]
O, may be i merged it too early :)   - but this is not dangerous
So we are talking about separate render.
( now i am confused )
Job post command should delete hip file.
May be we should make "Delete ROP files" option to delete ifds not in the task, but in BLOCK post command?
( on job deletion block(s) post sommand(s) are executed along with a job post command )

**Comment by sebastianelsner** [comment]
> Job post command should delete hip file.
Yes, and it still does.

> May be we should make "Delete ROP files" option to delete ifds not in the task, but in BLOCK post command?
I see, this is better. Will change it and I will take the "Delete ROP files" toggle into account.

**Comment by timurhai** [comment]
Hi.
Sorry, i reverted #293 pull.
Right now we need this at work too, and i write it other way.

**Comment by timurhai** [comment]
For "Custom Command" it is done.
Soon will be for "Separate Render".

**Comment by timurhai** [comment]
Done for a Separate Render too.

Also in an Afanasy ROP GUI i moded `override_service` and `override_parser` parameters from "Custom Command" tab to "Job Properties" tab. As they does not relate to a custom command mode, which has own service and parser settings.

Will test all this changes at work.
