### ISSUE TITLE
Blender submission does not handle scene path with spaces.

### ISSUE THREAD

**Issue by untappedstudios** [CGRU/cgru#289]
![image](https://cloud.githubusercontent.com/assets/14851151/18441994/a9be7254-78d4-11e6-95c1-0c03783a5863.png)

**Comment by untappedstudios** [comment]
Mon 12 Sep 07:41.47: INFO   Render registered.
WARNING: Working directory does not exist:
C:\Users\jeremy.wright

Started PID=4168: [postcmd:1000] jeremy.wright: test[post_commands][deletefiles]
Finished PID=4168: Exit Code=1 Status=1

WARNING: Working directory does not exist:
C:\Users\jeremy.wright
 From the node

**Comment by timurhai** [comment]
Hi.
Afanasy tries to inherit working derectory from your cg software application to tasks (commands) on afrender. So it stores it on a submission stage, and then afrender tries to launch child process in the same working folder. It can be useful if you are using relative paths.
If working folder does not exist, afrender just prints this warning.
If you are not using paths relative to the working directory, you can ignore this warning.

**Comment by untappedstudios** [comment]
I am using network paths but it still does not render and errors out how can you make it ignore the error?

**Comment by timurhai** [comment]
This is not an error.
To see error, try to look at the task output.

**Comment by untappedstudios** [comment]
Thanks for the quick responses. How could I go about viewing the task error from the web 
gui?

**Comment by timurhai** [comment]
There should be some "OUT" button, and/or some "Output" item in RMB menu.

**Comment by untappedstudios** [comment]
COMPUTERNAME=3DRENDER-1 
Read new prefs: C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\2.77\config\userpref.blend 
found bundled python: C:\Program Files\Blender Foundation\Blender\2.77\python 
Error: Cannot read file '\\fs01\Shared': No such file or directory 

Blender quit 
AL lib: (EE) ALCmmdevPlayback_open: Device init failed: 0x80070490

**Comment by timurhai** [comment]
Here is your error.
For faster debug, you can launch (copy&paste) the task command in a console.
Also, we can see that a path to the scene contains spaces, it should be quoted by a submission script, but it does not. It seems that blenders users that wrote this submission use paths with no spaces.

You can fix a Python script that sends jobs manually to handle spaces.

**Comment by untappedstudios** [comment]
yes using paths with no spaces worked correctly... thank you

**Comment by timurhai** [comment]
You can also try to replace in this command template
https://github.com/CGRU/cgru/blob/master/plugins/blender/addons/cgru_tools/operators.py#L27
`{blend_scene}` by `"{blend_scene}"` and try.
And if it works i can do this in repo.

**Comment by untappedstudios** [comment]
That gave me an error when loading the plugin
![image](https://cloud.githubusercontent.com/assets/14851151/18447629/19a16ee2-78ed-11e6-987c-0bc2438584c7.png)

**Comment by untappedstudios** [comment]
![error](https://cloud.githubusercontent.com/assets/14851151/18447647/2e9e441e-78ed-11e6-8438-13540b56c924.jpg)

**Comment by predat** [comment]
Try to escape double quote:
\"{blender_scene}\"

**Comment by untappedstudios** [comment]
\"{blender_scene}\" this works
