### ISSUE TITLE
 Add a block/task to an existing job

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#292]
While searching for a solution for a use case I have right now, I found this on the "Raodmap" page of cgru.info. But there was no ticket so I created one. 
In some cases it would be really interesting to have afanasy accept new blocks/tasks after the job was created. Please note I added the "new tasks", this was not on the Roadmap.
Rationale:
- In the context of Houdini distributed simulations it would be good to have afanasy start the "tracker.py" via a wrapper script on a render, then have the wrapper script send a new block/task for that job to afanasy, describing the acual simulations and most importantly, pass along the IP address of the host where the tracker is running. Right now the tracker needs to be started manually.
- If you are able to add tasks, afanasy gets a very powerful feature, which you normally only have in task queues like "celery" (http://www.celeryproject.org/): "Fire and forget". You could have one job called "All Image Resizings" and just append tasks to one preexisting block, without worring that you need to create a new job for each picture resize or filling up the queue in afwatch.

**Comment by timurhai** [comment]
I agree, it will be a useful feature.
But for now i can't say when.

**Comment by sebastianelsner** [comment]
No hurry from my side, I can make good workarounds.
