### ISSUE TITLE
Dailies Render from Nuke

### ISSUE THREAD

**Issue by korki696** [CGRU/cgru#296]
First of, Thanks for the awesome software!

I am having a problem using the dailies render. Wether I do it from Nuke or through MovieMaker->Dailies I get the same result.

`convert: unable to read image data '/var/folders/sk/qzhm89j57nb72p7tb9cdv0xr0000gn/T/makemovie.16-10-18_09-51-21_367043972015/logo_frame.tga' @ error/tga.c/ReadTGAImage/506.
convert: no images defined '/var/folders/sk/qzhm89j57nb72p7tb9cdv0xr0000gn/T/makemovie.16-10-18_09-51-21_367043972015/img.0000141.dpx' @ error/convert.c/ConvertImageCommand/3257.
/Volumes/Untitled/Volumes/Untitled/Volumes/fs1-alpha/renders/test_V001.0106353.dpx
@IMAGE!@/var/folders/sk/qzhm89j57nb72p7tb9cdv0xr0000gn/T/makemovie.16-10-18_09-51-21_367043972015/img.0000141.dpx
PROGRESS: 100%`

I noticed that coming from Nuke, the export path adds "/Volumes/Untitled/" before the actual path which is the local drive. This is not the case with MovieMaker but I do get the same result.

Any idea what could be causing this?

Thanks

**Comment by timurhai** [comment]
No idea. Lots of questions.

What OS?
Where you took `convert`?
Does it work?
That files are really exist?
Does convert "understand" that files?
What command was launched for dailies generation?

Next time try to specify well-formatted output with a good line-ends and from the beginning till the first error.

**Comment by korki696** [comment]
It looks like the issue was related with tga exports. and how the slate was being genterated as it doesn't adhere to the temporary format rule. Once I changed "tmplgs" and "tmplgf" to .dpx instead of .tga it works fine.

Would it make sense to define those variables as follows:

`# Definitions:
tmpname   = 'img'
tmplgs    = 'logo_slate.%s' % Options.tmpformat
tmplgf    = 'logo_frame.%s' % Options.tmpformat`

-Lars Koerkemeier

**Comment by timurhai** [comment]
It seems that your `convert` does not understands `tga` format.
Strange, `tga` was chosen as most supportable (mature) at first.
