### ISSUE TITLE
Wake-On-Lan: Automatic sleep and wake up.

### ISSUE THREAD

**Issue by timurhai** [CGRU/cgru#30]
Render should sleep after special time with no task (wol idle sleep time).
Server should wake sleeping renders when there are enough ready tasks.

**Comment by lithorus** [comment]
I'm having a few issues with the wakeonlan feature. Is it true that a machine will not be waken unless it's already "sleeping"?

And perhaps it's something we can change?

Also I'm not certain when the sleep function gets triggered. I've had clients that are free for 4 hours plus even though their wol idle sleep period is 2 min.

**Comment by timurhai** [comment]
Hi.
Machines can be "free" for any time, for wake-on-lan it does not matter.
Your machines should be "idle" for more that 2 mins.
 - `free` is seconds with no task.
 - `ilde` is `free` **and** confirm all `nimby_idle_*` conditions (prefix "nimby_" is historic, as before that parameters affects only `nimby`, and parameters was not renamed from that time).

**Comment by lithorus** [comment]
Ahh.. that makes sense. Ignored all the nimby stuff since I didn't think it had anything to do with wakeonlan :)
