### ISSUE TITLE
Config overrides.

### ISSUE THREAD

**Issue by timurhai** [CGRU/cgru#301]
It is useful to have an ability to override some config parameter w/o any config files modifying.
Any config parameter can be overridden with environment variable and command arguments.

For example, it can help to connect afwatch to other afserver quickly:
`afwatch --af_servername otherserver`

Or you can override some parameters in a console environment for tests:
`export CGRU_AF_SERVERPORT=51111`

Command line arguments will have the same name and `--` prefix.
Environment variable will have uppercase name and `CGRU_` prefix.

**Comment by timurhai** [comment]
Done for libafanasy, soon will be the same for Python API.

**Comment by sebastianelsner** [comment]
This is really useful!

Am 28. Oktober 2016 11:44:53 MESZ, schrieb Timur Hairulin <notifications@github.com>:
>Done for libafanasy, soon will be the same for Python API.

**Comment by ultra-sonic** [comment]
Awesome feature :) looking forward to the python implementation!

**Comment by sergiy-nazarenko** [comment]
I thought may be it also would be good to add some variable for entire config.
For instance it could be CGRU_CONFIG or something like that. 
I implemented it for us and I can pull those changes.

**Comment by timurhai** [comment]
Hi.
You are talking about an environment variable `CGRU_CONFIG` that contains an additional file to include?
Or i did not got you.

**Comment by sergiy-nazarenko** [comment]
No, it is not is a file but directory which contains files - farm.json and config.json
