### ISSUE TITLE
python error if "af_priority" is not in config file

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#302]
This is on current master.

When submitting from Houdini and "af_priority" is not defined in a config file or via the new config overrides, I get this error:

>Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/raid/standards/base-setups/cgru/plugins/houdini/afanasy.py", line 839, in render
>    params[-1].genJob(params[:-1])
>  File "/raid/standards/base-setups/cgru/plugins/houdini/afanasy.py", line 385, in genJob
>    job = af.Job()
>  File "/raid/standards/base-setups/cgru/afanasy/python/af.py", line 530, in __init__
>    self.data["priority"] = cgruconfig.VARS['af_priority']
>KeyError: ('af_priority',)

**Comment by sebastianelsner** [comment]
The "af_priority" is indeed defined in "cgru/afanasy/config_default.json" but it seems the file is not read. We do not have a copy of "config_default.json" as a "config.json"

**Comment by sebastianelsner** [comment]
Am I expected to have a "cgru/afanasy/config.json" now? I already have on in "cgru/config.json".

**Comment by timurhai** [comment]
Hi.
You should have `cgru/config_default.json` and `cgru/afanasy/config_default.json` from repo, w/o any changes. And define (override) your settings in a `cgru/config.json`. So that `_default` files are needed for the project work.
Also you should not just copy `config_default.json` in a `config.json`, you should define (override) only minimal needed parameters. As a new version can have an important change in some parameter to work proper.

**Comment by sebastianelsner** [comment]
yes, I do exectly this.
* cgru/config_default.json and cgru/afanasy/config_default.json from repo
* override setting in a cgru/config.json:
* I have NO cgru/afanasy/config.json

**Comment by timurhai** [comment]
So, how have you lost `af_priority`?
May be config was not initialized?
It is strange, but it initializing on `import af`:
https://github.com/CGRU/cgru/blob/master/afanasy/python/af.py#L10
May be you customized this scripts somehow?
Ensure that config was initialized, before `job = af.Job()`.

**Comment by sebastianelsner** [comment]
I see the error now. We are still using Python 2.6 with Houdini and it does not have the `object_pairs_hook` argurment of `json.load()`.
It fails silently in https://github.com/CGRU/cgru/blob/master/lib/python/cgruconfig.py#L202

```
        try:
            obj = json.loads(filedata, object_pairs_hook=collections.OrderedDict)['cgru_config']
        except:  # TODO: Too broad exception clause
            success = False
            print(filename)
            print(str(sys.exc_info()[1]))
```

Is this needed for anything in particular?

**Comment by timurhai** [comment]
This needed when we have:
"param":"value"
then **later** "OS_" override:
"OS_unix":{
"param":"value"
If there is no order, it can read OS override at first that comes later in a file.

**Comment by sebastianelsner** [comment]
I see, so this was an issue before but it was not noticed?
This means afanasy breaks compatibility with CentOS 6 from this point on?

**Comment by timurhai** [comment]
Hm.
It was fixed several month ago, as it was noticed.
W/o that argument parameters most often has the same order.
And i thought that it is the default behavior. But sometimes (when we changed our config) we noticed this.

Python version check can be a solution to keep python 2.6 compatibility.
If you did not noticed this config keys order issue - you can use old way.
( may be you use only one OS and do not have overrides at all )

**Comment by sebastianelsner** [comment]
I think a python version check is needed. Else you would require users to "OrderedDict",too.

**Comment by timurhai** [comment]
Hi.
I added a check.
So be attentive with this issue for Python 2.6
Try not to use:
    
    "param":"value"
    ...
    "OS_unix":{
    
, use:
    
    "OS_windows":{
    "param":"value"
    ...
    "OS_linex":{
    
instead.

**Comment by sebastianelsner** [comment]
ok, not a problem for us. thanks!
