### ISSUE TITLE
AfWatch&WebGUI: UI annotations level.

### ISSUE THREAD

**Issue by timurhai** [CGRU/cgru#304]
It will be useful for "afwatch beginners" to see more text on items that describe parameters.
For example: `Priority:100 HostsMask:mymask.*` and so on.
But this information level should be customizable.
As it will be to much text w/o any useful info.
So more "afwatch" experienced users may prefer to see `Pri:100 Hosts:mymask.*`
And may be someone even prefer `p100 h(mymask.*)`.

**Comment by timurhai** [comment]
Almost done for AfWatch.
Of next the same for WebGUI.
Take a look at it.
( i remember we have discussed it about a year before )

**Comment by timurhai** [comment]
I forgot to say.
To change UI level go to main dialog RMB menu (where you can choose theme).

And also, may be put all items of that menu in a main application window menu, to make afwatch looking more common? What do you think?

**Comment by timurhai** [comment]
Ok.
And main window menu now exists and an old RMB menu is shown on advanced UI levels.

**Comment by sebastianelsner** [comment]
Both good ideas!

**Comment by timurhai** [comment]
Web GUI is update here:
http://afanasy.info:51000

You can check new UI levels online.

**Comment by timurhai** [comment]
Hi.
How about to hide job ID on padawan UI level?
Only jedi can use id :)

ps
"padawan" is the default and the first (lowest) UI level. There are such full annotations as "Priority:99".

**Comment by sebastianelsner** [comment]
yes looking good!
