### ISSUE TITLE
get service limits and service limits usage via json

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#307]
It seems there is currently no way to get the service limits and the service limits usage via json.

void ServiceLimit::jsonWrite( std::ostringstream & o_str) const

seems unused.

also, "afcmd" does not give the current usage, in my case it always prints 0

Only the "writeFullInfo" of an RenderAf gives the good info.

**Comment by timurhai** [comment]
Hi.
`afcmd` uses JSON requests protocol too.
Yes you are right.
There was not any need of this before you )
There is not a big deal to make some new request and answer.

**Comment by sebastianelsner** [comment]
works fine. thank you!
