### ISSUE TITLE
Natron 2.1.8

### ISSUE THREAD

**Issue by tobkum** [CGRU/cgru#309]
The plugin does not work in latest version of Natron (2.1.8). Using CGRU 2.2.0

![image](https://cloud.githubusercontent.com/assets/16955378/20607571/e79f6f04-b279-11e6-9ff2-6ded748cf866.png)

**Comment by predat** [comment]
It's a typo I think... it should be 'setPersistent'

**Comment by tobkum** [comment]
Confirmed, replacing all "setPersistant" occurences with "setPersistent" in afanasyGroup.py solves the error

**Comment by predat** [comment]
Can you submit a pull request ?

**Comment by tobkum** [comment]
Done - #310

**Comment by timurhai** [comment]
Great!
But, strange how it worked before...
