### ISSUE TITLE
Solve jobs by total capacity. 

### ISSUE THREAD

**Issue by timurhai** [CGRU/cgru#314]
Now users (jobs) are solved by total number of running tasks.
But tasks can complexity (designed to be described by capacity) can differ much.
So user with light tasks take can take only the same number of hosts as a user with heavy tasks.
But more correctly to calculate running tasks total  capacity (not only their quantity).

**Comment by timurhai** [comment]
Now server solves users (jobs) by running tasks total capacity.
To switch to old behavior (solve by running tasks number)
set `af_solving_use_capacity` config parameter to false.

**Comment by ultra-sonic** [comment]
sounds like a nice feature addition! thumbs up for that!
