### ISSUE TITLE
Initial Project Specifics

### ISSUE THREAD

**Issue by Bazed** [CGRU/cgru#315]
Hi, any chance of adding a way of setting project specific details for a project in Rules, like for instance the dailies generation settings? Some projects are in 25fps, others 24fps, some doesn't require a full blown 1080p high-h264 daily generated.. while others (could be clean up work), require higher quality settings for producers to evaluate work done. Right now, as far as I can see, you can either edit the dailies default setting or manually change the dailies settings one by one each time you produce them. Would be nice to have a small project specifics form where you could punch in certain things that would later streamline the workflow for each running project in Rules.

**Comment by timurhai** [comment]
Hi.
All initial settings are in the config file:
https://github.com/CGRU/cgru/blob/master/rules/rules.00_general.json#L208

In any project you can create some `project_folder/.rules/rules.project_spec.json` and override some parameters.
For example
    
    {
    "fps":"24",
    "dailies":
    {
    	"format":"1920x1080",
    	"fps":"24",
    	"codec":"h264_mid"
    }
    }

**Comment by Bazed** [comment]
Ok, that will work nicely. thanks!

**Comment by Bazed** [comment]
I get:
Error: RULES file "rules.project_spec.json" in "/SLEEP_CURSE/.rules" is invalid.

This is what's in the json file:

`{
"dailies":
{
    "format":"asis",
    "fps":"24",
    "codec":"h264_high",
    "colorspace":"log",
}
}`

**Comment by timurhai** [comment]
Syntax error, see http://www.json.org/
Object (array) latest member should not have a comma.
Some text editors can highlight JSON syntax errors.

**Comment by Bazed** [comment]
Thank you Timur, my apologies for that oversight.
