### ISSUE TITLE
Isotropix Clarisse iFX support

### ISSUE THREAD

**Issue by timurhai** [CGRU/cgru#316]
This support means:
Service, parser, farm setup, icon, examples, afjob.py, afstarter dialog, keeper menus.
And may be some submission plugin to submit jobs directly from Clarisse application.
But whether such submission plugin needed for this software?

**Comment by timurhai** [comment]
Commits:
https://github.com/CGRU/cgru/commit/b0c70c6080451f2a82dfc58071d387ad107050d8
https://github.com/CGRU/cgru/commit/d0e7a747efddff7395b5c90ee85edae340d8c74b
https://github.com/CGRU/cgru/commit/cd2a27dd9f1a8effbe41ef5ada592b68e178ab76
https://github.com/CGRU/cgru/commit/11b9f7582214b58de4222e81c4075f21e84c5e7f
https://github.com/CGRU/cgru/commit/a9fed9ee9b830170eed90855f224c56fafcb7735

**Comment by Bazed** [comment]
Hi Timur, this is great news. Let me get back to you regarding your in-app submission plugin question.

**Comment by timurhai** [comment]
Hi.
If we want to write in-app submission, some consult from Clarisse users will be great.
Can we write in-app dialog using PyQt? (Where is "Hello world" example?)
If we can't, were is Clarisse-specific ui scripting documentation?

**Comment by Bazed** [comment]
You can grab the PLE version, and press F1 to get some information on how to script for 3rd party applications. There is some information here which I have been looking at:

http://www.clarissewiki.com/common/script_usage.html
http://www.isotropix.com/products/batch-rendering/cnode-crender

**Comment by timurhai** [comment]
Yes, i saw this help. But there is nothing about dialogs scripting.

**Comment by Bazed** [comment]
Let me check in the SDK which comes with the install once I get back to the studio. There's some info in the forum too, here:

http://forum.isotropix.com/viewforum.php?f=21

**Comment by timurhai** [comment]
I see now in SDK (docs/sdk/using_pyqt.html):
```python
from PyQt4 import Qt
import pyqt_clarisse
app = Qt.QApplication(["Clarisse"])
hello = Qt.QLabel("Hello, World")
hello.show()
# instead of calling app.exec_() like you would do normally in PyQt,
# you call pyqt_clarisse.exec_(app).
pyqt_clarisse.exec_(app)
```
And it works with PySide too, great!

**Comment by timurhai** [comment]
http://forum.isotropix.com/viewtopic.php?f=21&t=2724

**Comment by Bazed** [comment]
Awesome! Will try it out asap, thanks Timur.

**Comment by timurhai** [comment]
So, have somebody tried?

Also there is a software section on forum for general discussion:
http://forum.cgru.info/viewforum.php?f=31

**Comment by Bazed** [comment]
Will install on a blade server this weekend,shall report back ;)
