### ISSUE TITLE
Macosx does not have 'execvpe'

### ISSUE THREAD

**Issue by predat** [CGRU/cgru#318]
I've problem to compile 'launchprogram.cpp' because macosx don't have 'execvpe' function.
Is it safe to use 'execvp' ?

**Comment by timurhai** [comment]
If `execve` exists, you can use `#ifdef MACOSX` to skip this check
https://github.com/CGRU/cgru/blob/master/afanasy/src/libafanasy/common/launchprogram.cpp#L436
and always execute 1st block (if always true).
It should work, as second block will be executed only if specified shell does not starts with '/' character
https://github.com/CGRU/cgru/blob/master/config_default.json#L51
And i do not believe that someone will specify a relative path to the shell.

I think that we can drop this condition at all, as its `false` case is not practically used.

**Comment by timurhai** [comment]
ps
This `launchprogram.cpp` file is very mature and was taken from other program (see comments header).
So it was not specially designed for Afanasy at first.
