### ISSUE TITLE
Easy job queue

### ISSUE THREAD

**Issue by fynjah** [CGRU/cgru#319]
Is it possible to add new feature, something like 'easy job queue'.
What that means:
Sometimes we need to send all the farm on one single job and we use 'depend masks' for that.
But, there are two problems with this: 
1) You have about 20-30 jobs and it's not so easy to control them - to write correct 'depend mask' for each job. Just imagine yourself: 2 days sleepless, 4AM and you have to fill about 20-30 absolutely correct masks
2) Using 'depend masks', each next job will wait till previous job will be done fully. That's ok for really 'depend job', but not for simple job queue: If we already have free render nodes, why not to start next job?

I know, you'll say about priority... but may be it's easy to do with some kind of drag'n'drop?:D

I hope I was clear.

Greetings from Terminal FX:) Thanks

**Comment by timurhai** [comment]
Hi.
Sorry, may be i did not got you.
You want to send job in the top of your queue?
How depend mask is related to this?
Yes, to send a job in the top, you can:
1. Make job to move top itself by setting higher priority.
2. Move job top yourself within a GUI using RMB menu (drag'n'drop can be comfortable, but does implemented).

**Comment by timurhai** [comment]
Now there is a forum for such discussions:
http://forum.cgru.info
