### ISSUE TITLE
Translation problem between server and client

### ISSUE THREAD

**Issue by RonnyValdivieso** [CGRU/cgru#324]
Hi.
It seems like there's a problem with "pathsmap".
I'm working with 1 server and 2 clients:

- Server: Ubuntu 14.04
- Client 1: Ubuntu 15.04
- Client 2: Windows 8.1

Server and windows client are working fine, but there's a problem between server and ubuntu client.

Client
![client_w](https://cloud.githubusercontent.com/assets/7757060/21745318/0b997b6c-d4f7-11e6-8e67-f99672a37450.png)

Server
![server_w](https://cloud.githubusercontent.com/assets/7757060/21745321/17a18076-d4f7-11e6-80bd-819acf2006fc.png)

When a job is sent through Afanasy Starter from server, client gets the message "WARNING: Working directory does not exist: share". The server is working but the client doesn't.

![err_c](https://cloud.githubusercontent.com/assets/7757060/21745281/4bc2b6aa-d4f6-11e6-9c18-e5bf44d3c35d.png)

...the same problem from client. The client works but server doesn't.
Message on server: "/run/user/1000/gvfs/smb-share:server=200.126.7.232,share=share/"

![server](https://cloud.githubusercontent.com/assets/7757060/21745304/cdd9ba1c-d4f6-11e6-83cd-bac8bf9fd9b4.png)

This is my config.json
![client](https://cloud.githubusercontent.com/assets/7757060/21745336/7ab3ebd6-d4f7-11e6-953b-b3719379f319.png)

I have the same configuration on windows.
I followed the example in cgru documentation.

**Comment by timurhai** [comment]
Hi.
To check paths map you can open task in afwatch (double click job - receive tasks - double click task).
May be you have the same paths map for linux and windows clients?
Paths map designed to be different for clients with different paths.
If you want to use the same shared config.json (it is very useful), use OS_unix and OS_windows sections - as it shown in documentation in example.
Also you can see it in the default config:
https://github.com/CGRU/cgru/blob/master/config_default.json#L53

BTW
As paths map is described in client -> servers pairs, and your server is linux, you can describe paths map for windows clients only.

PS
Strange OS versions for production 15.04 and 8.1 :)
I met only 14.04 and 16.04, 7 and 10.
Afanasy was never compiled for 15.04 and not tested on 8.1 by me.

**Comment by IvonneBurgos** [comment]
Hi,

The problem is that we can't use Afstarter properly with the share folder we created. The server also works as render. If we send a job from client, this save the images in the share folder, but the other render doesn't. In terminal we got the message "Working directory does not exist". And this happend on the other side too. 

We configured the paths as we read on cgru website.
