### ISSUE TITLE
Does awscli parser work ? 

### ISSUE THREAD

**Issue by predat** [CGRU/cgru#328]
Hello @abuisine,

I'm looking to your awscli parser, but i found that all regex are, i think, outdated...

We can replace regex with this:
```diff
diff --git a/afanasy/python/parsers/awscli.py b/afanasy/python/parsers/awscli.py
index 963f5ff..55a0804 100644
--- a/afanasy/python/parsers/awscli.py
+++ b/afanasy/python/parsers/awscli.py
@@ -22,12 +22,8 @@ class awscli(parser.parser):
                :return:
                """
                # print(data)
-
-               data = re.findall(r'\d+ of \d+ part', data)
-               if len(data) == 0:
-                       return

-               data = re.findall(r'(\d+) of (\d+) part', data[-1])
+               data = re.findall(r'(-?[0-9]+\.[0-9]+?) MiB\/(-?[0-9]+\.[0-9]+?) MiB', data)
                if len(data) == 0:
                        return
```
I'm using awscli version 1.11.36.
Are you ok with that ?

**Comment by abuisine** [comment]
true, although the fixe is not as simple as it sounds, as you can have KiB MiB GiB compared

**Comment by timurhai** [comment]
Hi.
So, what is with this issue?

**Comment by abuisine** [comment]
The parser needs to be reworked to parse awscli output which changed, however the proposed patch rely on file sizes being in MiB, which will probably result in weird behavior when processing GiB big files.
I did not review the latest awscli lately, but there may be an easier output to parse with some additionnal flags in the command line.

I am not developing that much lately, so if someone got the motivation to do it then nice.
If not I can probably check the amazon cli a bit further and propose something.
