### ISSUE TITLE
${PATH} issue

### ISSUE THREAD

**Issue by ramellij** [CGRU/cgru#330]
Hi,
I need to launch a job with an environement path like "${WIP_PATH}/my project scene" but anytime I try I get "C:\cgru-windows\start\AFANASY\${WIP_PATH}/my project scene" (this is where I put CGRU) in afstarter and I can't launch anything. 
I'm trying to use windows server with linux renderers (I know that's not perfect). 
Do you know what it means ?

thanks for your help (again)
JR

**Comment by timurhai** [comment]
What path is shown in afstarter dialog (under controls)?

**Comment by ramellij** [comment]
I get : "Working directory does not exist."

**Comment by timurhai** [comment]
Afstarter checks any paths for existence. It seems that you can't do such things within it.
Paths map is designed for mixed OS rendering.

**Comment by ramellij** [comment]
ok, is there an other way to launch a job ?

**Comment by timurhai** [comment]
Afstater -> afjob.py -> Python API -> JSON protocol
You can create a job at any level.

**Comment by ramellij** [comment]
Ok thanks, I don't know what it means and how to do it but I'll search ;)

**Comment by ramellij** [comment]
Well I manage to launch manually a job using the code that afstarter give me in CGRU terminal and so I can change my path manually to set what I need. The job is launching correctly and my project paths are good. But like before, between terminal and my Vray output, the path changes from "${WIP_PATH}my scene" to "c:\temp\afanasy\${WIP_PATH}my scene" this time.

**Comment by ramellij** [comment]
I searched everywhere and I don't understand why and where the path changes. 
My data.json is good : 
> -sceneFile=\"${WIP_PATH}2016_PEYSSON\\01_MAYA\\VRscenes\\plateforme_ravin.vrscene\" 

same for the executable : 

> vray -sceneFile="${WIP_PATH}2016_PEYSSON\01_MAYA\VRscenes\plateforme_ravin.vrscene" -frames=2-2,1 -display=0 -autoClose=1 -verboseLevel=4 -showProgress=2

And my VRay output error : 

> No file "c:\temp\afanasy\${WIP_PATH}2016_PEYSSON\01_MAYA\VRscenes\plateforme_ravin.vrscene" exists 

This is strange cause I use that path map in Distributed Rendering with Vray over linux and Pc. renderers and it works fine. Afanasy must change my path somewhere and I don't know how to fix it.

**Comment by timurhai** [comment]
VRay (afrender client) is running on Windows?

**Comment by ramellij** [comment]
for testing yes

**Comment by timurhai** [comment]
windows environment variables should be %WIP_PATH%, not ${WIP_PATH}

**Comment by ramellij** [comment]
It works cause it changes my path to the windows location. I think it won't work with a linux client connected. 
I mean doing so my executable is now : 

> vray -sceneFile="\\Workstation2-pc\00_wip\2016_PEYSSON\01_MAYA\VRscenes

I use a path map so that my linux client see 

> "\mnt\00_wip\2016_PEYSSON\01_MAYA\VRscenes"

If I could launch the job with ${WIP_PATH} my VRay renderers would have no problem to locate the scene, in windows or linux.

**Comment by timurhai** [comment]
Now there is a forum for such discussions:
http://forum.cgru.info
