### ISSUE TITLE
 new job setting: max hosts

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#337]
This is useful to be able to limit the number of hosts the tasks are running on, but still allow for multiple tasks to run on the same host. example: max hosts = 5, so the job's tasks can run on 5 different hosts, but have 3 tasks on each host.
use case: plugins that are restricted in license count, do not use the CPU and RAM fully and thus allow > 1 task to run on a render leveraging the "capacity" sytem.

**Comment by lithorus** [comment]
It's already possible if you set "Max running tasks = 15" and "Max running tasks per host = 3"

**Comment by lithorus** [comment]
But you are really talking about service limits and not task limits. And what you really want is to track license count.
I think there has been a discussion about that in a previous issue. And one solution was to implement the ability to add secondary services (plugins) for blocks.

**Comment by lithorus** [comment]
https://github.com/CGRU/cgru/issues/311

**Comment by sebastianelsner** [comment]
While you are right with the new license feature (which would help), it would not help to balance jobs and allow mutltiple jobs run at the same time. with a max hosts setting i would be able to send 3 different jobs with max hosts set to 2 (with maybe 5 tasks on each) and still have lics left for others. as with the "plugin license" approach, one job might just grab all plugin licenses.

**Comment by lithorus** [comment]
I see your point.
It would actually make sense to have that option. Also just to make sure that 1 render job doesn't take up the whole farm at once. Especially with eg. Nuke which has to be split up with multiple tasks.
