### ISSUE TITLE
Host mask per task  or Task host dependency

### ISSUE THREAD

**Issue by sergiy-nazarenko** [CGRU/cgru#338]
Sometimes I need distribute or update some software on render nodes. 
It can be useful to have option to set task per host. That option allows me to restart some task in case of failed and I have guarantee that task restarted on particular host.

**Comment by sebastianelsner** [comment]
This is already covered via the "maintenance jobs", see "Job.setMaintanence()".

**Comment by sergiy-nazarenko** [comment]
Thanks
