### ISSUE TITLE
Render Pools.

### ISSUE THREAD

**Issue by timurhai** [CGRU/cgru#339]
It is a very popular feature request.
I want to discuss it on forum:
http://forum.cgru.info/viewtopic.php?f=26&t=19

I've created this forum for 2 main reasons:
 - To leave GitHub issues for code developing only.
    - now i will delete issues staring likely with "My Blender does not render ..." 
 - To join users that not using github.

**Comment by lithorus** [comment]
Perhaps this would be fixed after the added branches?
Eg. a main branch /poolA could have a specified hosts mask and /poolB could have another hosts mask specified. They can even overlap some machines if necessary.

**Comment by timurhai** [comment]
We are using pools about a year.
Assuming as done.
