### ISSUE TITLE
Stop afrender after idle timeout

### ISSUE THREAD

**Issue by mlesin** [CGRU/cgru#340]
In order to run `afrender` efficiently inside other task manager, such as slurm, for example, it's required to be able to exit from `afrender` process after it's being idle longer then specified timeout (it would be great if this timeout could be specified in config file, with possibility to override that value from command line)

**Comment by timurhai** [comment]
Easy to implement.
Will be done soon.

**Comment by lithorus** [comment]
We did something similar last year by modifying the shutdown script to kill it's parent process :

`kill -9 `ps --pid $$ -oppid=``

**Comment by mlesin** [comment]
@lithorus it's not a problem to kill afrender, main problem is to detect idle timeout is reached. And it's much harder to do from outside of afanasy

**Comment by lithorus** [comment]
@mlesin that is what the `wol_idlesleep_time` is for.

**Comment by lithorus** [comment]
And you should be able to tweak the `nimby_idle*` variables to ignore cpu/mem usage.

**Comment by mlesin** [comment]
@lithorus it's almost, but not the same. I need to count only time without any running tasks in afrender on machine, completely ignoring it's cpu/memory/network loads, which could be pretty high (running other tasks not counted by afrender)

**Comment by lithorus** [comment]
@mlesin I agree that the max_idle time would be helpful (would have helped when we did the similar thing in MOAB/torq :)), just saying that if you need something working now using the sleep features might also work.

How about getting an override for sleep command and also an option to ignore cpu/memory/network loads? I'm thinging that sometimes you want to ignore load and sometimes you want to exit instead of sleep....

**Comment by timurhai** [comment]
How do you think, who should make such decision server or client itself?
 - both cases an easy implementation )))

**Comment by timurhai** [comment]
Server can reload config, so you can change it for en entire farm in one command.
But if client - you can tune it for each client.
Also we can add such parameter to farm setup, and you can tune for a group of clients on server.

**Comment by timurhai** [comment]
- and server already counts free time, you can see it in afwatch

**Comment by mlesin** [comment]
I thought to make this on client, but on server it's also ok.
Important thing to have an ability to override it with command line, something like `afrender --exit_idle_timeout=3600`

**Comment by timurhai** [comment]
The global afanasy politics prefers server as brains, and clients just waiting for commands from server.
So i`ll make it on server.

You can override any config option, did you forgot about:
https://github.com/CGRU/cgru/issues/301
 :)

But if it will be on server, you can't override it with a command ))
So we should think again.

**Comment by timurhai** [comment]
Done on client side.
Later we can return to this issue.
It can be on both sides:
 - On client, defined in config.json and can be tuned via command/environment for each client.
 - On server, defined in farm.json for a group of hosts by names mask.
Both can be useful.
