### ISSUE TITLE
Parser Error not working as expected

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#348]
This is logging and referencing: http://forum.cgru.info/viewtopic.php?f=34&t=106#
(the user reporting it is working with me)

In my implemented nuke parser class I'm setting self.error=True. As I understood it, afanasy should then get a Parser Bad Result (PBR) error and restart this task. In my case, the task stays on the state RUN, but in the background the render process is killed. afrender output gives me: "Error: Parser bad result. Stopping task."
But instead of restarting the task, nothing happens (state stays on RUN) and after waiting some time, the afserver runs into the af_task_update_timeout threshold. Afrender tries to stop the Task, but fails with the message
AFERROR: RenderHost::stopTask: 0 tasks, no such task
TP: j6 b0 t4
Then after waiting some more the server runs into af_task_stop_timeout.

To reproduce

job.py
```
import sys
import af

job = af.Job('test')

mycmd = 'sleep 300'

block = af.Block('block', 'generic')
job.blocks.append(block)

block.setParser('myparser')
block.setCommand(mycmd, False)
block.setTasksName('task @#@')

for t in range(10):
    task = af.Task('#' + str(t))
    task.setCommand(mycmd)
    block.tasks.append(task)

job.setNeedOS('')

job.send()
```

myparser.py
```
from parsers import parser

class myparser(parser.parser):
    def __init__(self):
        parser.parser.__init__(self)
    
    def do(self, data, mode):
        self.error=True
```

**Comment by lithorus** [comment]
Might have something to do with the "sleep" command. If you change it to eg. "echo 'test1'". It seems to do what you would expect.
