### ISSUE TITLE
ejecting a task does not work when using "mask"

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#349]
commands:
af.Cmd().renderEjectTasks("")
afcmd reject $HOSTNAME

expected behaviour:
ejects the tasks on the current machine

problem:
it is not working, though a log entry is made

the commands create a jsons like:

{'action': {'type': 'renders', 'operation': {'type': 'eject_tasks'}, 'mask': 'stationstu0411.rise', 'user_name': 'sebels', 'host_name': 'stationstu0411.rise'}}

this does not work, but this does:

{'action': {'type': u'renders', 'operation': {'type': 'eject_tasks'}, 'user_name': 'sebels', 'host_name': 'stationstu0411.rise', 'ids': [1]}}

(where id 1 == stationstu0411.rise)

I guess this is related to using the "mask" parameter.

**Comment by timurhai** [comment]
Strange, but this works for me.
Also out artists using CGRU Keeper and ejecting tasks every morning.
Keeper uses the same:
https://github.com/CGRU/cgru/blob/master/utilities/keeper/nimby.py#L32

Also i just tried "afcmd reject $HOSTNAME" and it work too.
May be you have some mess with HOSTNAME?

ps
"text" parameter is not used now, but kept for compatibility.
https://github.com/CGRU/cgru/blob/master/afanasy/python/af.py#L1005
Later in a binary API, each action has some text just for log. It was useful sometimes.
But when we switched to JSON, i just dropped it temporary to complete JSON protocol faster.
I always thinking that sometime later i will add some comment for a JSON action too.

**Comment by sebastianelsner** [comment]
It seems this is happening sometimes because I do a rNIMBY and reject in immediate order and the server does not receive the second if there is lots of load. Testing more.

**Comment by sebastianelsner** [comment]
works. sorry for the noise.
