### ISSUE TITLE
set file pattern on numeric block

### ISSUE THREAD

**Issue by mehlukas** [CGRU/cgru#363]
The taskinfo["files"] parameter that is provided for the python framechecking only contains the first frame if the block is numeric.
Instead it should contain the file pattern, startframe, endframe and by.
This needs to be changed somewhere around https://github.com/CGRU/cgru/blob/master/afanasy/src/libafanasy/blockdata.cpp#L1166
Referencing to: http://forum.cgru.info/viewtopic.php?p=708

**Comment by mehlukas** [comment]
will you look into it or should I see if I can fix it?

**Comment by timurhai** [comment]
You can try.
I am quite busy for now.
I can do this, but in a several months.

**Comment by lithorus** [comment]
I'm currently looking at this. How should the output look like?

Eg.:
/tmp/test.#@@@@1,5,1#.exr
or
/tmp/test.#@@@@#.exr,1,5,1
?

I've currently added the taskInfo['frame_start'] and taskInfo['frame_finish'], not commited yet..
We can also used the getFiles() for the non-parsed/converted and the getParsedFiles() for the converted

**Comment by timurhai** [comment]
I think that the second variant is more simple to parse.
getFiles() is used to get files that was set on a job submission (and now there is an issue with a numeric block).
getParsedFiles() is used to get files that was parsed from the task output.
May be we should create getFilesPattern(), getFrameFirst(), .. (and so on) functions.
 - may be we will back to this issue later, for now i am busy with a branches solving, it is a huge issue, and i do not want to spread on others (that are not very simple too)

**Comment by lithorus** [comment]
Will leave it for now. I also noticed it broke alot of things :)

**Comment by timurhai** [comment]
On a numeric blocks
_command_task_ and _files_task_ will be empty
_command_block_ and _files_block_ will contain patterns

I just want to remind, that not-numeric blocks (with tasks) has patterns for tasks too.
Task can contain just changing part of an entire command that can be stored once in a block pattern.

**Comment by timurhai** [comment]
I am already about to implement it.
Much simple and clean.
Couple of hundreds c++ code lines replaced by tens Python code line.
Much simple to manipulate string patterns via Python re module.
More easy to test, customize.

**Comment by timurhai** [comment]
We are using new 2.3.0 Afanasy at work since 1 Oct. Everything is fine. Soon there will be a 2.3.0 release.
