### ISSUE TITLE
PAID FEATURE REQUEST - multi-site job balancing - maybe add a "location" property to a user and modify the user-jobqueue to work per location instead of a single user

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#369]
Hi Timur,

first of all I must say that this is a paid feature request! No need to do it for free!

This is just a question about how hard it would be to add the concept of multi-site (or per-department)  user-balancing.

Our idea would be to get away from simple per-user balancing and introduce a new more flexible way to balance.

I think that at the moment there is one "jobqueue" per user and in my opinion there should be an option where one could choose which "criteria" is used to create the queue.
for example a User can have two additional properties called "department" or "location" and in the global afanasy config we would be able to choose based on which property the "user-queue" is being create:
1. username
2. department
3. location

Do you have the time to implement this in the near future (not asap) if we pay you for that? We can discuss the price in private.

Thanks in advance!
Oli

**Comment by ultra-sonic** [comment]
Edit: maybe the new properties need to be on the job and NOT on the user

**Comment by ultra-sonic** [comment]
If the property is in the job we just call it "queue" which defaults to username if not set otherwise

**Comment by timurhai** [comment]
Hi.
I have a plan to create render "pools" and job "branches".
Pool - just a group of some renders or child pools.
Branch is like a path, for example "/vfx/projectA", "/edit/projectB".
Path can have any depth, not just a department and projects.
Branch can be assigned to pools.
Free renders will be balanced between each path "folder".

For now i am writing non-blocking IO for linux afserver, it will be based on epoll().
And also i do not have much time right now, as we have too much work in out studio.
After non-blocking io, i will start to implement branched balancing.
I think that we see some results at the end of this year.

**Comment by ultra-sonic** [comment]
end of the year sounds awesome to me....good to see you have something
similar to the feature I requested on your list already...keep up the great
work!

**Comment by timurhai** [comment]
Just stated to describe a new Afanasy node type - Branch (that will hold a set of jobs).
This year there is no chance test new jobs solving.
There is much work to do.

**Comment by ultra-sonic** [comment]
Hi Timur,

I'm glad you didn't forget about my request! Looking forward to the beginning of next year then!

Cheers
Oliver

**Comment by timurhai** [comment]
Hi!
This is not only your request, i heard about similar requests later. And now our studio has the same issue too )

**Comment by ultra-sonic** [comment]
Hey Timur,
hope you are doing fine! Do you think you might find some time to look into this anytime soon?
Cheers
Oliver

**Comment by timurhai** [comment]
Hi!
I am coding it (jobs branches solving) right now.

**Comment by ultra-sonic** [comment]
That sounds awesome! Can't wait!

**Comment by timurhai** [comment]
Hi.
It is just implemented:
https://github.com/CGRU/cgru/commit/ceb0991068a269d7899c2f9d9ace6dffc76da5a0

But for now users does not play any role.
Soon there will be branch solving options, what to solve and how to solve: jobs order, jobs priority or users.

**Comment by ultra-sonic** [comment]
That sounds promising! Thank you for that.

> Soon there will be branch solving options, what to solve and how to solve:
> jobs order, jobs priority or users.
>
What about solving per location? e.g. Moscow,Berlin,London? Will that be
doable with the current implementation?

Thanks
Oli

>

**Comment by timurhai** [comment]
You can create any branches hierarchy:
/ Milky Way Galaxy / Solar System / Earth / Goods / Drinks / Beer

**Comment by ultra-sonic** [comment]
that sounds pretty sophisticated!

From what you wrote before I did not understand if the feature can be
tested already or not. Can you please elaborate again on what's still
missing?

**Comment by timurhai** [comment]
You can test it since that commit: https://github.com/CGRU/cgru/commit/ceb0991068a269d7899c2f9d9ace6dffc76da5a0

But it is not recommended to use it at real work before the next release.

**Comment by timurhai** [comment]
Hi.
You can look at:
http://cgru.info/afanasy/branch

Also i want not directly code-related questions to discuss on a forum:
http://forum.cgru.info/viewtopic.php?f=4&t=1486
As not all Afanasy interested people are using GitHub.

**Comment by timurhai** [comment]
This is done.
And we already work with it.
In release, it will be available since 2.3.0.

**Comment by ultra-sonic** [comment]
Awesome! Thanks so much Timur! Will try to merge it into our production server asap.

**Comment by ultra-sonic** [comment]
hey timur,
how is "per-user" job-solving affected by this feature? is it obsolete now or is this solved after the branches are taken into account?

Thanks
Oliver

**Comment by timurhai** [comment]
Hi.
You can choose to solve users or jobs directly:
http://cgru.info/afanasy/branch#branch_flags

**Comment by ultra-sonic** [comment]
awesome! thanks for the clarification!
