### ISSUE TITLE
Afserver crashes when starting a multihost job

### ISSUE THREAD

**Issue by mehlukas** [CGRU/cgru#371]
The Afserver runs into segmentation fault, after I started a Job that contains a multihost block.
After it crashed, you cannot restart the server again, it immediately crashes until you manually delete the job folder in /var/tmp/jobs/.

This is my job submission script:
```
import af
job = af.Job('sometestjob')
cmd = "python -c \"for i in range(100): print 100 * 'xxxxxxxxxxxxxx'+ 'PROGRESS: '+str(i)+'%';import time;time.sleep(5)\""
block = af.Block("block")
block.setCommand(cmd)

block.setNumeric(1, 100)

block.setMultiHost(1, 3, 0, master_on_slave=True, service="", service_wait=0)
block.setSlaveLostIgnore()

job.blocks.append(block)
job.offLine() # crash happens after starting the job
job.send()
```

I tried some variations in the arguments of block.setMultiHost(..), but everything results in a crash.

Thanks for your help!

--
CGRU version = '2.2.0'
Afanasy build revision = 'b03edf8bdb6da3ea35145bf4f587cbccc98fa91b'
Python version = '2.6.6'
GCC version = '4.4.7'

**Comment by timurhai** [comment]
Hi.
I reproduced this bug with the job you've provided.
Will find the error.

**Comment by timurhai** [comment]
Now server does not hung.
But afrender created from current master does.
I will discover this error too.
May be this error is just in my testing task and service.
You can make the same fix in 2.2.0 afserver code to test.

**Comment by yannci** [comment]
I unlikely have to reopen the ticket. We upgraded to afanasy version 2.3.0 in the mean time and the server still crashes on sending multihost tasks with a segmentantion fault. Your previous mentioned changes are applied but it's still not working.

It tried to submit mantra multihosts jobs aswell as the script posted by mehlukas in the inital post. Same results. If you need any further information don't hesitate to come back to me.

Thanks in advance,
Yannic

**Comment by timurhai** [comment]
Hi.
Fixed. Again.
Sorry for this bug, after branches were added, resources counts were changed, again, and i made the same bug.
( it seems that code should be better to avoid such variables mix )

**Comment by timurhai** [comment]
At least next time i should choose more informative variables names.

**Comment by yannci** [comment]
Thank you very much!
We'll try it.
