### ISSUE TITLE
C4D issue

### ISSUE THREAD

**Issue by ramellij** [CGRU/cgru#375]
Hi Timur, 

I'm trying to render with C4D and see what I get from output task : 

```
C4D_EXEC=C:\Program Files\MAXON\CINEMA 4D R18\CINEMA 4D.exe
La syntaxe du nom de fichier, de r�pertoire ou de volume est incorrecte.
```
meaning the path's syntax is incorrect. 
Must be a simple thing that I don't get :(

Thanks for your help
JR

**Comment by timurhai** [comment]
This is some mistake in windows cmd script, may be some path is incorrect, may be some path should be set in "commas characters". I do not have MS Windows and C4D by hand. You should dig the problem deeper.

Also such questions better to ask on forum:
http://forum.cgru.info/index.php

**Comment by ramellij** [comment]
I found the solution here : 
http://forum.cgru.info/viewtopic.php?f=33&t=270&p=787&hilit=C4D#p787

Thanks
