### ISSUE TITLE
plugin issue after fx error

### ISSUE THREAD

**Issue by samytichadou** [CGRU/cgru#390]
Hi, and first of all, thanks for this wonderful tool ! i'm conducting some test on cc2015 afx in order to setup a farm for a small postproduction company, and the afx plugin is giving me some hard time.
The job sent from ae gives "avoid error" 
here's the command line ran : 
aerender -project "C:\Users\tonton\Desktop\test afanasy.aep.test%20afanasy.aep.1119-174019-930.aep" -s 0 -e 4 -i 1 -comp "Composition 1"
all my tests so far are conducted on a single machine as server, worker, and client
thanks !

**Comment by predat** [comment]
Hi @samytichadou,
Is your "Composition 1" in the render queue ?
Where this error come from (extendscript or cgru) ?
Afanasy plugin does not set RStemplate, OMtemplate or output path... your need to provide those informations from the render queue.

**Comment by samytichadou** [comment]
hi @predat, i just figured what the problem was, it seems to be the name of the template created, each space in name are replaced automatically by "%20" in the actual file, but not in the command line. Do you have an idea how to correct this ? (i'm no coder, but i could take a look in the script when i have some spare time)

**Comment by timurhai** [comment]
Hi.
Problem is in the temporary scene name.
There is some job submission steps:
 - AE script constucts a command for afjob.py to send with ' -tempscene' argument:
https://github.com/CGRU/cgru/blob/master/plugins/afterfx/Afanasy.jsx#L111
 - afjob.py asks cgruutils to copy scene file to some temp file:
https://github.com/CGRU/cgru/blob/master/afanasy/python/afjob.py#L452
 - cgruutils constucts a temp name and copy:
https://github.com/CGRU/cgru/blob/master/lib/python/cgruutils.py#L348
As you see it tries to:
copyFile += '.' + jobName
But in fact you have:
copyFile += ' ' + jobName
Why you system insetrs a space istead of a dot?
May be some locale problem.
But, if so, why other dots are dots and not spaces?
I do not know. Try to experiment with "copyFile += '.' + jobName" line.

Solution2:
remove from Afanasy.jsx this line:
cmd += ' -tempscene';
But it will render current scene. And if you are planning to continue working with it, while render goes, your render sequence will change as you save (update) scene. In this case, you can save render scene within AE application by hands (not automatically).

btw
CGRU forums appeared:
http://forum.cgru.info/
With a section for each software.
Such question better to ask there. As others (not-github) users can find solution when forum will have enough data. Lets keep github for a code developing only.

**Comment by samytichadou** [comment]
@timurhai thank you very much for making this clearer ! i'll take a look on that with your explanation !
my bad for the github instead of forum !
