### ISSUE TITLE
af.Cmd.monitorUnregister() error response

### ISSUE THREAD

**Issue by paulwinex** [CGRU/cgru#392]
Non critical problem.
Code:
```
cmd = af.Cmd()
# register monitor
id = cmd.monitorRegister()
# id = 2
# unregister monitor
cmd.monitorUnregister(id)
# monitor is deleted but catch error!
```
```
afnetwork.py: Received data:

JSON loads error:
No JSON object could be decoded
```
Windows 10, cgru 2.2.3, python 2.7

**Comment by timurhai** [comment]
Server does not send anything back on "deregister" operation.
Almost all actions has some answer.
But this action can come on web page close, to supress errors in afserver log, it just sends nothing.
