### ISSUE TITLE
Cinema 4D setup script (.cmd) error.

### ISSUE THREAD

**Issue by alexinc2000** [CGRU/cgru#394]
During start rendering via Cinema 4D i get mistake:
"python_init.py got Copied"
C4D_EXEC=C:\Program Files\MAXON\CINEMA 4D R18\CINEMA 4D.exe
""CINEMA 4D.exe"" don't intenal or external programm or cmd files.

**Comment by alexinc2000** [comment]
Fix problem
in \cgru\software_setup\setup_c4d.cmd change 2 strings
set APP_EXE=%APP_DIR%\CINEMA 4D 64 Bit.exe
if not exist "%APP_DIR%\%APP_EXE%" set "APP_EXE=%APP_DIR%\CINEMA 4D.exe"

**Comment by timurhai** [comment]
Does 32 bit Cinema4D still exists?
Does anybody going to it?

If not, better to simplify setup script by removing 32bit version search.

**Comment by alexinc2000** [comment]
I think so.
In Cinema 4D r18 i don't see any else files except main Cinema 4d.exe

**Comment by timurhai** [comment]
Closed by https://github.com/CGRU/cgru/pull/395
