### ISSUE TITLE
Render not register in CGRU afanasy 

### ISSUE THREAD

**Issue by phangurram** [CGRU/cgru#396]
Hi render not register . in afanasy cgru.
renderer running but its not register with server .
till morning its working fine. suddenly its not working.
i tried creating new user on windows and tried.  not working .
can some one help me on this how to get the render work again normally.

**Comment by timurhai** [comment]
Hi.
There is a forum for such and any questions:
http://forum.cgru.info/index.php
GitHub we use for a code development only.
