### ISSUE TITLE
AFERROR: af::pathMakeDir - "c:/temp/afanasy\tasks"

### ISSUE THREAD

**Issue by skrmn** [CGRU/cgru#404]
Hi!
I have a strange issue which is coming from 2.2.2 and I got it on 2.2.3 as well.
It starts few weeks ago.
Please see raw output below.
The task couldn't start on render because "c:\temp\afanasy" dir doesn't exist.
If I creating it manually, resetting error hosts and restarting it works.
But sometime later the situation repeats.

Afanasy 2.2.3
Render OS: Windows 10, 1709 (16299.248) 
Afanasy SRV: under linux in VmWare.

Any help will be appreciated.

There are also some issues than task don't start and I can't check error because of no output ....
ERROR: Can't get file:
/var/tmp/afanasy/jobs/0/296.TIT-BEG_v04.nk-Write8-2/tasks/0.8/output/1.txt
No such file or directory

This errors are not related to service type, the same happens with Cinema 4D....

`Tue 27 Feb 11:38.31: INFO    Started PID=6828 [hbatch_mantra:1000] kostya: PSR_0010_render_v03[foam_extra][frame 236-238]
Tue 27 Feb 11:46.59: INFO    Parser notification.
Tue 27 Feb 12:00.46: INFO    Finished PID=6828: Exit Code=0 Status=0
AFERROR: af::removeDir: Can't open folder:
c:/temp/afanasy\tasks\295.0.27_34No such file or directory

AFERROR: af::pathMakeDir - "c:/temp/afanasy\tasks": No such file or directory

Tue 27 Feb 12:00.47: INFO    Started PID=3908 [hbatch_mantra:1000] kostya: PSR_0010_render_v03[foam_extra][frame 269-271]
Tue 27 Feb 12:06.41: INFO    Parser notification.
Tue 27 Feb 12:15.43: INFO    Finished PID=3908: Exit Code=0 Status=0
AFERROR: af::removeDir: Can't open folder:
c:/temp/afanasy\tasks\295.0.38_35No such file or directory

AFERROR: af::pathMakeDir - "c:/temp/afanasy\tasks": No such file or directory

Tue 27 Feb 12:15.44: INFO    Started PID=7556 [hbatch_mantra:1000] kostya: PSR_0010_render_v03[foam_extra][frame 299-300]
Tue 27 Feb 12:22.56: INFO    Parser notification.
Tue 27 Feb 12:29.04: INFO    Finished PID=7556: Exit Code=0 Status=0
AFERROR: af::removeDir: Can't open folder:
c:/temp/afanasy\tasks\295.0.48_36No such file or directory

AFERROR: af::pathMakeDir - "c:/temp/afanasy\tasks": No such file or directory

Tue 27 Feb 13:23.49: WARNING Working directory does not exist:
C:\Users\anton
AFERROR: Failed to start a process
AFERROR: af::removeDir: Can't open folder:
c:/temp/afanasy\tasks\296.0.8_37No such file or directory

AFERROR: af::pathMakeDir - "c:/temp/afanasy\tasks": No such file or directory

Tue 27 Feb 13:23.51: WARNING Working directory does not exist:
C:\Users\anton
AFERROR: Failed to start a process
AFERROR: af::removeDir: Can't open folder:
c:/temp/afanasy\tasks\296.0.8_38No such file or directory

AFERROR: af::pathMakeDir - "c:/temp/afanasy\tasks": No such file or directory

Tue 27 Feb 13:23.53: WARNING Working directory does not exist:
C:\Users\anton
AFERROR: Failed to start a process
AFERROR: af::removeDir: Can't open folder:
c:/temp/afanasy\tasks\296.0.8_39No such file or directory

AFERROR: af::pathMakeDir - "c:/temp/afanasy\tasks": No such file or directory

Tue 27 Feb 14:13.14: INFO    Started PID=1464 [hbatch_mantra:1000] kostya: PSR_0010_render_v03-1[foam_extra_end][frame 250-251]
Tue 27 Feb 14:16.49: INFO    Parser notification.
Tue 27 Feb 14:19.16: INFO    Finished PID=1464: Exit Code=0 Status=0
AFERROR: af::removeDir: Can't open folder:
c:/temp/afanasy\tasks\297.0.0_40No such file or directory

AFERROR: af::pathMakeDir - "c:/temp/afanasy\tasks": No such file or directory

Tue 27 Feb 14:19.17: INFO    Started PID=6868 [hbatch_mantra:1000] kostya: PSR_0010_render_v03-1[foam_extra_end][frame 274-275]
Tue 27 Feb 14:24.04: INFO    Parser notification.
Tue 27 Feb 14:27.42: INFO    Finished PID=6868: Exit Code=0 Status=0
AFERROR: af::removeDir: Can't open folder:
c:/temp/afanasy\tasks\297.0.12_41No such file or directory`

**Comment by timurhai** [comment]
Hi.
May be someone (process) deletes c:/tamp/afanasy
May be some permission problems.
You can also try to change store folder:
https://github.com/CGRU/cgru/blob/master/afanasy/config_default.json#L49
On some other folder, that may be is more easy to control.

**Comment by timurhai** [comment]
btw
such questions better to ask on forum.

**Comment by skrmn** [comment]
Thanks. 
Sorry for posting here, will continue on forum.
