### ISSUE TITLE
Documentation not at par with default configuration

### ISSUE THREAD

**Issue by abuisine** [CGRU/cgru#405]
on http://cgru.info/afanasy/render.html, the documentation says :
```
cmd_shell
Shell command used to launch any other command. It is important that it will be used by render to launch task process. If not defined build-in values are used:
UNIX: "/bin/bash -c"
MS Windows: "cmd.exe /c"
```
whereas the default cgru/config_default.json contains :
```
	"OS_unix":{
		"cmd_shell":"/bin/sh -c"
	},
```
putting bash as default could not work on some systems, so I would suggest to rather modify the documentation

**Comment by timurhai** [comment]
Hi. Yes, now it fixed and soon will be updated on the site.
Previously **/bin/bash** was the default shell, but later some people asked me to change to **/sh**, as the was no **bash** on their renders. But, **sh** exists on any UNIX-like system.
