### ISSUE TITLE
Having this error when using meArnoldRender.py

### ISSUE THREAD

**Issue by tws0002** [CGRU/cgru#406]
hi,

Having this error when using meArnoldRender.py
```
sys.platform = win32 self.os = win
# Error: ValueError: file \cgru\plugins\maya\afanasy\meArnoldRender.py line 181: No object matches name: defaultArnoldRenderOptions.binaryAss # 
```

Help!
Desmond

**Comment by lithorus** [comment]
Could be related to this :
https://arnoldsupport.com/2015/12/09/mtoa-creating-the-defaultarnold-nodes-in-scripting/

Did you try it after opening the render settings dialog?

**Comment by ymesh** [comment]
This problem were introduced after Arnold become built-in renderer in Maya...
defaultArnoldRenderOptions will be created after opening once the render settings.
