### ISSUE TITLE
Natron Afanasy node doesn't work

### ISSUE THREAD

**Issue by tobkum** [CGRU/cgru#409]
When trying to add an Afanasy node in Natron via the CGRU - Afanasy node (F10) menu, nothing happens.
![image](https://user-images.githubusercontent.com/16955378/41263917-34c55c08-6dea-11e8-8c5d-e29dc03a9825.png)

I can load the examples shipping with cgru and see the nodes in there though.
![image](https://user-images.githubusercontent.com/16955378/41263930-474e4c68-6dea-11e8-8b56-03cd11375027.png)

So I'm unable to add own Afanasy nodes, but I can see the ones that are saved within a Natron project.

**Comment by lithorus** [comment]
It should be fixed in the repo now.
It was due to the plugin not loading because a comment was missing the in the header of the file...

**Comment by lithorus** [comment]
Were you able to test if it works?

**Comment by tobkum** [comment]
Sorry, missed you answer - no, haven't tested, but will do asap!

**Comment by tobkum** [comment]
Sorry for not reporting back earlier - issue is fixed now. Thanks!
