### ISSUE TITLE
Is it possible to set host capacity using Afwatch GUI?

### ISSUE THREAD

**Issue by morevnaproject** [CGRU/cgru#413]
I am running afanasy 2.2.3.
I may mistake, but in previous versions it was possible to set host capacity right from Afwatch gui. Can't find this function anymore.

**Comment by timurhai** [comment]
Hi.
From some version, all host changes are available only in admin mode, in "Administrate" sub-menu.

btw
From some time when project got forums:
http://forum.cgru.info
Such question better to ask on forum.
GutHub now standing for code development only.
