### ISSUE TITLE
is there an ETA for the next official release?

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#414]
Hi Timur,
is there an ETA for the next official release?

**Comment by ultra-sonic** [comment]
Nice! So 2.3.0 is already there, but what does "Not released" mean or
better: When will it be released?
Thanks
Oliver

**Comment by timurhai** [comment]
In a couple of month.
Now i am processing the latest 2.3.0 issue:
https://github.com/CGRU/cgru/issues/363

**Comment by timurhai** [comment]
Hi.
Sorry for a delay, i was on vocation.

Before that issue:
https://github.com/CGRU/cgru/issues/363
We are using 2.3.0 with branches for a couple of months at work.
And it seems that it is enough stable for production.
But after that latest issue changes:
https://github.com/CGRU/cgru/commit/c9c9df0e4d83f061831a04d04d0a56b161bef0c0
When command pattern frame numbers replacement moved from afserver (c++) to afrender (Python service class) it was not well tested. But i will do this next days and later will update all it at my work.

**Comment by ultra-sonic** [comment]
thx timur!
so you say that we could test the master at this point in time:
142c61477b06f948743b8406490c82b9d6cdb6e2

cheers
Oli

**Comment by timurhai** [comment]
Yes.

**Comment by timurhai** [comment]
But note, that the next huge commit breaks network compatibility.
Server&clients at that point will not work with any 2.3.x release.
