### ISSUE TITLE
Threading control for Nuke render

### ISSUE THREAD

**Issue by yiminfantw** [CGRU/cgru#418]
Hi,

By the look at _software_setup/setup_nuke.*_ script, the _NUKE_AF_RENDERTHREADS_ var declaration is commented and there is no implementation for controlling threading (defining **-m** argument) by capacity(or other) parameter in _plugins/nuke/scripts/cgru/afanasy.py_. Just wondering is there any reason not to do so just like what's implemented in Houdini plugin?

Cheers,
YiMin

**Comment by timurhai** [comment]
Hi.
Sorry for a delay, i was on vocation.

It seems that it was occasionally commented instead of deletion, as now i can't find where _NUKE_AF_RENDERTHREADS_ variable is used.

You want use variable capacity?
Or just limit render threads on the entire farm? Or per job (submission parameter)?

**Comment by yiminfantw** [comment]
Yes, what I'm looking for is limit threads per job by capacity parameter as what was implemented in Houdini plugin. Thx :)
