### ISSUE TITLE
Job.setEnv() wrong "in" test

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#420]
https://github.com/CGRU/cgru/blob/d38556004cc99eaf91020592704443be43efa3e2/afanasy/python/af.py#L286

the test should be:

 `if "environment" not in self.data:`

the old line would only allow ONE env var to be set at all.

**Comment by timurhai** [comment]
Hi.
Yes! And i only used it for one variable!
It should be fixed.

**Comment by timurhai** [comment]
Great that you noticed it right now. It will be fixed in 2.3.0, that i am about to create.
