### ISSUE TITLE
errors during compilation centos-7.4 qt-5.11 in custom path

### ISSUE THREAD

**Issue by utoplenick** [CGRU/cgru#421]
```
[ 96%] Building CXX object fermer/CMakeFiles/afermer.dir/a-vfx/stuff/programs/linux/cgru-2.3.0/afanasy/src/fermer/Managers/Service/RadiolocationService.cpp.o
/a-vfx/stuff/programs/linux/cgru-2.3.0/afanasy/src/fermer/Managers/Service/RadiolocationService.cpp: In member function ‘bool afermer::RadiolocationService::get(QList<TaskObject>&, int)’:
/a-vfx/stuff/programs/linux/cgru-2.3.0/afanasy/src/fermer/Managers/Service/RadiolocationService.cpp:232:74: error: ‘class af::TaskExec’ has no member named ‘getCommand’
         TaskManager::Ptr task_container = TaskManager::create( taskexec->getCommand(), taskexec->getNumber() );
                                                                          ^
/a-vfx/stuff/programs/linux/cgru-2.3.0/afanasy/src/fermer/Managers/Service/RadiolocationService.cpp: In member function ‘void afermer::RadiolocationService::jobsUpdate(bool)’:
/a-vfx/stuff/programs/linux/cgru-2.3.0/afanasy/src/fermer/Managers/Service/RadiolocationService.cpp:755:80: error: ‘const class af::BlockData’ has no member named ‘getTasksMaxRunTime’
             job->m_resource_map["tasks_max_runtime"] = QString::number( block->getTasksMaxRunTime() );
                                                                                ^
/a-vfx/stuff/programs/linux/cgru-2.3.0/afanasy/src/fermer/Managers/Service/RadiolocationService.cpp: In member function ‘void afermer::RadiolocationService::usersUpdate()’:
/a-vfx/stuff/programs/linux/cgru-2.3.0/afanasy/src/fermer/Managers/Service/RadiolocationService.cpp:1447:32: error: ‘class UserAf’ has no member named ‘getRunningTasksNumber’
         int tasks_size = user->getRunningTasksNumber();
                                ^
make[2]: *** [fermer/CMakeFiles/afermer.dir/a-vfx/stuff/programs/linux/cgru-2.3.0/afanasy/src/fermer/Managers/Service/RadiolocationService.cpp.o] Error 1
make[1]: *** [fermer/CMakeFiles/afermer.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by predat** [comment]
It look like *fermer* code is a little bite outdated...
There is not anymore ´getRunningTaskNumber’ méthod in user.h.

For instance, to compile afanasy without afermer, you need to pass ´—nofermer’ parameter to build.sh script...

**Comment by utoplenick** [comment]
trying to compile and getting such errors:
`[ 99%] Building CXX object fermer/CMakeFiles/afermer.dir/mnt/users/arifulov/home/repos/cgru/afanasy/src/fermer/main.cpp.o
[100%] Building CXX object fermer/CMakeFiles/afermer.dir/afermer_automoc.cpp.o
[100%] Linking CXX executable /mnt/users/arifulov/home/repos/cgru/afanasy/bin/afermer
CMakeFiles/afermer.dir/mnt/users/arifulov/home/repos/cgru/afanasy/src/watch/wndtask.cpp.o: In function `WndTask::createTab(QString const&, QWidget**, QAfTextWidget**)':
wndtask.cpp:(.text+0x10b): undefined reference to `QAfTextWidget::QAfTextWidget(QWidget*)'
CMakeFiles/afermer.dir/mnt/users/arifulov/home/repos/cgru/afanasy/src/watch/wndtask.cpp.o: In function `WndTask::updateProgress(af::TaskProgress const&)':
wndtask.cpp:(.text+0x40e0): undefined reference to `ButtonDblClick::setEnabled(bool)'
wndtask.cpp:(.text+0x40fb): undefined reference to `ButtonDblClick::setEnabled(bool)'
wndtask.cpp:(.text+0x44d2): undefined reference to `ButtonDblClick::setEnabled(bool)'
wndtask.cpp:(.text+0x4503): undefined reference to `ButtonDblClick::setEnabled(bool)'
CMakeFiles/afermer.dir/mnt/users/arifulov/home/repos/cgru/afanasy/src/watch/wndtask.cpp.o: In function `WndTask::WndTask(af::MCTaskPos const&, ListTasks*)':
wndtask.cpp:(.text+0x55ed): undefined reference to `ButtonDblClick::ButtonDblClick(QString const&, QWidget*)'
wndtask.cpp:(.text+0x5633): undefined reference to `ButtonDblClick::setEnabled(bool)'
wndtask.cpp:(.text+0x568f): undefined reference to `ButtonDblClick::ButtonDblClick(QString const&, QWidget*)'
wndtask.cpp:(.text+0x56d5): undefined reference to `ButtonDblClick::setEnabled(bool)'
collect2: error: ld returned 1 exit status
`
system Centos 7, tried qt-5.11 and qt-5.9.4

**Comment by timurhai** [comment]
It seems that you have compiled it.
That errors are at linking stage.
Try ti include this file:
https://github.com/CGRU/cgru/blob/master/afanasy/src/watch/buttondblclick.cpp
in here:
https://github.com/CGRU/cgru/blob/master/afanasy/src/project.cmake/fermer/CMakeLists.txt

**Comment by utoplenick** [comment]
> Try ti include this file:
> https://github.com/CGRU/cgru/blob/master/afanasy/src/watch/buttondblclick.cpp
> in here:
> https://github.com/CGRU/cgru/blob/master/afanasy/src/project.cmake/fermer/CMakeLists.txt
after including 
https://github.com/CGRU/cgru/blob/master/afanasy/src/watch/buttondblclick.cpp and 
https://github.com/CGRU/cgru/blob/master/afanasy/src/watch/qaftextwidget.cpp
linking passed without errors

**Comment by utoplenick** [comment]
It works

**Comment by timurhai** [comment]
Can you create a pull request with you fix?

**Comment by utoplenick** [comment]
Yes, I think I`ll do it today

**Comment by timurhai** [comment]
Thank you!
