### ISSUE TITLE
per host property

### ISSUE THREAD

**Issue by samytichadou** [CGRU/cgru#423]
Hi, sorry for posting here more a question than an issue, cgru forum seems laggy these days...
I'm wondering how to create a custom property per worker machine which can be easily changed on the fly, i managed to get a custom prop per farm using farm.json file, but not per worker...
cheers !

**Comment by timurhai** [comment]
Hi.
You can use a more specific pattern mask, that will match a single worker:
https://github.com/CGRU/cgru/blob/master/afanasy/farm_example.json#L34

btw
What is wrong with the forum?

**Comment by samytichadou** [comment]
Hi thanks for the quick answer, i see, i'll try asap ! 
About the forum i'm not sure, i wasn't able to use my account anymore, i had to create another one, and older posts from this topic i created were deleted : http://forum.cgru.info/viewtopic.php?f=34&t=1073

I tried to post in it instead of here, but no luck, even with new account, so that's why i asked you here

**Comment by timurhai** [comment]
Hi.
There lots of spamming bots on forums.
Periodically i clear users with no posts.
There are 30-100 user registrations per day!!! It is a problem. (they have strange emails and logins)
So i think, i occasionally deleted your account after http://forum.cgru.info/viewtopic.php?f=34&t=1073
And next time, when you registered again, and have no posts yet, i deleted you account as an account with no posts.
Sorry for this!

I should apply some custom registration form, with some simple question for example, for spam bots protection. And will think up this soon.

For now you can re-register again and post some answer here:
http://forum.cgru.info/viewtopic.php?f=34&t=1073
And i will remember you.

**Comment by samytichadou** [comment]
perfect thanks, no problem, i understand that you have to clear users sometimes and i'm not so active on forums, i thought forum was broken somehow.
cheers !
(my new account username is samytichadou, don't erase me ;) )

**Comment by timurhai** [comment]
you should write some post to be active, for example here:
http://forum.cgru.info/viewtopic.php?f=34&t=1073
or create a new topic

**Comment by timurhai** [comment]
Hi.
I also added a question in the registration form, to prevent bots.
Can you register now, again?
And say something here:
http://forum.cgru.info/viewtopic.php?f=34&t=1073

**Comment by samytichadou** [comment]
done, perfect thanks ! i'll complete the post to be sure to be active !
cheers !

**Comment by timurhai** [comment]
Hi.
I see that you have registered. But, please, write something to be active!

**Comment by samytichadou** [comment]
done ! thanks
