### ISSUE TITLE
2.3.0 blender error when sending job

### ISSUE THREAD

**Issue by ialebedev** [CGRU/cgru#426]
![screenshot_20181108_161751](https://user-images.githubusercontent.com/16067800/48210183-e5c84e80-e387-11e8-8142-0ebd78f9be64.png)

Here is the screenshot of an error.
Debian 9 64bit, Blender 2.79b

**Comment by predat** [comment]
Hi @ialebedev,

Thank you for submitting this...
I just commit a Fix in the master branch.

What you can for now is modifing operator.py at line 226 to remove True argument of the job.output method.

**Comment by predat** [comment]
@ialebedev any news about this ?
Can i close the issue ?

**Comment by ialebedev** [comment]
Yes U can

Thanks


ср, 5 дек. 2018 г. в 15:00, predat <notifications@github.com>:
