### ISSUE TITLE
3dsmax VRAY Next No Progress Messages

### ISSUE THREAD

**Issue by eoyilmaz** [CGRU/cgru#430]
With 3dsmax VRay Next GPU there are no progress messages shown on the job outputs page.

When running the command manually from the command line there are some progress messages, but they are not shown in the jobs output page.

**Comment by timurhai** [comment]
Hi.
I am not using Max and VRay (and has no ability to test it).
I see here max.py and vray.py parsers:
https://github.com/CGRU/cgru/tree/master/afanasy/python/parsers
I think there also should be max_vray.py parser class that inherit both, like:
https://github.com/CGRU/cgru/blob/master/afanasy/python/parsers/hbatch_mantra.py
 - to calculate frame (it task renders several frames) and per frame progress.

To it seems that there is lack max+vray support in the project as such file still does not exist.

**Comment by eoyilmaz** [comment]
Oh I see, ok I'll implement that as per your direction 👍
