### ISSUE TITLE
Job.setWaitTime() does not set "time_wait" for job

### ISSUE THREAD

**Issue by yannci** [CGRU/cgru#433]
When submitting a job via the python API the setWaitTime() method of the Job does not set "time_wait"

If I print the job.data "time_wait" is present, but after sending the job it has no "time_wait" on the job.

This issue occurs in afanasy 2.2.3

**Comment by timurhai** [comment]
It should. And it definitely works in 2.3.0.
 - i do not see any recent changes for that line:
https://github.com/CGRU/cgru/blob/master/afanasy/src/libafanasy/job.cpp#L70

**Comment by lithorus** [comment]
I can re-produce the error with this :
`job.setWaitTime(time.time()+5000)`
however if I convert it into an int it works :
`job.setWaitTime(int(time.time()+5000))`

**Comment by lithorus** [comment]
Fixed in 55b538f204722fd6f071873807b7510e2441898c

**Comment by yannci** [comment]
If tried it with time.time(), too. Haven‘t thought about the cast to int, to be honest. 

Thx for the fix!

**Comment by lithorus** [comment]
I'm gonna close this then
