### ISSUE TITLE
Nimby when users logged in

### ISSUE THREAD

**Issue by lithorus** [CGRU/cgru#439]
It would be useful for workstations to automatically go nimby when users log in and automatically go free when all are logged out. 

It seems that afrender already tracks logged in users.

Also to be able to ignore some users (eg. root or render)

**Comment by timurhai** [comment]
Hi.
May be it can do some other application.
CGRU Keeper can be in some user session "auto run" list.
We can add some "Set Nimby On Start" and "Set Free On Exit" checkboxes to Keeper tray menu.
( our studio already starting keeper at logon, it shows afrender status: online, busy, nimby )

**Comment by sebastianelsner** [comment]
We solved this via the gnome display manager pre/post session scripts which just do a simple "afcmd rNIMBY $HOSTNAME"

**Comment by lithorus** [comment]
We will probably also have to do some pre/post sessions script for the time being it would just be cleaner to have the functionality directly in afrender.

You could argue that we could also replace the whole  'nimby_*' with custom scripts to detect usage and act accordingly.

**Comment by timurhai** [comment]
Why you want afrender to do it?
May be better some GUI (PyQt) application?
You can write your own or use CGRU Keeper.
If there are lots of unneeded items there (it is really so), we can config what items (menus) to show.

Keeper already shows afrender status - it is useful for this issue.

**Comment by lithorus** [comment]
Well, users are users :)

In my experience things go better if they don't have to think...

Also sometimes users can be logged in before afrender starts.

**Comment by timurhai** [comment]
"In my experience things go better if they don't have to think..."
 - Application will be in auto start, and will exit on logoff.
"Also sometimes users can be logged in before afrender starts."
 - So it is definitely should be done by some application, not by afrender.
