### ISSUE TITLE
Autodesk Maya 2018 Plugin not working

### ISSUE THREAD

**Issue by SoXX-TheFennec** [CGRU/cgru#440]
Hello,

as of today, I worked on bringing CGRU/Afanasy to work at my University. Blender works great but it seems that the May Plugin won't work or install correctly. I couldn't find an answer on the Forum and here on GitHub so I made this Issue.

We are using Maya 2017 and CGRu version 2.3.0. We tried everything but it seems that it just won't work. 
I know that you guys need more information and I provide that, I just don't know what exactly you need.

I hope you guys can help.

**Comment by timurhai** [comment]
Hi.
For what do you need that plug-in?
Most CGRU Maya features are scripted within MEL or Python and does not need any compiled library.
You can launch (source) such things yourself.
To create  CGRU menu you can run:
https://github.com/CGRU/cgru/blob/master/plugins/maya/cgru.mel#L21

**Comment by timurhai** [comment]
btw
There is a forum for such questions.
Here we are discussion concrete code changes only.

**Comment by SoXX-TheFennec** [comment]
Oh sorry for that, i open a new Topic in the Forum if i have more questions. Thanks
