### ISSUE TITLE
Logging of username when deleting jobs

### ISSUE THREAD

**Issue by lithorus** [CGRU/cgru#442]
Currently the server does not log which user deletes jobs. It would be helpful if the server logs when people eg. accidently deletes all done jobs when in GOD/VISOR mode.

**Comment by lithorus** [comment]
It might also be a good idea to add a confirmation dialog when doing 'delete all done' in GOD mode

**Comment by timurhai** [comment]
Hi.
Yes, confirmation dialog is needed there.
When user adds/deletes job(s), it appears in user log.

**Comment by lithorus** [comment]
Another option is to remove the "delete all done" when in GOD/VISOR mode

**Comment by timurhai** [comment]
Yes. I agree that "delete all done" is not needed in a super user modes.
