### ISSUE TITLE
Pause or not a render with AFCMD

### ISSUE THREAD

**Issue by Arubinu** [CGRU/cgru#443]
Hello,

I would like as the title says, pause or conversely a render.

I tried to see if a parameter allowed it but none of those available seems to do it.
I also tried with the JSON using the same object as the Afanasy interface or using the mask, but without success.

Moreover, no return of these requests on the output of the render.

Would it be possible to add this missing feature with eg ```afcmd rpaused true``` or ```afcmd rpaused false``` ?
Can we have a return on the output of the render ?

**Comment by timurhai** [comment]
Hi.
Yes, it is possible (and easy to add). But according to other afcmd commands style, it should be:
`afcmd rpause` and `afcmd runpause`

> Can we have a return on the output of the render ?
 - What output? Afrender daemon process stdout?

**Comment by Arubinu** [comment]
Hi timurhai, that would be great.

An output on the process of the ```afrender```, since it is he who is targeted.

I read the output of it and having this information would allow me to easily know the status without having to launch another order.

So a message that looks like the one displayed for a ```rexit``` would be welcome :)

**Comment by timurhai** [comment]
afcmd rpause and rupause added.

But i still did not got your other issue.
What so nice can return rexit, that other afcmd commands can't?

**Comment by Arubinu** [comment]
It's perfect, thank you :)
