### ISSUE TITLE
Replace the "stars" in Users with application icons

### ISSUE THREAD

**Issue by lithorus** [CGRU/cgru#444]
Would it make sense to replace the stars in the Users with the icons of the service?

When having a farm with mixed types of services running it would help to see who is taking which types of "ressources".

**Comment by timurhai** [comment]
Hi.
For now server does not count running tasks by service, just total running tasks.
But i am agree, some more informative about who and what is needed.

**Comment by timurhai** [comment]
![Screenshot_2020-06-23_17-20-20](https://user-images.githubusercontent.com/1492143/85415797-698f7880-b576-11ea-95f9-5465bd1aa115.png)
