### ISSUE TITLE
Empty env vars are ignored

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#448]
I am setting an env var on a block like:

`block.setEnv("test","")`

Checking on the block later, the env var is not existing. It seems the server is removing empty env vars.

It is useful to have those empty env vars, because empty can mean somthing like "use this value to reset a database field to "nothing""

**Comment by timurhai** [comment]
Hi.
It is here:
https://github.com/CGRU/cgru/blob/master/afanasy/src/libafanasy/name_afjson.cpp#L301
It was designed to remove some environment variable from a job that already was sent on server, from a GUI.
If we will read and append empty strings to map, how we will remove ability to edit such property.
Also i did not understand why you need empty vars?
You can edit that code and server will read empty strings. Test it.

**Comment by timurhai** [comment]
btw
We can append empty strings on creation only and remove empty string on changes.
* o_str provided for changes log, it is NULL on creation.
So if you change that code
`
		if( str.size())
			o_attr[name] = str;
		else
		    o_attr.erase( name)
`
on
`
		if (str.empty() && o_str)
			o_attr.erase(name)
		else
			o_attr[name] = str;
`
So it will be erased only when empty value provided on changes.
Any way erase play no role on creation. Somebody even asked:
`
		    o_attr.erase( name); // This does not erasing element, why ?
			//printf("erase(%s)=%d\n",name.c_str(),o_attr.erase( name));
`

**Comment by sebastianelsner** [comment]
That might be the solution, will test!

**Comment by timurhai** [comment]
Hi!
Any news on this issue?
