### ISSUE TITLE
Alembic ROP does not get exported correctly

### ISSUE THREAD

**Issue by manuelito02** [CGRU/cgru#450]
Hi there!

We have an issue with alembic ROP in Houdini that does not get written correctly when using Afanasy. What happens is that an alembic can contain more than one frame. But when using Afanasy to execute the Alembic ROP on the farm, the alembic file contains only the last frame. It looks like that the content, instead of getting appended frame by frame, does get replaced.
But when executing the ROP locally, it works as expected.

Am I missing a parameter somewhere or is this a bug?

Greets,
Carlo

**Comment by timurhai** [comment]
Does your submission contain this:
https://github.com/CGRU/cgru/commit/6f6daced0192083444048257d576c98e2a23d299#diff-bbb8ac9dc842251da615073de9fc8bba

**Comment by manuelito02** [comment]
Hey, thanks for your quick reply. Yes, I just checked the python file and it contains the added code of your diff.

**Comment by timurhai** [comment]
May be frame range problem.
Try to set on Alembic ROP "Render Frame Range Only (Strict)" and specify needed range.
And on Afanasy ROP "Render Current Frame" - this makes one task job.

**Comment by manuelito02** [comment]
I will check this tomorrow. Thanks for the hint. I'll keep you posted.

**Comment by manuelito02** [comment]
Hey, that made the trick! But I checked to put "Render Frame Range Only (Strict)" on the Afanasy ROP and this worked as well. The 'Strict' option seems to be the magic solution.

Thanks!

**Comment by somesanctus** [comment]
Y

**Comment by somesanctus** [comment]
Ddte
