### ISSUE TITLE
Set a task as DON, without SKP, via json.

### ISSUE THREAD

**Issue by hradec** [CGRU/cgru#455]
Since there's no way to do that on the UI, I was wondering if its possible via json to forcefully set a task as DON, without SKP. 

I'm asking because we have a check script that runs periodically double checking all jobs in afanasy, and verifying if the frames have being rendered correctly on disk, etc;

If the script detects an error on the rendered files, it restarts the frame task so the farm can re-render it. 

It's just a "safety net" in case something passes on by afanasy checking, so artists don't have to do the frame checking themselves.

It's specially useful in our case, since we have a cloud rendering mechanism which automatically upload rendered files back to our file system, so this check script can detect upload errors.

That's why a way to set a task as DON without SKP would came in handy. If an upload comes OK, I would like to set the frame as DON just like if the render was successful, even if something went wrong in the logs from the cloud render nodes. 

Sometimes we have weird errors on the cloud nodes, but the rendered files are actually OK. 

Today we set the frame task as DON SKP via JSON, but I would love to just set DON without SKP! 

make sense?

**Comment by timurhai** [comment]
Hi.
Such operation is not implemented on server.
Why SKIP is not useful in your case?

btw
There is only JSON protocol for changing something on server.
If something is possible, i can be possible only via JSON.

**Comment by hradec** [comment]
>
>
> Such operation is not implemented on server.
> Why SKIP is not useful in your case?
>
It's more about human visual identification for management than anything
else.
Artists at our studio use SKIP mostly when they want to limit a frame range
at a given time, but want to restart the render on those frames later on,
when the farm is less busy.

By having the checking script setting SKIP, we run into the problem of
wranglers restarting it since they assume it was skipped because it wasn't
rendered.
SKIP is stateless... There's no way to tell the reason it was skipped,
specially when the log can't be retrieved from the render node due to a
restart, or because it was rendered on the cloud and the render node
doesn't exist anymore.

Being able to set DONE via scripting would fix this problem making things
clean again, leaving the SKIP to be set/reset by artists only like it
should be.

make sense?

I think this DONE should be available via JSON only actually... as an
option for pipeline integration. There's no reason to be available in the
UI!

**Comment by timurhai** [comment]
Hi. Yes, now i see. Lets create an issue. But for now i can`t say when it can implemented. I am busy with render farm pools now.
