### ISSUE TITLE
Securing Web GUI

### ISSUE THREAD

**Issue by qbadev** [CGRU/cgru#456]
I would like to restrict access to GUI website host:51000. I am aware of this answer http://forum.cgru.info/viewtopic.php?f=17&t=1668, but maybe You could point me where to find a code responsible for web server or maybe even tell where to change its behaviour. Thanks.
Where to change port which server runs on?

**Comment by timurhai** [comment]
Hi.

This config option stands for server port:
https://github.com/CGRU/cgru/blob/master/afanasy/config_default.json#L

You can use VPN for Web, Qt GUIs and any other connections.

**Comment by qbadev** [comment]
I have already found a folder where website file are placed, but still would like to know, what www server it is. Can I modify it's configuration? Protect folder where website files are placed? Sth similiar to Apache Basic Authentication...

**Comment by timurhai** [comment]
Afanasy server is a www server.
And for now there is no protection (authentication) mechanisms.

**Comment by qbadev** [comment]
That's 2 things I already know. But where this server's binary files? Is this sth like Apache or Nginx, or maybe You did write from scratch?

**Comment by qbadev** [comment]
I think that You mean, that all afserver communications (Python client, or Desktop GUI) are done using webserver compiled into afserver binary file, right?

**Comment by timurhai** [comment]
Yes.
Afanasy server is a Web server too. Web server is not just "compiled in", it is the same program.
Afanasy uses JSON protocol, and so to serve Web GUI it just recognizes html header before it (POST request).
Also it can read and send files on GET request.

**Comment by qbadev** [comment]
Problem solved by copying multiple afanasy folders and file to desired location, creating proxy for afanasy server communication, and protecting the folder with HTTPAUTH native in apache web server. Now, works fine.

If anybode is in need, I could provide compressed copy of my clone.
