### ISSUE TITLE
Tickets

### ISSUE THREAD

**Issue by timurhai** [CGRU/cgru#459]
Ticket is like a "named" capacity.
Pools, renders and tasks (job blocks) can have some tickets.
Ticket has a name and count.
( tickets is a std::map<std::string, int32_t> )

If host has "MEM"x64 tickets, it can run 2 tasks with MEMx"32" tickets.
If pool has "NET"x1000 tickets, all its renders can run tasks with a total "NET" tickets sum <= 1000.
Root pool can have 100 "NUKE" tickets to limit licenses.
"hbatch_mantra" block can have "HYTHON"x1 and "MANTRA"x1 tickets for corresponding limits.

ps
We are already using pools at work. Now we have some extra farm within some special network. So our studio very-very need some mechanism to balance network load. And i have think up "tickets" (i decided to call named capacity so), and already started to implement it as we are very need it.

pps
Sorry, but other issues and #451 pull request (https://github.com/CGRU/cgru/pull/451) will be postponed. But i definitely will be back to it.

**Comment by sebastianelsner** [comment]
I think this is also solving #311 . no? If you give the root pool  100 "Nuke" tickets and 5 "NukePlugin" tickets and a block is defined to need 1 "NukePlugin" and 1 "Nuke" ticket per task, only 5 tasks IN TOTAL with the ticket "NukePlugin" will run on the pool! No?!

**Comment by timurhai** [comment]
Hi.
Yes i think it solves that issue.

**Comment by timurhai** [comment]
We started to use tickets in a real production.

**Comment by timurhai** [comment]
We are using it about several months. It seems that it works.
