### ISSUE TITLE
How to modify System Job capacity?

### ISSUE THREAD

**Issue by qbadev** [CGRU/cgru#463]
I use a powerfull server and would like to change System Job capacity. 
I added `af_task_default_capacity` with my custom value to config.json of my AfServer and AfRender, hoping it will be used by System Job, but it wasn't.
Is it even possible to achieve or hardcoded? Should I configure sth in farm.json? Tried searching through a code here on GitHub, reading docs, issues. I also read config files in my /opt/cgru folder.
Still no success.
**Note**  
At the moment, I am aware that I could play with AfRender capacity, but I am not willing to, as my application is already fine tuned for running, when AfRender capacity is 1100.

**Comment by timurhai** [comment]
Hi.
If system job already created, you can`t affect it by any config change (like any other job).
But you can change it via GUI (json), like any other job.
Note, that system job is visible only in GUI admin mode.

**Comment by qbadev** [comment]
Even if I restart AfServer? Does it take config values into account then?
I already did restart AfServer several times, but it is still 1000

**Comment by timurhai** [comment]
Server restart does not modify any parameter of any job (system or not, capacity or any).

**Comment by qbadev** [comment]
So, when are System Jobs started (instantiated)? Not when AfServer starts?

**Comment by timurhai** [comment]
System job created when a new (fresh, with an empty store) afserver starts. Later system job, like any other job is stored in a store, and server reads it from store on start.

**Comment by qbadev** [comment]
That was the clue. I navigated to `/var/tmp/afanasy/jobs/0.1.afanasy` and edited capacity values in `data.json` file. After restarting AfServer it is set as expected.
Thanks for the hint.

**Comment by timurhai** [comment]
It could be more simple to set it from GUI. But your way is working too.

**Comment by qbadev** [comment]
GUI? You mean web interface? I don't use GUI app run from command line

**Comment by qbadev** [comment]
But please tell me how to make this change permanent? I can only hope that data.json will not ever be removed or modified. But is it possible to change it once and never have to worry about it again?

**Comment by timurhai** [comment]
There are Web and Qt GUIs, both are using the same JSON protocol.
So, you can manipulate afserver (any job) via JSON protocol, and from a command line too.
Such manipulation does not need server restart.

Server store is permanent. Unless you will modify/remove it yourself.

**Comment by qbadev** [comment]
All answers I need. Thanks.
