### ISSUE TITLE
Can't create a branch

### ISSUE THREAD

**Issue by qbadev** [CGRU/cgru#467]
I tried to create a `branch` the same way as creating `user` is documented in [manual](http://cgru.info/afanasy/api#json_action). I sent JSON request to server, but it responded `Invalid action`.

I sent JSON like below:
```
{"branch":{
    "name":"user 1",
    "max_running_tasks":2
}}
```
Is it possible to create `Branch` any other way than with creating a `Job`?

**Comment by timurhai** [comment]
Hi.
For now you can create branches only by creating jobs.
Branches are supposed to represent a real files structure (department, projects or even shots).
