### ISSUE TITLE
AfWatch doesn't apply sort method when returned to Jobs tab.

### ISSUE THREAD

**Issue by eoyilmaz** [CGRU/cgru#468]
Sorting the list in the Jobs tab is working perfectly.

Let's say that the jobs are sorted by creation date:

![Jobs Sorted by Time Created ](https://lh3.googleusercontent.com/lTXD9j6HwWwiWN9tlmcWvi4SLootdtNtxzyuRiepFoeEQF31if-mG3P9-Mg2XcxTmjsFXHA7c5vxdgA9T5DlHZG3RWrnJeYgV0mvWZMNQTNMDQN65AYzn7wqwwRSNukYNZHYb5pxzw=w2400)

AfWatch doesn't apply the sort method when you switch to let's say Render and switch back to Jobs  tab.

![Jobs not properly sorted by Time Created anyore](https://lh3.googleusercontent.com/Lj0HfhnRiYMXt35uF8C242sw-7M5lftK2KYUOuoQrJ2d-xUAkLDMca6qBB0hfBWejVHhDATWyyWPkUpPPc1bmk9w1n5ExhqfIOnGN6ASd0YW2pES8pJKCAWv0u3UFk4r9vy8TwbOQg=w2400)

**Comment by timurhai** [comment]
Hi!
I can't reproduce this bug in the current master branch.
Afwatch has lots of changes, since it can hold several node types with a hierarchy.
(Branches and Jobs, Pools and Renders)

**Comment by eoyilmaz** [comment]
Hmm. I actually checked against 2.3.1 not the latest commit.

**Comment by eoyilmaz** [comment]
Okay checked against the latest version (6e410a22b45009dcf595977f7db0c93709a6d37b) and the problem still exists:

This is before going to Farm page:
![Jobs Sorted by Time Created ](https://lh3.googleusercontent.com/TvrszM52J0PZe7dSIWfldw8M-UtOJsQmU1YIWxEO9mVO1NWNa-oSnWEErdSmm58OhP_HMIwdymcYnZqGTTvmsGrsc-zmXmZxbjhAYT4huT1riOgDlP8g04JGJ7gZvMV4338PfU3Z8A=w2400)

And this is after going to the Farm page and returning back to the Jobs page:
![Jobs not properly sorted by Time Created anyore](https://lh3.googleusercontent.com/o6NlebvsLhnGD_yEbMgfsy2DcN4T07qL-rbAO7aF6Itzg8-tGOHjJUTKuT1Ou9M66eKXzpPhkffD0qs2ppeaIOExevfbgwusPi0ZuYkblMvvJGST2yXw_7toUriqMCSUDNLWGtpnFg=w2400)

Notice that the Sort method is still "Created" but the order is not correct!

**Comment by timurhai** [comment]
Now i see and fixed.
At seems that this bug was from very beginning.
If user is not admin, jobs list was always asking for user jobs order. And sort nodes on order (list of ids) received. But it should ask for an order, only if no sorting was chosen.
Bug was noticed after 10 years, means that users are not using jobs sorting much, only admins.
