### ISSUE TITLE
taskProgressChangeTimeout retries forever - ignores "Error Retries"

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#472]
I just tried to use the no_progress_for value and the server does kill the job after the specified amount of time, but it just keeps restarting the task forever instead of stopping after the number of times specified in "Error Retries"

Could it be that we need to add this
```
m_progress->state = m_progress->state | AFJOB::STATE_ERROR_MASK;
```
in here:
https://github.com/CGRU/cgru/blob/407142138934a73b92fafdf1a0bca3ba9566c63d/afanasy/src/server/taskrun.cpp#L305

**Comment by timurhai** [comment]
O! Yes!

**Comment by timurhai** [comment]
О! In that commit was other, but very minor changes.

**Comment by ultra-sonic** [comment]
Thx a lot Timur! Much appreciated!
