### ISSUE TITLE
QUESTION: I'm seeing a lot of "zombie" tasks stuck on render nodes, when those nodes are running over a vpn

### ISSUE THREAD

**Issue by hradec** [CGRU/cgru#479]
Hi there... 

Quick question... it's not an actual issue, just a bit annoying at times... 

I'm seeing a lot of duplicated "zombie like" tasks that stick to a render node forever, and I can't find a way to clear it up. 
![DeepinScreenshot_select-area_20200627145936](https://user-images.githubusercontent.com/806743/85933034-2b9c9800-b887-11ea-9d83-cc4315c6f66c.png)
`The yellow task at the top of the green one was done a long time ago, and got stuck at the render node and never disappears`

They show up on machines running remotely over a vpn (in this case, vm's at google cloud computing). They never show up on machines on the local network, so It does seems like a network latency related issue related or some error when VM's are preempted at google. It's possible that a VM is removed and another is added, and receives the same IP address. (which is this case, the render node will have the same hostname, but with different mac address)

I tried to tweak some of the afanasy network parameters, but didn't help. 

Rebooting the render node doesn't help,  neither restarting afanasy server. The node comes back and shows the zombie task again.  

It's funny, because those "zombie like" render tasks ended up being rendered and finished by the same node, or sometimes other nodes, and shows up on afanasy as DONE. But it seems afanasy doesn't remove then from the render node UI, even "knowing" the render task is finished and done!

It can be a little misleading at times, mainly because the time keeps running and you see a unfinished task with hours in the UI, but that task was finished a long time ago. 

If there was a way to force afanasy to remove that task from the UI via json, I could write a simple script that verifies if tasks are finished, and remove it. 

I'm running Afanasy 2.3.1, and apart from that it runs very smoothly and perfect!! 

thanks lots!!
Roberto

**Comment by timurhai** [comment]
Hi!

It will be very handy, if you will catch the bug, and tell me minimal movements to repeat it.

Is it a GUI only bug? If you relauch afwatch, zombie tasks will disappear?
If you relaunch afrender will old zombie tasks disappear, at least before new one will appear?
