### ISSUE TITLE
/bin/sh:nukeRender.sh:command not found

### ISSUE THREAD

**Issue by prnvprdp** [CGRU/cgru#480]
/bin/sh:nukeRender.sh:command not found

I am getting this error in output when i am trying to render nuke files.I tried checking environment is set in the render blade.Its running fine in the terminal.

**Comment by timurhai** [comment]
Hi.
``command not found`` means that your ``nukeRender.sh`` command not found.
So, if you have checked environment, and it works, means that you have checked some other environment.
You should check the same environment that afrender runs. The same user and the same other initialization scripts.

**Comment by prnvprdp** [comment]
How can I check environment in which afrender  is running

**Comment by timurhai** [comment]
It depends on how you are you running afrender.
What OS are you unsing?
As a system.d service by render user?
Did you set service/environment up somehow or you just installed afrender linux package?

**Comment by prnvprdp** [comment]
os is CENTOS 7
installed the linux package
i believe it was installed by root user

**Comment by timurhai** [comment]
Install Linux package and that is all?
CGRU does not have `nukeRender.sh` command.
So if you are adding custom commands, you should add them for afrender service too.

**Comment by prnvprdp** [comment]
i think the af.render is  running from root user and that doesnt  seem to have the environment i guess.

**Comment by timurhai** [comment]
You should definitely know what user afrender service is running, and change environment for cg-artist and render in the same way.

**Comment by prnvprdp** [comment]
actually it is trying to call a shell file.
how can i add my command to af render service

**Comment by timurhai** [comment]
You should create some custom `setup_custom.sh` in a cgru root folder.
https://github.com/CGRU/cgru/blob/master/setup.sh#L24
And source there some other custom setup file, the same for all other users and purpoces.
In that setup file you should add something in PATH variable.
This way anybody in your studio (afrender too) should be able to launch extra commands.

**Comment by prnvprdp** [comment]
I checked the environment, it is set system wide but somehow this is overwritten.Does this happen because of some permission issues? or is there any file that i can exclusively mention these paths?

**Comment by timurhai** [comment]
CGRU does not set the environment system wide and does not override any PATH, just appends few own.
On your system different processes has different PATH variable.
This is not a CGRU issue. And not for github. It is a common system administration question.
Try to ask some forum.
You can even ask me on a CGRU forum.
