### ISSUE TITLE
afserver doesn't start

### ISSUE THREAD

**Issue by ialebedev** [CGRU/cgru#482]
Timur, hi

I've installed afserver on our new server with Debian 10
But when I start it, I get this

`
me@server01:~$ sudo systemctl restart afserver
me@server01:~$ sudo systemctl status afserver
● afserver.service - Afanasy server daemon
   Loaded: loaded (/opt/cgru/afanasy/systemd/afserver.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-08-17 15:05:13 MSK; 4s ago
  Process: 30522 ExecStart=/opt/cgru/start/AFANASY/_afserver.sh -log_nodate (code=exited, status=217/USER)
 Main PID: 30522 (code=exited, status=217/USER)

Aug 17 15:05:13 server01 systemd[1]: Started Afanasy server daemon.
Aug 17 15:05:13 server01 systemd[30522]: afserver.service: Failed to determine user credentials: No such process
Aug 17 15:05:13 server01 systemd[30522]: afserver.service: Failed at step USER spawning /opt/cgru/start/AFANASY/_afserver.sh: No such proce
Aug 17 15:05:13 server01 systemd[1]: afserver.service: Main process exited, code=exited, status=217/USER
Aug 17 15:05:13 server01 systemd[1]: afserver.service: Failed with result 'exit-code'.
me@server01:~$ 
`
Can you help with this issue ?

**Comment by timurhai** [comment]
Just tried to compile and run on a fresh debian 10 (virtualbox).
Everything works fne.

Such questions better to ask on forum: https://forum.cgru.info
GitHub stands for a code related questions, development.

**Comment by ialebedev** [comment]
Hmm, can you give me info how to compile it?

Maybe it will be the easiest way.

Thanks

**Comment by timurhai** [comment]
https://cgru.readthedocs.io/en/latest/installation/installation.html#manual-project-build

**Comment by ialebedev** [comment]
Thanks a lot
