### ISSUE TITLE
Regression: Tickets in 3.x are not supporting licenses counted per host

### ISSUE THREAD

**Issue by mlesin** [CGRU/cgru#483]
There is a common type of licensing where you can run multiple instances of software on same host, occupying only single license.
In versions before 3.x that was implemented by farm/limits/service/maxhosts field in farm.json.
Now it is missing, and licenses are counted incorrectly.

**Comment by timurhai** [comment]
Hi!

Now tasks has TICKET_NAME:TICKET_COUNT pairs.
(std::map<std::string, int32_t> m_tickets)
Better not to add some special task ticket type.
Task (user, artist, submission script) should not know how farm admin going to limit it.
It should just know type and count.

Now pool tickets has count and usage fields.
Count is now much tickets the pool has.
Usage is the current usage.
And pool render will never take a task if usage >= count.

We can make pool to measure hosts along with usage.
Hosts will represent how much pool renders running this ticket,
no matter how much each.

And if we add a field max_hosts to pool ticket, we can limit hosts.

**Comment by timurhai** [comment]
3.1.0 Already released.
