### ISSUE TITLE
jobs should not get WDP state once they are DON

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#485]
is there a reason why jobs can have the WDP state even if they are DON?
Is this something that could be changed? If not where in the source would be the best place to adjust this behavior on our end?

**Comment by timurhai** [comment]
Hi!
Hm, now WDP state has no relation with DON.
I have not faced the situation where DON job with WDP state bother me.

There is a `void JobAf::checkDepends()` function:
https://github.com/CGRU/cgru/blob/master/afanasy/src/server/jobaf.cpp#L635
You can try to skip check just after this line `m_state = m_state & (~AFJOB::STATE_WAITDEP_MASK);` if job is DON.
Everything should be ok.
And make a pull request after test!
