### ISSUE TITLE
configure rendernode priority in farm.json

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#488]
Hi Timur,
I am pretty sure I have configured the priority of a rendernode in farm.json in the past but it does not seem to work anymore.
We are still on 2.3.0 over here at RISE.

Also over here I saw https://cgru.readthedocs.io/en/latest/afanasy/api.html in the "Set user priority" paragraph you are stating
"priority": "50"
as a string...is that correct?

Cheers
Oliver

**Comment by timurhai** [comment]
Hi!
No, farm.json was designed for capacity, services and some other settings, but not priority.
Thats an error in docs, fixed.

**Comment by ultra-sonic** [comment]
thanks for confirming this timur! closing ticket
