### ISSUE TITLE
Deb Package Ubuntu should depend on python3.8-dev

### ISSUE THREAD

**Issue by qbadev** [CGRU/cgru#493]
When installing `afrender` using `install_afrender.sh`, it is not possible to start service, as it can't find `libpython3.8` shared lib. I think this dependency should be added to list in the `deb` package.
Tested in Ubuntu 19 and 20.
Cgru versions tested: 2.3.1, 3.1.0

**Comment by timurhai** [comment]
Hi!
Just installed afrender a new fresh Ubuntu 20 and haven't faced this problem.
Ubuntu 20 has a system Python 3.8, and it is very strange that is hash't its libs by default.
May be you installed some other Python version?
(there is no deb packages for Ubuntu 19)
