### ISSUE TITLE
Parsers maya_redshift.py and redshift.py.

### ISSUE THREAD

**Issue by timurhai** [CGRU/cgru#494]
- There is no just maya.py parser. maya_redshift just inherits redshift and do nothing itself. May be better to create maya.py parser to process just maya stuff. It can be used in other maya_* parsers. It can find some global errors like `(kFailure):`?
- Redshift always appends every output line with "[Redshift]" prefix? Or it just an option? May be if it works standalone (if it can), it do not add prefix, as all output is its own?

**Comment by eoyilmaz** [comment]
Created a PR :+1:

**Comment by timurhai** [comment]
I added (kFailure) to maya errors:
```
self.str_error += [
            'Frame aborted',
            'Frame rendering aborted',
            'Fatal Error',
            '(kFailure)',
        ]
```
This is redshift errors array:
```
        self.str_error += [
            '[Redshift]No devices found. Aborting rendering.',
            'Frame aborted',
            'Frame rendering aborted',
            'Bad node type found: Redshift_ROP',
            'Bad node type found: redshift_vopnet',
            'Fatal Error',
            'Error an illegal memory access was encountered',
        ]
```
I see the same line in both, may be we can drop them?

Also at first adding "(kFailure)" to maya did not worked, because child class initialized both parents,
and `parser.parser.__init__(self)` is called twice. Second call clears first call arrays.
```
class maya_redshift(maya.maya, redshift.redshift):
    """Maya Redshift parser
    """

    def __init__(self):
        maya.maya.__init__(self)
        redshift.redshift.__init__(self)
```
Now I pushed this code to parser.py:
```
        if not hasattr(self, 'str_warning'):
            self.str_warning = []
        if not hasattr(self, 'str_error'):
            self.str_error = []
        if not hasattr(self, 'str_badresult'):
            self.str_badresult = []
        if not hasattr(self, 'str_finishedsuccess'):
            self.str_finishedsuccess = []
```
So second parser.py initialization does not drops arrays.
