### ISSUE TITLE
How to render one frame with multiple render

### ISSUE THREAD

**Issue by brilliant218** [CGRU/cgru#499]
As title. I'd like to know if afanasy could render one frame with multiple render at the same time with blender? If yes, how to setup the environment.

**Comment by timurhai** [comment]
Hi!

There are 2 ways to render 1 frame on several machines:
- Render engine supports rendering 1 frame on several hosts. In this case usually one host acts like a server (server) and others like a clients (slaves). Afanasy supports this scheme.
- Render tiles (parts on an image) on each machine. For example if you split an image 4x3 tiles, you can render on 12 machines at the same time, than stitch tiles via Afanasy task or manually in a your post-process software.

Blender CGRU "out-of-the-box" Afanasy submission add-on, does not support any.
You should know Python to split 1 frame over farm with Blender, or send a regions of an image manually, if Blender render settings supports it.
