### ISSUE TITLE
AFermer: Is Boost really needed?

### ISSUE THREAD

**Issue by timurhai** [CGRU/cgru#503]
Hi!
Is Boost really needed in AFermer?
Each library makes binaries harder to make to work on different computers and OS`es.
DEB and RPM packages should install them, Windows releases should contain them.
We already have a huge Qt library which has lots of tools.

**Comment by sergiy-nazarenko** [comment]
Hello! Yes - afermer use filesystem and python modules of boost. 
But you can easily get rid of afermer - leave it in some branch. Who wants to use that tool can use it from branch.

**Comment by RiLights** [comment]
Hi Timur,

We already not working on AFermer project, so as Sergiy mention, it makes sense to get rid of it from the main branch to not deal with useless dependencies.

**Comment by timurhai** [comment]
Wow! You are not using it? What GUI you are using, if you are still using Afanasy?
Do you know studios using it (may be they have connected with you for feedback)?

**Comment by RiLights** [comment]
I wish that Weta Digital (the place where I'm working now) would use Afanasy but they have their own scheduler.

Regarding Platige image: by the politics or some other reason (but it is not something that can be fixed on the Afanasy side) they shifting from Afanasy to Qube render manager - which is sad : (

**Comment by timurhai** [comment]
Very pity : (
