### ISSUE TITLE
player.html not working while logged in

### ISSUE THREAD

**Issue by karanbeniwal** [CGRU/cgru#504]
file: cgru/rules.php

line 352:
`$rec['url'] = $i_arg['url'];`

$i_arg['url'] is generating null value, which in turn corrupts the json generated.
by placing a null check on it, player works again:

`$rec['url'] = isset($i_arg['url']) ? $i_arg['url'] : '';`

Also, once logged in, I'm not able to log out of RULES.
After clicking on "logout" button, the page refreshes, but it doesn't log out.

OS: Windows 10

**Comment by timurhai** [comment]
Hi!
Strange, I see just a notice:
`PHP Notice:  Undefined index: url in /data/cgru/rules.php on line 352, referer: https://localhost/player.html `
But the check should be, thank you!
