### ISSUE TITLE
Any chance to update m_progress->last_percent_change outside af::TaskExec::UPPercent

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#509]
Hi Timur,
its me again :stuck_out_tongue_winking_eye: 
The no progress timeout is great but I would like to consider every log output as progress and not just a progress percent change like here:
https://github.com/CGRU/cgru/blob/66b6f3ebdcc8223199f10f48745ca3f51a487b27/afanasy/src/server/taskrun.cpp#L126

Do you have an idea on how one could implement this easily?

thx in advance
Oli

**Comment by timurhai** [comment]
Hi!
Afrender does not send any log lines on task progress update.
And it can't as there can be a huge amount of such messages (lots of running tasks on a big farm)
So task update message should have as small size as possible.
And Afrender sends task process output only on task finish.

For this issue, message should contain log lines count.
And a new block parameter should be added - some "task log timeout".

It is not a big deal to implement it, but it is not so easy.
Also AfRender uses "rocky" binary protocol (for traffic reasons, it is not a json), and it will loose binary compatibility on any new parameter added, so it will be 3.3.x version, and you should update server and all clients.

**Comment by ultra-sonic** [comment]
> For this issue, message should contain log lines count.
It might be the easiest to just send an int of the last update time to the server (basically moving the m_progress->last_percent_change from afserver to afrender)
The python parser must be able to update this value (like percent) so one could even trigger an update for jobs based on other metrics than log output.

> And a new block parameter should be added - some "task log timeout".
not sure if I would do that...I would consider this feature an enhancement/re-factor of the no_progress_for and would not make things more complicated by adding yet another option. if we make this accessible from the parser then people could still keep the "old" progress behavior.

> It is not a big deal to implement it, but it is not so easy.
Understood...we would greatly appreciate this once you find the time!

> Also AfRender uses "rocky" binary protocol (for traffic reasons, it is not a json), and it will loose binary compatibility on any new parameter added, so it will be 3.3.x version, and you should update server and all clients.
Fine for us...we always update afrender and afserver at the same time

Cheers
Oli

**Comment by timurhai** [comment]
Yes, you are right!

We can keep the same block parameter "task progress change timeout", and a parser (afrender side) should provide some "last progress time" integer(64).
This case we can choose by parsers what is "progress": percentage, stdout line, may be some special string (regexp).

And this is a new 3.3 version, as we should modify af::MCTaskUp message class and parsers (not all, but at least the base class).

**Comment by ultra-sonic** [comment]
sounds good to me :+1:

**Comment by timurhai** [comment]
Hi! Issue is done! Will be available in 3.3.0 release.

I decided that parser should not send server any time, when progress was changed.
We should not rely on time on a farm, it can differ from server time (bad situation, but server should work).
So parser checks and afrender sends to afserver one more boolean parameter `progress_changed`.

**Comment by ultra-sonic** [comment]
sounds great!
