### ISSUE TITLE
WRN tasks do not start

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#510]
Hi Timur,
sometimes after an afserver crash we have tasks in a WRN state that seem to be ignored by the solving algorithm. only if we restart those tasks manually they start again...for some reason they do not get reset to RDY after a server restart...
cheers
Oliver

@sebastianelsner

**Comment by timurhai** [comment]
Hi Oliver,
Threre should not be just WRN state, there should be (WRN & RUN) or (WRN & DON) state (flags). If task has DON flag, it should not be restarted on server restart. If on server start task has RUN flag, it takes WAITRECONNECT flag and waits for a some render that can reconnect running session.
btw,
On server crash!?
Do you have some server logs before the crash? May be you can repeat the crash?

**Comment by ultra-sonic** [comment]
thanks a lot for fixing this timur!!!!!
