### ISSUE TITLE
AfWatch does not use "icons_path" from config.json

### ISSUE THREAD

**Issue by lithorus** [CGRU/cgru#511]
As seen on this line, it only searches for icons from the main cgru location :

https://github.com/CGRU/cgru/blob/9092489cd25e283c12c96353dba7033504e4597c/afanasy/src/watch/watch.cpp#L65

**Comment by timurhai** [comment]
Hi!
Indeed, icons path is not configrable for AfWatch.
That variable is used in `cgru/lib/python/` only, and does not preset in any `*.cpp` file.
So it used in Python utlities only, but it will be handy to add it to AfWatch.

**Comment by timurhai** [comment]
Wow! It seems that we have made assignment at the same time!

**Comment by lithorus** [comment]
Closing this since it's merged to master
