### ISSUE TITLE
Support for custom config.json path

### ISSUE THREAD

**Issue by ghostvfx-jimmy** [CGRU/cgru#512]
This is related to the custom icons path. This way you can have a largely vanilla install of cgru and use environment variables to override eg. site specific config and/or custom parsers.

I was thinking calling it :
`CGRU_CUSTOM_CONFIG`

Was also thinking about adding :
`CGRU_CUSTOM_PYTHONPATH`
which will be prefixed to PYTHONPATH instead of suffixed so it can override/add custom parsers/services.

**Comment by lithorus** [comment]
Was logged in with wrong account. It was me who created the ticket :)

**Comment by lithorus** [comment]
Closing this since it's merged to master
