### ISSUE TITLE
Each not-numeric task should be able to have an own environment.

### ISSUE THREAD

**Issue by timurhai** [CGRU/cgru#513]
For now only job block has an extra environment, and every block task has the same environment.
Not numeric task should have an own extra environment, which will be added to the block general environment.

ps
Houdini PDG work items has almost the same command, and task specific data (like a frame) is passed via environment variables.

**Comment by lithorus** [comment]
Wouldn't it over complicate things?

You can add the environment variables prior to the command :
eg.
```bash
PDG_ITEM=42 /path/to/hbatch /path/to/filename
```
I'm currently also looking at doing a PDG implementation and didn't find the need for per task environment. It can also be achived by using a wrapper script.

**Comment by timurhai** [comment]
Hi!
Yes, it can be done by a wrapper, but task environment is easy to implement, so i decided to do it, and already finished )

**Comment by timurhai** [comment]
btw
I have already started to do PDG implementation.
It already works, but just only few callbacks are implemented.
I think that the next week i will commit some simple scheduler.

**Comment by lithorus** [comment]
Nice, will be interesting to see how it's being implemented. Hopefully I can use the same implementation and just create custom callbacks for our need (so we don't have to fork the submitter)

**Comment by RiLights** [comment]
Hi Timur,

I'm wondering which way of implementation did you choose? Static Hybrid (by your comment in PDG forum), dynamic task job/block expansion?
