### ISSUE TITLE
QTinterface

### ISSUE THREAD

**Issue by IvanZakharov11** [CGRU/cgru#516]
Hi
I would like to creat qt gui Watch interface for my program on qt designer. How can I connect to user qt interface? Could you, please, advice which files I should correct?

**Comment by timurhai** [comment]
Hi,
Afanasy already has a Qt interface - AfWatch.
So, you can copy its code, and modify it to create your own.

**Comment by IvanZakharov11** [comment]
that's the question.  Where can i find this qt file?

**Comment by timurhai** [comment]
All AfWatch sources are here:
https://github.com/CGRU/cgru/tree/master/afanasy/src/watch
