### ISSUE TITLE
Adding multiple versions of houdini

### ISSUE THREAD

**Issue by IvanZakharov11** [CGRU/cgru#519]
Is it possible to add multiple versions of Houdini to Keeper?

**Comment by timurhai** [comment]
Hi!
On start, Keeper reads this folder (and sub-folders) to construct menu items (and sub-menus).
https://github.com/CGRU/cgru/tree/master/start
There is no "Software" section out-of-the box, and Keeper constructs the default "Software" section.
You can create "Software" folder and fill it with own scripts.
That scrips can be called Houdini17, Houdini18, and so on, and run anything you want.

Also that scripts should construct a good environment, to make Afanasy run correct Houdini version later.

**Comment by IvanZakharov11** [comment]
thank you very much, master))
