### ISSUE TITLE
Frame not finishing

### ISSUE THREAD

**Issue by MikhailPasechnik** [CGRU/cgru#528]
render: Redshift 3.0.54
application: Maya Batch 2022

Frames not finishing and stuck.
For one scene everything is OK for another all frames not finishing.

After frame is rendered from 0% to 100% 

![image](https://user-images.githubusercontent.com/11280047/143039318-971ed138-e00e-47d9-ab43-65ec2968d90f.png)

progress resets to 0% and nothing is happening after it.

![image](https://user-images.githubusercontent.com/11280047/143039577-35bc693f-52d8-4659-9271-f357321e6dfb.png)

Render node is still holding frame even it is already rendered.

config
```{
  "name": "frame 1",
  "service": "maya_redshift",
  "capacity": 1000,
  "time_start": 1636537333,
  "job_id": 5,
  "block_num": 0,
  "task_num": 0,
  "command_block": "mayarender -r file -s @#@ -e @#@ -b 1 -rl \"rs_CH_a\" R:/***/render_e01_sq100_sh030_v01.ma",
  "command_task": "",
  "frame_start": 1,
  "frame_finish": 1,
  "frames_inc": 1,
  "frames_num": 1,
  "parser": "maya_redshift",
  "working_directory": "C:\\Program Files\\Autodesk\\Maya2022\\bin"
}
```
[af_output.txt](https://github.com/CGRU/cgru/files/7588666/af_output.txt)

Need help on how to debug this and where to find logic in repository behind this behaviour?

**Comment by timurhai** [comment]
Hi!
This meand that command has not finished.
Afrender runs a command that should finish after everything is done, parsers can parse percentage and images this time.
Try to run "command_block" manually in a console (cmd.exe).
Will it be the same behaviour?
