### ISSUE TITLE
Afwatch: It is not possible to select anything on the Farm Page

### ISSUE THREAD

**Issue by eoyilmaz** [CGRU/cgru#542]
I'm using 3.2.2, in Afwatch Farm Page, it is not possible to highlight anything by left clicking. The right column seems to be updating but nothing is highlighted and it is not possible to set NIMBY, nimby or Free. In the video below, I'm left clicking on the rows. 

![2022-06-06_09-40-29](https://user-images.githubusercontent.com/1786804/172127268-52500527-3552-4ab1-9a11-83bd10a70f50.gif)

I would have fixed it by myself, but I the C code is not getting compiled under Fedora 36.

**Comment by timurhai** [comment]
Hi! Selecting (so manipulating) is availdable for admins (GOD mode) only.

**Comment by eoyilmaz** [comment]
Yeah, there was something like that, right. So, a related error message on the status bar would be better I reckon.

**Comment by eoyilmaz** [comment]
I can't seem to find how to change the user, the documentation suggest writing down the password on an active Watch page, but this is not clear.

**Comment by SteffenDuenner** [comment]
This is very weird and nerdy when you're new to Afanasy ;)

Just open afwatch, make sure the window is active and type one the keyboard "iddqd". You're in god mode.
If you repeat "iddqd" you're in user mode again.

**Comment by eoyilmaz** [comment]
> This is very weird and nerdy when you're new to Afanasy ;)

I've been using and contributing to Afanasy, I believe, since 2013, I knew it had a login feature, but never have to use it some how.

Thanks for the heads up by the way.

In terms of GUI usability, I think we should think on having a ``Login`` option in the menu.

**Comment by timurhai** [comment]
Just ensure that some widget have not grubbed the keyboard.
For example, keyboard can be grubbed by Info and Filter widget (QLineEdit).

Yes, we can crate a menu to change to visor / god mode and back to user.
Also, I agree, it can be some message, that selectiong is not allowed in user mode.

**Comment by eoyilmaz** [comment]
I'm closing this ticket and opening a new one about the login menu option and a dialog for that.

**Comment by SteffenDuenner** [comment]
> I've been using and contributing to Afanasy, I believe, since 2013, I knew it had a login feature, but never have to use it some how.

Sorry, I knew you're an old school Afanasy contributor, I just didn't phrase that right: I meant to say "even if you're not new to Afanasy, this login method is very unusual to say the least" ;)

**Comment by eoyilmaz** [comment]
Sorry, my fault, I didn't phrase it right too, I exactly meant the same thing with you :smile:
