### ISSUE TITLE
where do I configure CONNECTION_LOST_TIME for afrender?

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#548]
hi timur, is there a counterpart for afrender that can be configured in a config.json file?
https://github.com/CGRU/cgru/blob/7d6e18da7f9e79b0cc78f64919a66eab77c14572/afanasy/src/libafanasy/environment.cpp#L66

**Comment by timurhai** [comment]
Hi Oliver,
https://github.com/CGRU/cgru/blob/7d6e18da7f9e79b0cc78f64919a66eab77c14572/afanasy/src/libafanasy/environment.cpp#L306
https://github.com/CGRU/cgru/blob/master/afanasy/config_default.json#L158

**Comment by ultra-sonic** [comment]
Hi Timur, this seems to be the af_watch connection lost time....is this also used by af_render?

**Comment by timurhai** [comment]
Hi Oliver,
Sorry, my mistake, it seems that I confused afrender and afwatch.
Sine pools appeared, such afrender network parameters are configured on pool (for an ability to vary them per pool).
Afrender connection lost time that is used on client side parameter disappeared, now afrender and afserver use the same zombie time parameter to consider that connection is lost.
