### ISSUE TITLE
rez should use REZ_USED_RESOLVE not REZ_USED_REQUEST

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [CGRU/cgru#550]
Rez support was added via https://github.com/CGRU/cgru/pull/539
However it current uses the _requested_ environment via the us of `REZ_USED_REQUEST`, not the resolved one that is actually in use `REZ_USED_RESOLVE`. This can lead to situations where renders running in a rez configured environment could be running different application versions, which seems antithetical to use of rez in a render farm setting.

If we switch over to using the `REZ_USED_RESOLVE` environment variable then we are guaranteed to be using the same environment that was used for the submission.

What do you think @eoyilmaz ?

**Comment by eoyilmaz** [comment]
Yeah that’s definitely a better idea 👍

**Comment by eoyilmaz** [comment]
Fixed in #551
