### ISSUE TITLE
Application _LOCATION environment variable being being overridden in rez environment on Windows

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [CGRU/cgru#553]
@eoyilmaz Added rez supported was added in https://github.com/CGRU/cgru/pull/539, but this only seems to be for Linux.
Currently the `*_LOCATION` environment variable is being overridden in the `cgru/software_setup` scripts. 

For example, when launching Houdini from Keeper that was started from a rez environment I have `HOUDINI_LOCATION` already set. So 

https://github.com/CGRU/cgru/blob/fd58731c4d4a770f2a256a83eb3ca2ed33ed5131/software_setup/setup_houdini.cmd#L4

Should become something like

```cmd
IF NOT DEFINED HOUDINI_LOCATION (
    For /F "Tokens=*" %%I in ('dir /b "C:\Program Files\Side Effects Software\Houdini 1*"') Do set "HOUDINI_LOCATION=C:\Program Files\Side Effects Software\%%I"
)
```

**Comment by eoyilmaz** [comment]
@Anti-Distinctlyminty would you like to implement the Windows part.

**Comment by Anti-Distinctlyminty** [comment]
I can give it a go. I cannot test all the applications as I do not have access to them all, but I will do what I can.
