### ISSUE TITLE
Не понимаю, зачем нормализовывать этот путь. Он ведь разворачивает слеши у винды и тогда на такую конструкцию (mayarender -s 1 -e 1 -b 1 -rl "defaultRenderLayer" -proj r"\\alpha\itsalive\" //alpha/itsalive/test.mb.221212-170252-696.mb) прилетает ошибка Missing file name. Когда я развернул слеши вот так //alpha/Itsalive, процесс запустился.

### ISSUE THREAD

**Issue by alexcubor** [CGRU/cgru#557]
https://github.com/CGRU/cgru/blob/b1f3b15ebf66f91d25b3ea26a79a45561b47bb2b/plugins/maya/afanasy/__init__.py#L82

**Comment by timurhai** [comment]
А вы уверены, что тот, кто это написал, понимает по-русски?
На этом сайте, на этом проекте общаются по английски, хоть и для большинства это не родной язык.
Английский тут для большинства тоже не родной, но все разработчики этого проекта его знают и общаются.

В телеге есть канал https://t.me/cgruafanasy, там на-русском, там и маю на винде юзают.
