### ISSUE TITLE
Error! Not have method reverse for list

### ISSUE THREAD

**Issue by alexcubor** [CGRU/cgru#560]
https://github.com/CGRU/cgru/blob/b75c1cb50dacbb9e0fbd20fb18c9b9ff0b2ce9f4/plugins/maya/afanasy/maya_ui_proc.py#L358

I suggest changing the line to:
```
labels = list(renderLayers.values())
list(reversed(labels))
```

**Comment by eoyilmaz** [comment]
Would you like to create a pull request for this.

**Comment by timurhai** [comment]
Python list has method reverse()
May be the error is somewhere else?

**Comment by timurhai** [comment]
Maybe labes is not a list just after this:
labels = renderLayers.values()
Maybe there should be:
labels = list(renderLayers.values())
