### ISSUE TITLE
Manual still refers to EOL version of Python

### ISSUE THREAD

**Issue by IcedQuinn** [CGRU/cgru#561]
The manual mentions needing Python 2.7 which has been dead for some time now. It looks like this toolchain has already updated to Python 3 though?

https://cgru.readthedocs.io/en/latest/installation/installation.html

**Comment by timurhai** [comment]
Hi!
It just says, that the minimal compatible Python version is 2.6.
You can't build the project against Python 2.5 or lower.
Python 3 is supported, you can the project  against the latest Python 3 version (3.11 for now).
