### ISSUE TITLE
afserver breaks job, which causes 'Segmentation fault (core dumped)' crashes

### ISSUE THREAD

**Issue by eberrippe** [CGRU/cgru#563]
Hello @timurhai,

We recently updated to version 3.3.0 and encountered an issue with our "testjob" that was run in January. The job was left on the farm and two days ago the Afserver crashed with the message "Segmentation fault (core dumped)". Despite our attempts to restart the server, it kept crashing.

Upon further investigation, we discovered that the "testjob" was causing the issue, and moving it out of the /usr/tmp/afanasy/jobs/0 directory allowed the server to start normally. Additionally, we found the following information:

- The server can be started with the testing job inside, but it will crash as soon as a render connects to the Afserver.
- Removing the block content from the attached data.json file resolves the issue.
- Changing the block flag to 33 also prevents the server from crashing.
- Copying a block.json file from another block also resolves the issue.

We are concerned about this issue and would appreciate your help in resolving it. We have developed an "afjobsFixer" script that checks all jobs in the Afanasy job structure. If the job has no tasks folder, no block.json file, and the data.json file has a flag of 32, we change it to flag 33. This fixes any broken jobs before we restart the server.

We have attached all the information we have regarding this issue. Thank you in advance for your assistance.

**Afserver log:**
`
Fri 24 Feb 10:10.42: INFO    Listening 51000 port...
Fri 24 Feb 10:10.56: Render:  stationxxxx@eberrippe[7] unix linux 64 3.3.0 127.0.0.1 ON 
Segmentation fault (core dumped)
`

**Strucuture of data.json**
![jobStructure](https://user-images.githubusercontent.com/53370419/221138236-832bb82a-f6ef-44d0-ad80-fbf603fd7f89.png)

**Content of data.json**
`{
"name":"test_py_cmd-1",
"id":3,
"priority":201,
"custom_data":"{\"xx\": \"xxx\", \"xx\": \"xxx\"}",
"solve_method":"solve_order",
"solve_need":"solve_tasksnum",
"serial":2,
"user_name":"xxx",
"host_name":"stationxxx",
"st":1,
"state":" RDY",
"ignorenimby":true,
"ignorepaused":true,
"branch":"/",
"user_list_order":0,
"time_creation":1673028727,
"time_started":1676974801,
"blocks":[
{
"command":"python -c 'print(1)'",
"tasks_name":"",
"parser":"generic",
"working_directory":"/tmp",
"name":"test_py",
"service":"generic",
"capacity":1000,
"flags":32,
"tasks_num":1,
"frame_first":0,
"frame_last":0,
"frames_per_task":1,
"frames_inc":1,
"time_started":1673028727,
"time_done":1673028734,
"hosts_mask":"stationxxxx.*",
"block_num":0
}]
}`

**Comment by timurhai** [comment]
Hi!
Playing with the first flags bit, you switch block to numeric.
https://github.com/CGRU/cgru/blob/master/afanasy/src/libafanasy/blockdata.h#L53
Yes, not numeric jobs should contain tasks information.
Not numeric should not, tasks are generated by demand (on-the-fly).
So such jobs are really broken.
How such jobs can appear? After what.

**Comment by timurhai** [comment]
Strange situation, never heard about it.
So you send a job with a **numeric** block.
Than for some reason server stops (craches).
And its store became broken?
May be it happens with some kind of jobs only?
Can you check your store on a working server, when the store breaks?
May be some kind of jobs it always store broken (- and this is the bug).

Yes I can write some patch that force job to be not numeric, if it is no tasks data.
 
But better to find out the reason, there is some other bug.

**Comment by sebastianelsner** [comment]
It seems this was a one time thing. So if it is not happening again "soon", just let it go (like: [here](https://youtu.be/L0MK7qz13bU?t=63))

**Comment by timurhai** [comment]
Hi!

I just add a check for a validness reading a job from store.
That check was written to check incoming new jobs, that can be invalid constucted - numeric and tasks data mess.
Now such jobs will be deleted from store.

But I still do not know, how new job can pass this test on register. And later cannot pass on store reading.
Job was initially numeric, so this is not a situation when tasks data was not stored for some reason.
And it is not sitiation on server hung during storing, as json file has no systax errors.
This is a situation when somehow we lost numeric flag.
Or there is some bug on server, or its store was modified by something esle.

Anyway stored job cheching is needed.
