### ISSUE TITLE
Knowing the Job ID, Block Num and Task num inside a job

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#570]
I had a use case where it would be very beneficial to know the current job ID inside the rendering process. This way  for example you can have houdini, nuke etc save the job id or job serial in the exr header for later reference. Or you can have a task control its own job via the json API.
I think this would be best done as a environment variable that is automatically created by afrender when it starts the job. The env var is then passed to the process the usual way similar to the manually created env vars which are stored on the block.
I propose to have these env vars:

$AF_JOB_ID
$AF_BLOCK_ID
$AF_TASK_ID

@timurhai  do you think this is doable and makes sense? Maybe you can guide me to the place where this would be best implemented.

**Comment by timurhai** [comment]
Hello!
You are already using this? How is going? Everything as expected? There are no errors?

**Comment by sebastianelsner** [comment]
Yes, I am using this. There are no errors, it compiles fine. I am just a Beginner with c++, so if you could give it a look in terms of memory or possible side effects, that would be great.

**Comment by timurhai** [comment]
It is ok!
