### ISSUE TITLE
Jobs with json in custom_data are invalid on server restart

### ISSUE THREAD

**Issue by lithorus** [CGRU/cgru#574]
When a job is created with json in the custom_data property the job is discarded by the server.

This is due to the job data on disk is also encoded as json and the custom_data is not escaped.

Code to reproduce it :
```python
import json

import af

job = af.Job("Job with custom data block")

block = af.Block("block with custom data")
task = af.Task("test")
task.setCommand("echo 0")
block.tasks.append(task)
custom_data = {"test": "a"}
block.data['custom_data'] = json.dumps(custom_data)

job.blocks.append(block)
job.send()
```

**Comment by sebastianelsner** [comment]
Strange. I use the newest version and have lots of custom data... and this is not happening....

**Comment by timurhai** [comment]
Any af::Node has custom data and it is esceped on writing:
https://github.com/CGRU/cgru/blob/master/afanasy/src/libafanasy/afnode.cpp#L108
But af::BlockData is not af::Node it was not.
May be you are using custom data on Nodes only (User, Job, Render,...).

**Comment by sebastianelsner** [comment]
Ah! I am using it on the job. Did not know its possible on the block! Nice!
