### ISSUE TITLE
WebUI: When clicking on the parameters menu nothing happens

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#577]
![Selection_006](https://user-images.githubusercontent.com/902798/234533632-7ab97a67-00ef-4446-8e75-17bc403de4b8.png)

There is no error in the console or any other output. Should there be something happening?

**Comment by timurhai** [comment]
Hello!
It just uses the same functions for all monitor windows, but block and task items does not add any parameters there.

**Comment by sebastianelsner** [comment]
Ah, I see, so editing Block parameters is not possible in web ui?

**Comment by timurhai** [comment]
It it possibe, but not implemented.
