### ISSUE TITLE
Solve order not working as expected

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#583]
Hello!

I setup a new Afanasy server with the newest version. The job solving does not work as I was used to. Previously (v2.3.1) I had it in a way that the tasks were rendered in order of the creation of the job. For this I set the parameters of all branches to:

```json
  "solve_method": "solve_order",
  "solve_need": "solve_capacity",
  "solve_jobs": true,
```
The webui shows this:

![Selection_014](https://github.com/CGRU/cgru/assets/902798/2d4dab3b-3210-4ccd-a07e-726f28bc6736)

I dont need to have any "fair" or "cooperative" behaviour at all and just need the jobs to be worked in in a sequential fashion.

Has there changed anything in the new version 3.3 which i need to add in the config?

**Comment by sebastianelsner** [comment]
I think I understand now what the actual issue is:

To reproduce, assume we have one renderclient. We have multiple jobs,  each job has 4 Blocks. Blocks depend on the one before in the same job, so Block 4 depends on Block 3, Block 3 on Block 2 etc.

What happens now is that once Job 1 Block 1 is done the server will solve in a way that Job 2 Block 1 is run next. But that is not what is wanted, we want Job 1 Block 2 to run after Job 1 Block 1. Job 1 is older and even may have a higher prio. You can see  the behaviour in the Video I attach.

 If I remove the block dependencies, this is no happening and the one client will work on Job 1 Block 1, then Job 1 Block 2 etc.

Generally, I set the `solve_jobs` to `true`. Otherwise the farm is completely new bootstrapped and has default settings.

Is this by design?

https://github.com/CGRU/cgru/assets/902798/d650c5ac-10d7-4ceb-9a62-c8b9308caf30

**Comment by timurhai** [comment]
On a test farm already running from that moment - all good.
Today or tomorrow I will update our real farm.

**Comment by timurhai** [comment]
Hello!
It works for a month on our farm.
