### ISSUE TITLE
how do I get the capacity  of the current render-node within the parser/service

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#589]
Hi Timur,

the capacity of our render-nodes equals the amount of threads the system can run. During daytime we reduce this capacity to 80% on artists workstation to still be able to render while artists work on them.

we are setting the threads via service.py and right now our only way of getting the current capacity of an afrender-client is to query it from afserver which sometimes does not work properly. is there a way to make all properties (capacity and if possible also tickets) of the current render-node available in python without asking the server?

cheers
Oli

@sebastianelsner

**Comment by timurhai** [comment]
Hi Oliver,

Such render node information is not available for now. But can be implemented.

**Comment by timurhai** [comment]
Also, there is an issue about tickets:
https://github.com/CGRU/cgru/issues/562
May some other render useful info can be passed too.

**Comment by ultra-sonic** [comment]
> Such render node information is not available for now. But can be implemented.
Thanks for confirming this. Looking forward to 3.4.0 already!

**Comment by timurhai** [comment]
As new `af::TaskExec` class have custom fields, it is not a big deal to add some more info without compatibility break.

For example to close this issue I just added few lines:
```
	i_taskexec->setDataInteger("render_capacity_total", findCapacity());
	i_taskexec->setDataInteger("render_capacity_used",  m_capacity_used);
	i_taskexec->setDataInteger("render_tasks_maximum",  findMaxTasks());
	i_taskexec->setDataInteger("render_tasks_running",  m_tasks.size());
```
At the end of `RenderAf::addTask()` finction.
