### ISSUE TITLE
exception in service.py causes tasks to be skipped

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#590]
Hi Timur,

we are currently running into an issue where exceptions (like IOError [Errno 28] No space left on device) cause a task to be skipped and want to ask if this would be the right place to fix this:
https://github.com/CGRU/cgru/blob/1634d57862b5e0a1bee1bdcea62e70cb672eb976/afanasy/src/render/taskprocess.cpp#L113
or should this rather be done here:
https://github.com/CGRU/cgru/blob/1634d57862b5e0a1bee1bdcea62e70cb672eb976/afanasy/src/server/taskrun.cpp#L154

I cant find any other reference to af::TaskExec::UPSkip so I would propose setting the status to AFJOB::STATE_ERROR_MASK instead of AFJOB::STATE_SKIPPED_MASK in this case.
I also cannot imagine a case where an empty command would be sent on purpose.

do you think this is safe to do?

@sebastianelsner

**Comment by timurhai** [comment]
May be i should make service to skip task in some other way, not by an empty command.
I will be good to have some service initialization check, an on its fail send some `UPFailedToInitializeService`.

**Comment by ultra-sonic** [comment]
Thanks for the quick reply Timur!!! Much appreciated!

> May be i should make service to skip task in some other way, not by an empty command. Also it will be good to have some service initialization check, an on its fail send some `UPFailedToInitializeService`.

This would be great to have for sure!

**Comment by timurhai** [comment]
Not on server, on render in this line:
https://github.com/CGRU/cgru/blob/master/afanasy/src/render/taskprocess.cpp#L121

I already added sevice initialization check. May it will solve your problem.
Ther next step (today-tomorrow) i will create a special function for service to skip (not by zero command).
And on zero command it will be UPFailedToStart (error for server).

**Comment by ultra-sonic** [comment]
Great news Timur! Thanks for the quick fix! You're the man!
