### ISSUE TITLE
Lots of errors on job nr. 1 / events block

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#597]
Hello!

I am seeing a lot of errors on our "afanasy" job nr. 1 on the events block's task. In the log all of them say: "Failed to start". 

I checked the c++ code and could it be that it is happening because of this line?

https://github.com/CGRU/cgru/blob/b6de019008f9fe0ded3944920d53b649c8bb9d39/afanasy/src/render/taskprocess.cpp#L129

I think event tasks do have an empty cmd and thus report an error?!

**Comment by timurhai** [comment]
Now it is an error.
https://github.com/CGRU/cgru/blob/b6de019008f9fe0ded3944920d53b649c8bb9d39/afanasy/src/render/taskprocess.cpp#L118
There should be an empty commands. Empty command can happen due some error in a service python code.
But now, check for skipping goes first:
https://github.com/CGRU/cgru/blob/b6de019008f9fe0ded3944920d53b649c8bb9d39/afanasy/src/render/taskprocess.cpp#L118
So, if you want to skip a command launch you should set `self.skip_task = True`:
https://github.com/CGRU/cgru/blob/b6de019008f9fe0ded3944920d53b649c8bb9d39/afanasy/python/services/service.py#L195

**Comment by timurhai** [comment]
This was discussed here:
https://github.com/CGRU/cgru/issues/590

**Comment by sebastianelsner** [comment]
yep, I understand, thanks for posting issue #590, that was the one I was looking for! BUT does the change of 

https://github.com/CGRU/cgru/blob/b6de019008f9fe0ded3944920d53b649c8bb9d39/afanasy/src/render/taskprocess.cpp#L129

make event tasks fail?? Or is this something that is just happening for me and the reason is something else?

**Comment by timurhai** [comment]
Latest commit fix common event class:
https://github.com/CGRU/cgru/commit/b6de019008f9fe0ded3944920d53b649c8bb9d39
There is 3.4.0 in master branch now, it is under develop.
But we use it in production.

**Comment by sebastianelsner** [comment]
Got it, we need to port some of your changes as well.
