### ISSUE TITLE
Lot of task output slows down rendering

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#611]
Hej, today we have noticed an issue: 

When a houdini's husk task outputs *A LOT* to stdout the task takes much longer (10x and more) to render if rendered via afanasy. If the command line of the task is run directly in the terminal we do not see the slowdown.

I tested some things and when I change 

```c
const int TASK_READ_BUFFER_SIZE /**/ = 1024 * 1024; ///< Task process read buffer.
```

to 

```c
const int TASK_READ_BUFFER_SIZE /**/ = 1024 * 1024 *1024; ///< Task process read buffer.
```

the slowdown is nearly gone when rendering via afanasy.

Can it be the buffer is getting full which slows down the rendering?

This may also be caused in combination with our render heartbeat set to 10 seconds. Because the stdout's buffer is only cleared every 10 seconds then, right?

**Comment by timurhai** [comment]
Hello!
Yes, task process waits i/o in this case.
TASK_READ_BUFFER_SIZE should be configurable.
1GB is a lot for some special small machines for a special tiny tasks.

**Comment by sebastianelsner** [comment]
Ok, understood. I might lower and test with 100MB :D Thank you for the confirmation!

**Comment by timurhai** [comment]
Hello! Lets make this parameter configurable!

**Comment by timurhai** [comment]
Hello!
So, what we are going to do?
Just make it configurable and close the issue, or we should find a solution to not to slow process in any case?

**Comment by sebastianelsner** [comment]
Hej, I am testing as we speek. Will provide a updated PR soon.

**Comment by timurhai** [comment]
Ok. Lets merge it!
Soon we will update out farm.
